// System Design Master Roadmap — chapter-based course.
// Reuses the AiePhase shape (phases as chapters) for the Next.js learning app.

import type { AiePhase } from "@/types";

export const SYSDES_PHASES: AiePhase[] = [
  // ─── CH 01 ──────────────────────────────────────────────────────────────
  {
    num: 1,
    phaseLabel: "CH 01",
    kind: "phase",
    title: "How the Internet Works",
    subtitle:
      "Every system design interview assumes you know this. Most candidates don't. Own it.",
    miniProjectTitle: "Network Debugging Toolkit",
    miniProjectDesc: "Build CLI tools that expose networking internals:",
    miniProjectChecklist: [
      "Implement DNS resolver using raw UDP sockets (not dnspython)",
      "TCP port scanner: concurrent SYN checks across a CIDR range",
      "HTTP tracer: show every redirect, TLS handshake time, TTFB",
      "Wireshark capture: capture and annotate a 3-way handshake",
      "Compare HTTP/1.1 vs HTTP/2 latency on the same endpoint (use hyperfine)",
    ],
    sections: [
      {
        id: "ch1-osi",
        label: "1.1 OSI & TCP/IP Models",
        heading: "The 7 OSI Layers",
        tone: "table",
        table: {
          headers: ["Layer", "#", "Protocol Examples", "What It Does"],
          rows: [
            ["Application", "7", "HTTP, DNS, SMTP, FTP", "What the user/app sees"],
            ["Presentation", "6", "TLS/SSL, JPEG, JSON", "Encoding, encryption, compression"],
            ["Session", "5", "RPC, NetBIOS", "Open/close/manage sessions"],
            ["Transport", "4", "TCP, UDP", "End-to-end delivery, ports"],
            ["Network", "3", "IP, ICMP, BGP, OSPF", "Routing across networks"],
            ["Data Link", "2", "Ethernet, WiFi, ARP", "Node-to-node on same network"],
            ["Physical", "1", "Ethernet cable, Fiber, Radio", "Raw bits on wire"],
          ],
        },
        bullets: [
          "TCP/IP model collapses OSI 5-7 into Application, 3 into Network, 2 into Link",
          "In interviews: focus on L4 (TCP/UDP) and L7 (HTTP) — that's where design decisions live",
          "TLS sits between L4 and L7 (sometimes called L4.5 or L5)",
        ],
      },
      {
        id: "ch1-tcp-udp",
        label: "1.2 TCP vs UDP",
        tone: "table",
        table: {
          headers: ["Property", "TCP", "UDP"],
          rows: [
            ["Connection", "3-way handshake required", "Connectionless"],
            ["Reliability", "Guaranteed delivery", "Best-effort, may drop"],
            ["Ordering", "In-order delivery", "No ordering guarantee"],
            ["Flow control", "Yes (sliding window)", "No"],
            ["Speed", "Slower (overhead)", "Faster (no handshake)"],
            ["Use cases", "HTTP, DB, email, SSH", "DNS, video streaming, gaming"],
            ["Header size", "20 bytes min", "8 bytes"],
          ],
        },
        bullets: [
          "TCP 3-way handshake: SYN → SYN-ACK → ACK (adds ~1 RTT latency)",
          "TCP slow start: begins congestion window at 1 MSS, doubles each RTT",
          "TCP TIME_WAIT: socket stays open for 2*MSL after close (avoid port exhaustion)",
          "QUIC (HTTP/3): UDP-based protocol with reliability built in — best of both",
        ],
        sources: [
          { label: "Cloudflare Learning Center — TCP/IP", url: "https://www.cloudflare.com/learning/ddos/glossary/tcp-ip/" },
          { label: "Julia Evans — Networking Zines", url: "https://jvns.ca/networking-zine.pdf" },
          { label: "Beej's Guide to Network Programming", url: "https://beej.us/guide/bgnet/" },
        ],
      },
      {
        id: "ch1-http",
        label: "1.3 HTTP Deep Dive",
        tone: "table",
        table: {
          headers: ["Version", "Transport", "Key Feature", "When to Use"],
          rows: [
            ["HTTP/1.0", "TCP", "One req per connection", "Legacy only"],
            ["HTTP/1.1", "TCP", "Keep-alive, pipelining", "Default for most services"],
            ["HTTP/2", "TCP+TLS", "Multiplexing, HPACK", "APIs, web, reduces latency"],
            ["HTTP/3", "QUIC(UDP)", "0-RTT, no HOL blocking", "Low-latency, mobile"],
          ],
        },
        bullets: [
          "HTTP/2 multiplexing: multiple streams on single TCP connection — no head-of-line blocking at HTTP layer",
          "HTTP/3 QUIC: eliminates TCP HOL blocking entirely — critical for lossy networks",
          "Keep-Alive header: reuse TCP connection for multiple requests (default in HTTP/1.1)",
          "Connection pooling: maintain pool of reused connections — massive latency win",
          "HTTP methods: GET (idempotent, safe), POST (not idempotent), PUT (idempotent), PATCH, DELETE",
          "Status codes: 2xx success, 3xx redirect, 4xx client error, 5xx server error",
          "Headers: Content-Type, Authorization, Cache-Control, ETag, If-None-Match",
          "HTTPS: TLS handshake adds 1-2 RTTs — TLS 1.3 reduces to 1 RTT, 0-RTT for resumption",
        ],
        sources: [
          { label: "MDN — HTTP Reference", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP" },
          { label: "High Performance Browser Networking — Ilya Grigorik (free)", url: "https://hpbn.co" },
          { label: "HTTP/3 Explained", url: "https://http3-explained.haxx.se" },
        ],
      },
      {
        id: "ch1-protocols",
        label: "1.4 Network Protocols You Must Know",
        tone: "bullets",
        bullets: [
          "DNS: resolves domain → IP. Hierarchy: Root → TLD → Authoritative. TTL controls caching.",
          "ARP: maps IP → MAC address on local network",
          "DHCP: dynamically assigns IP addresses to hosts",
          "BGP: Border Gateway Protocol — how the internet routes between ISPs",
          "WebSockets: full-duplex TCP — Upgrade header converts HTTP → WS connection",
          "SSE (Server-Sent Events): one-way HTTP streaming, browser-native EventSource",
          "gRPC: HTTP/2 + Protocol Buffers — binary, fast, strongly typed",
          "MQTT: lightweight pub/sub for IoT devices",
          "AMQP: Advanced Message Queuing Protocol (used by RabbitMQ)",
        ],
      },
      {
        id: "ch1-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "What happens when you type google.com in a browser? Walk through every step.",
          "Explain the TCP 3-way handshake. What happens if the server doesn't respond?",
          "When would you choose UDP over TCP? Give a production example.",
          "What is the difference between HTTP/1.1, HTTP/2, and HTTP/3?",
          "How does TLS work? What is a certificate authority?",
        ],
      },
    ],
  },

  // ─── CH 02 ──────────────────────────────────────────────────────────────
  {
    num: 2,
    phaseLabel: "CH 02",
    kind: "phase",
    title: "DNS, Load Balancers & Proxies",
    subtitle:
      "How requests find their way to your servers — and how you spread them across many.",
    sections: [
      {
        id: "ch2-dns",
        label: "2.1 DNS — Domain Name System",
        tone: "bullets",
        bullets: [
          "DNS resolution order: browser cache → OS cache → /etc/hosts → recursive resolver → root → TLD → authoritative",
          "Record types: A (IPv4), AAAA (IPv6), CNAME (alias), MX (mail), TXT (verification), NS (nameservers), SRV (service discovery)",
          "TTL: time-to-live controls how long clients cache a record (low TTL = faster DNS changes, more queries)",
          "DNS load balancing: multiple A records for same domain — simplest form of distribution",
          "GeoDNS: return different IPs based on client geography — route users to nearest region",
          "DNS-based failover: Route53 health checks + failover routing policy",
          "Anycast: same IP routed to geographically nearest server — used by CDNs and DDoS mitigation",
        ],
        sources: [
          { label: "How DNS Works — Cloudflare", url: "https://www.cloudflare.com/learning/dns/what-is-dns/" },
          { label: "DNS Lookup Tool", url: "https://dnschecker.org" },
        ],
      },
      {
        id: "ch2-lb",
        label: "2.2 Load Balancers",
        tone: "table",
        table: {
          headers: ["Type", "Layer", "Sees", "Examples", "Use When"],
          rows: [
            ["L4 (Network)", "TCP/UDP", "IP + Port only", "AWS NLB, HAProxy L4", "Raw TCP, lowest latency"],
            ["L7 (Application)", "HTTP", "URL, headers, cookies", "AWS ALB, Nginx, Envoy", "HTTP routing, SSL term"],
            ["DNS LB", "DNS", "Domain only", "Route53, GeoDNS", "Cross-region routing"],
            ["Global LB", "Anycast", "Network topology", "Cloudflare, GCP GLB", "Global traffic distribution"],
          ],
        },
      },
      {
        id: "ch2-lb-algorithms",
        label: "2.2 Load Balancing Algorithms",
        heading: "Load Balancing Algorithms",
        tone: "table",
        table: {
          headers: ["Algorithm", "How It Works", "Best For", "Pitfall"],
          rows: [
            ["Round Robin", "Rotate through servers in order", "Homogeneous servers", "Ignores load"],
            ["Weighted RR", "More requests to higher-weight servers", "Mixed capacity servers", "Static weights"],
            ["Least Connections", "Route to server with fewest active conns", "Long-lived connections", "Thundering herd"],
            ["IP Hash", "Hash client IP → same server always", "Session affinity needed", "Uneven distribution"],
            ["Random", "Pick random server", "Simple, stateless services", "Hot spots possible"],
            ["Resource-Based", "Route based on CPU/memory of server", "Heterogeneous load", "Needs agent on each server"],
          ],
        },
        bullets: [
          "Health checks: LB probes /health every N seconds, removes unhealthy servers",
          "Session persistence (sticky sessions): same client always routed to same server — breaks horizontal scale",
          "SSL termination at LB: decrypt once, forward plain HTTP to backend (saves CPU on backends)",
          "Connection draining: gracefully stop sending new requests to server being taken down",
          "Active-Active vs Active-Passive LB: active-active both handle traffic; active-passive one is standby",
        ],
      },
      {
        id: "ch2-proxy",
        label: "2.3 Reverse Proxy vs Forward Proxy vs CDN",
        tone: "table",
        table: {
          headers: ["Type", "Who Uses It", "Hides", "Key Features"],
          rows: [
            ["Forward Proxy", "Client-side", "Client IP", "Corporate filter, anonymity, caching"],
            ["Reverse Proxy", "Server-side", "Server details", "SSL term, LB, caching, compression"],
            ["CDN", "Server-side", "Origin server", "Edge cache, DDoS, global delivery"],
            ["API Gateway", "Server-side", "Microservices", "Auth, rate limiting, routing, logging"],
          ],
        },
        bullets: [
          "Nginx as reverse proxy: upstream block defines backend pool; proxy_pass routes requests",
          "CDN cache hit rate: aim for >90% — cache misses go to origin (slow + expensive)",
          "CDN cache invalidation: purge by URL, by tag, or deploy with versioned filenames",
          "Edge computing: run compute (Lambda@Edge, Cloudflare Workers) at CDN PoP for lowest latency",
          "API Gateway pattern: single entry point — handles auth, rate limiting, routing, observability",
        ],
        sources: [
          { label: "Nginx Docs — Load Balancing", url: "https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/" },
          { label: "AWS ALB vs NLB Decision Guide", url: "https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/what-is-load-balancing.html" },
          { label: "Cloudflare CDN Learning", url: "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/" },
        ],
      },
      {
        id: "ch2-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design a global load balancing system for a service with users in 5 continents.",
          "What is the difference between a reverse proxy and a load balancer?",
          "How would you implement sticky sessions without breaking horizontal scalability?",
          "When would you use L4 vs L7 load balancing?",
          "How does a CDN know what to cache and for how long?",
        ],
      },
    ],
  },

  // ─── CH 03 ──────────────────────────────────────────────────────────────
  {
    num: 3,
    phaseLabel: "CH 03",
    kind: "phase",
    title: "Databases — SQL, NoSQL, NewSQL",
    subtitle:
      "Choosing, modelling, and tuning the data store — the heart of every system design.",
    miniProjectTitle: "Database Performance Lab",
    miniProjectDesc: "Build a comparative database performance benchmark:",
    miniProjectChecklist: [
      "Postgres: schema for a Twitter clone, index design, EXPLAIN ANALYZE all queries",
      "Redis: implement session store + leaderboard with ZSet",
      "Cassandra: time-series write benchmark — measure TPS vs Postgres",
      "Elasticsearch: full-text search over 100K documents, compare to Postgres LIKE",
      "Connection pool: PgBouncer setup, measure connection overhead with/without",
    ],
    sections: [
      {
        id: "ch3-sql",
        label: "3.1 Relational Databases (SQL)",
        tone: "bullets",
        bullets: [
          "ACID: Atomicity (all or nothing), Consistency (rules always hold), Isolation (concurrent txns don't interfere), Durability (committed = permanent)",
          "Indexes: B-Tree (range queries), Hash (equality), GIN/GiST (full-text, arrays), Partial (subset rows)",
          "Query planner: EXPLAIN ANALYZE shows cost estimates and actual execution — use this before optimising",
          "N+1 problem: 1 query returns N rows, then N more queries for related data — fix with JOIN or eager load",
          "Connection pooling: PgBouncer sits between app and Postgres — reuses connections (Postgres max_connections ~100-500)",
          "WAL (Write-Ahead Log): changes written to log before data pages — enables replication and point-in-time recovery",
          "Vacuuming (Postgres): reclaims space from dead rows after UPDATE/DELETE (MVCC leaves old versions)",
          "Transactions: BEGIN → operations → COMMIT (or ROLLBACK). Savepoints for nested transactions.",
          "Isolation levels: Read Uncommitted → Read Committed → Repeatable Read → Serializable (trade consistency for concurrency)",
        ],
        sources: [
          { label: "Use The Index, Luke — SQL Indexing", url: "https://use-the-index-luke.com" },
          { label: "Postgres Documentation", url: "https://www.postgresql.org/docs/" },
          { label: "PlanetScale — MySQL Vitess Sharding", url: "https://planetscale.com/docs" },
        ],
      },
      {
        id: "ch3-nosql",
        label: "3.2 NoSQL Databases",
        tone: "table",
        table: {
          headers: ["Type", "Examples", "Data Model", "Strong At", "Weak At"],
          rows: [
            ["Document", "MongoDB, Firestore", "JSON documents", "Flexible schema, nested data", "Complex joins, transactions"],
            ["Key-Value", "Redis, DynamoDB", "Key → Value", "Speed, simplicity, caching", "Complex queries"],
            ["Wide-Column", "Cassandra, HBase, Bigtable", "Row key + columns", "Time-series, write-heavy, scale", "Complex queries, joins"],
            ["Graph", "Neo4j, Amazon Neptune", "Nodes + Edges", "Relationship traversal", "Non-graph queries"],
            ["Search", "Elasticsearch, OpenSearch", "Inverted index", "Full-text, faceted search", "Primary storage, transactions"],
            ["Time-Series", "InfluxDB, TimescaleDB", "Timestamp + tags + fields", "Metrics, IoT, monitoring", "General purpose queries"],
          ],
        },
        bullets: [
          "BASE: Basically Available, Soft-state, Eventually consistent — the NoSQL trade-off to ACID",
          "CAP theorem: in network partition, choose Consistency OR Availability (can't have both)",
          "MongoDB: flexible schema great for prototyping, but schema validation still important in production",
          "Cassandra: masterless ring, write anywhere — optimise partition key design for your query patterns",
          "Redis: in-memory, sub-ms latency. Data structures: String, Hash, List, Set, ZSet, Stream, HyperLogLog.",
        ],
      },
      {
        id: "ch3-selection",
        label: "3.3 Database Selection Framework",
        tone: "table",
        table: {
          headers: ["Requirement", "Choose"],
          rows: [
            ["Complex queries, transactions, relations", "PostgreSQL"],
            ["High write throughput, time-series", "Cassandra or InfluxDB"],
            ["Sub-millisecond reads, caching, session store", "Redis"],
            ["Flexible schema, JSON documents", "MongoDB or Firestore"],
            ["Full-text search, analytics", "Elasticsearch"],
            ["Graph traversal, recommendations", "Neo4j"],
            ["Global scale, multi-region writes", "DynamoDB or Spanner"],
            ["Analytical queries, data warehouse", "BigQuery, Snowflake, Redshift"],
            ["Vector similarity search", "Qdrant, pgvector, Pinecone"],
          ],
        },
      },
      {
        id: "ch3-sql-perf",
        label: "3.4 SQL Performance — What Interviewers Test",
        tone: "bullets",
        bullets: [
          "Index strategy: index columns used in WHERE, JOIN ON, ORDER BY, GROUP BY",
          "Composite indexes: order matters — (user_id, created_at) serves user_id=X and user_id=X AND created_at>Y queries",
          "Covering index: index contains all columns needed by query — zero table access needed",
          "Partial index: CREATE INDEX ON orders(user_id) WHERE status='pending' — smaller, faster",
          "Index bloat: too many indexes slow writes (every write updates all indexes)",
          "Query optimisation: SELECT only needed columns, avoid SELECT *, use LIMIT, avoid functions on indexed columns",
          "Slow query log: enable in Postgres/MySQL, investigate queries >100ms",
          "Read replicas: route SELECT queries to replicas, writes to primary",
        ],
      },
      {
        id: "ch3-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design the database schema for Twitter/X. What indexes would you create?",
          "When would you choose MongoDB over PostgreSQL?",
          "Explain ACID. Can you have a distributed ACID transaction?",
          "What is the N+1 problem? How do you detect and fix it?",
          "When does an index make a query slower?",
          "Design a schema that handles multi-tenancy for a SaaS product.",
        ],
      },
    ],
  },

  // ─── CH 04 ──────────────────────────────────────────────────────────────
  {
    num: 4,
    phaseLabel: "CH 04",
    kind: "phase",
    title: "Caching — Every Layer",
    subtitle:
      "Where to cache, how to keep it fresh, and the failure modes that bring systems down.",
    sections: [
      {
        id: "ch4-hierarchy",
        label: "4.1 Cache Hierarchy",
        tone: "table",
        table: {
          headers: ["Layer", "Location", "Latency", "Size", "Examples"],
          rows: [
            ["CPU L1/L2/L3", "On-chip", "0.5–10ns", "KB–MB", "Hardware"],
            ["RAM", "Same machine", "50–100ns", "GB", "In-process cache"],
            ["Local disk", "Same machine", "100µs", "TB", "SSD page cache"],
            ["In-process", "App memory", "~100ns", "100MB", "Guava, Caffeine, lru-dict"],
            ["Distributed", "Cache cluster", "0.5–2ms", "100GB+", "Redis, Memcached"],
            ["CDN edge", "PoP near user", "5–50ms", "Petabytes", "Cloudflare, Fastly"],
            ["Browser", "User device", "~0ms", "MB", "Cache-Control headers"],
          ],
        },
      },
      {
        id: "ch4-strategies",
        label: "4.2 Cache Strategies",
        tone: "table",
        table: {
          headers: ["Strategy", "How It Works", "Best For", "Stale Risk"],
          rows: [
            ["Cache-Aside", "App checks cache, miss→DB, fill cache", "General read-heavy", "Medium"],
            ["Write-Through", "Write to cache AND DB synchronously", "Strong consistency needed", "Low"],
            ["Write-Behind", "Write to cache, async flush to DB", "Write-heavy, burst writes", "High"],
            ["Read-Through", "Cache fetches from DB on miss", "Transparent caching", "Medium"],
            ["Refresh-Ahead", "Pre-fetch before TTL expires", "Predictable access patterns", "Low"],
          ],
        },
      },
      {
        id: "ch4-eviction",
        label: "4.3 Cache Eviction Policies",
        tone: "bullets",
        bullets: [
          "LRU (Least Recently Used): evict the item not accessed for the longest time — Redis default",
          "LFU (Least Frequently Used): evict item accessed fewest times — better for skewed access patterns",
          "FIFO: evict oldest inserted item — simple but ignores access frequency",
          "TTL-based: items expire after fixed time — simplest, works for time-sensitive data",
          "ARC (Adaptive Replacement Cache): balances recency + frequency automatically",
          "Redis maxmemory-policy: noeviction, allkeys-lru, volatile-lru, allkeys-lfu, volatile-ttl",
        ],
      },
      {
        id: "ch4-problems",
        label: "4.4 Cache Problems & Solutions",
        tone: "table",
        table: {
          headers: ["Problem", "What It Is", "Solution"],
          rows: [
            ["Cache Stampede", "Many requests miss simultaneously, hammer DB", "Mutex lock, probabilistic early expiry, background refresh"],
            ["Cache Avalanche", "Many keys expire at same time → DB flood", "Stagger TTLs with jitter, pre-warm cache"],
            ["Cache Penetration", "Query for non-existent key bypasses cache", "Bloom filter to check existence, cache null results"],
            ["Hot Key", "Single key gets millions of req/sec", "Local in-process cache, key sharding, read replicas"],
            ["Cold Start", "Empty cache on deploy → all DB hits", "Cache warming script before traffic switch"],
          ],
        },
        bullets: [
          "Redis data structures: String (basic), Hash (object), List (queue), Set (unique), ZSet (leaderboard), Stream (event log)",
          "Redis persistence: RDB (snapshot, compact) vs AOF (every write, durable) vs hybrid",
          "Redis Cluster: hash slot partitioning across nodes, 3 primaries + 3 replicas minimum",
          "Memcached vs Redis: Memcached is simpler, multi-threaded; Redis has rich data types, persistence",
          "Cache-Control headers: max-age, no-store, no-cache, must-revalidate, s-maxage (CDN-specific)",
          "ETag: server sends hash of content; client sends If-None-Match; server returns 304 if unchanged",
        ],
        sources: [
          { label: "Redis Documentation", url: "https://redis.io/docs/" },
          { label: "Redis University (free courses)", url: "https://university.redis.com" },
          { label: "Caching Best Practices — AWS", url: "https://aws.amazon.com/caching/best-practices/" },
        ],
      },
      {
        id: "ch4-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design a caching layer for a news feed with 10M users.",
          "What is cache stampede and how do you prevent it?",
          "When would write-through be better than cache-aside?",
          "How do you handle cache invalidation across microservices?",
          "Design a rate limiter using Redis. What data structure would you use?",
        ],
      },
    ],
  },

  // ─── CH 05 ──────────────────────────────────────────────────────────────
  {
    num: 5,
    phaseLabel: "CH 05",
    kind: "phase",
    title: "Message Queues & Event Streaming",
    subtitle:
      "Decoupling services with asynchronous messaging, and the delivery guarantees behind them.",
    sections: [
      {
        id: "ch5-why",
        label: "5.1 Why Message Queues?",
        tone: "bullets",
        bullets: [
          "Decoupling: producer doesn't wait for consumer — systems independent",
          "Load levelling: smooth out traffic spikes — queue absorbs burst, consumer drains steadily",
          "Durability: messages persisted — consumer can process after temporary failure",
          "Fan-out: one message → multiple consumers (email + analytics + notification)",
          "Backpressure: queue depth signals when consumers can't keep up",
          "Async processing: send email, resize image, run ML inference — all without blocking user request",
        ],
      },
      {
        id: "ch5-queue-stream",
        label: "5.2 Queue vs Stream",
        tone: "table",
        table: {
          headers: ["Property", "Message Queue (RabbitMQ)", "Event Stream (Kafka)"],
          rows: [
            ["Model", "Push to consumers, delete on ack", "Append-only log, consumers pull"],
            ["Retention", "Deleted after consumption", "Retained for days/forever"],
            ["Consumers", "Each message consumed once", "Each consumer group gets all messages"],
            ["Ordering", "Per-queue (limited)", "Guaranteed within partition"],
            ["Replay", "Not possible after ack", "Rewind to any offset"],
            ["Throughput", "Moderate (thousands/sec)", "Massive (millions/sec)"],
            ["Use case", "Task queues, RPC, routing", "Event sourcing, audit log, analytics"],
          ],
        },
      },
      {
        id: "ch5-kafka",
        label: "5.3 Apache Kafka Deep Dive",
        tone: "bullets",
        bullets: [
          "Topic: logical stream of events. Partition: ordered, immutable log segment.",
          "Offset: position within a partition — consumers track their own offset",
          "Consumer group: N consumers share partition load — each partition to one consumer",
          "Producers: choose partition by key hash (same key → same partition = ordering guarantee)",
          "Brokers: Kafka cluster nodes. Replication factor: how many copies of each partition.",
          "Leader election: one broker leads each partition, others are followers (ISR)",
          "Retention: delete after 7 days OR compact (keep latest value per key)",
          "Exactly-once semantics: idempotent producers + transactional consumers",
          "Schema Registry: enforce Avro/Protobuf schema evolution across producer/consumer",
          "Kafka Streams / ksqlDB: stream processing built on top of Kafka",
        ],
        sources: [
          { label: "Kafka Documentation", url: "https://kafka.apache.org/documentation/" },
          { label: "Confluent Kafka Courses (free)", url: "https://developer.confluent.io/courses/" },
          { label: "RabbitMQ Tutorials", url: "https://www.rabbitmq.com/tutorials/" },
          { label: "AWS SQS Documentation", url: "https://docs.aws.amazon.com/sqs/" },
        ],
      },
      {
        id: "ch5-delivery",
        label: "5.4 Delivery Guarantees",
        tone: "table",
        table: {
          headers: ["Guarantee", "Meaning", "Risk", "How to Achieve"],
          rows: [
            ["At-most-once", "May lose messages, no duplicates", "Data loss", "Fire and forget, no ack"],
            ["At-least-once", "No loss, may duplicate", "Duplicate processing", "Ack after processing"],
            ["Exactly-once", "No loss, no duplicates", "Highest complexity", "Idempotent consumers + transactions"],
          ],
        },
        bullets: [
          "Idempotency key: include unique ID with message, consumer deduplicates by ID",
          "Dead Letter Queue (DLQ): messages that fail N times go here for investigation",
          "Poison pill: message that always causes consumer crash — DLQ saves the day",
          "Backoff retry: exponential backoff on consumer failure prevents hammering",
        ],
      },
      {
        id: "ch5-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design a notification system for 100M users using message queues.",
          "How does Kafka guarantee ordering? When can ordering be violated?",
          "What is the difference between at-least-once and exactly-once delivery?",
          "When would you use RabbitMQ vs Kafka vs SQS?",
          "Design an event-driven order processing pipeline using Kafka.",
        ],
      },
    ],
  },

  // ─── CH 06 ──────────────────────────────────────────────────────────────
  {
    num: 6,
    phaseLabel: "CH 06",
    kind: "phase",
    title: "Distributed Systems — Core Theory",
    subtitle:
      "CAP, consensus, clocks and failure models — the theory that underpins every large system.",
    sections: [
      {
        id: "ch6-cap",
        label: "6.1 CAP Theorem",
        tone: "bullets",
        bullets: [
          "Consistency: every read receives the most recent write (or an error)",
          "Availability: every request receives a response (no guarantee it's the latest write)",
          "Partition Tolerance: system continues despite network partition — NOT optional in real distributed systems",
          "CAP trade-off: during a partition, choose CP (sacrifice availability) or AP (sacrifice consistency)",
          "CP systems: ZooKeeper, HBase, Spanner — prefer to return error than stale data",
          "AP systems: Cassandra, CouchDB, DynamoDB — prefer stale data over no response",
          "PACELC extension: even without partition, trade off Latency vs Consistency",
        ],
      },
      {
        id: "ch6-consistency",
        label: "6.2 Consistency Models",
        tone: "table",
        table: {
          headers: ["Model", "Guarantee", "Example"],
          rows: [
            ["Strong/Linear.", "Every read sees latest write", "Single-node DB, Spanner"],
            ["Sequential", "All nodes see ops in same order", "Zookeeper"],
            ["Causal", "Causally related ops in order", "Dynamo, some MongoDB"],
            ["Eventual", "All nodes converge eventually", "Cassandra, DynamoDB"],
            ["Read-your-writes", "You always see your own writes", "Most user-facing apps need this"],
            ["Monotonic reads", "Never see older data after newer", "Pagination, timelines"],
          ],
        },
      },
      {
        id: "ch6-consensus",
        label: "6.3 Consensus Algorithms",
        tone: "bullets",
        bullets: [
          "Raft: leader election + log replication. Leader sends entries, majority ack = committed.",
          "Paxos: original consensus algorithm — mathematically elegant, hard to implement correctly",
          "Two-Phase Commit (2PC): coordinator asks all nodes to PREPARE, then COMMIT — blocks if coordinator fails",
          "Three-Phase Commit (3PC): adds pre-commit phase to handle coordinator failure — still not partition-tolerant",
          "Multi-Paxos / Multi-Raft: Raft used by etcd, CockroachDB, TiKV",
          "Leader election: Bully algorithm (highest ID wins), Ring algorithm (pass token around ring)",
          "Quorum: majority of nodes (N/2 + 1) must agree — balance consistency vs availability",
        ],
        sources: [
          { label: "Raft Consensus Visualisation", url: "https://raft.github.io" },
          { label: "Designing Data-Intensive Applications — Kleppmann (must-read)", url: "https://dataintensive.net" },
          { label: "The Paper Trail — Distributed Systems Blog", url: "https://www.the-paper-trail.org" },
          { label: "MIT 6.824 Distributed Systems (free lectures)", url: "https://pdos.csail.mit.edu/6.824/" },
          { label: "Martin Kleppmann's Blog", url: "https://martin.kleppmann.com" },
        ],
      },
      {
        id: "ch6-clocks",
        label: "6.4 Clocks & Time in Distributed Systems",
        tone: "bullets",
        bullets: [
          "Problem: no global clock — different machines have different clocks (clock skew)",
          "NTP: synchronises clocks but has uncertainty of ~100ms — not enough for ordering",
          "Logical clocks (Lamport): monotonic counter incremented on send/receive — tracks causality",
          "Vector clocks: per-node counters — detect concurrent vs causally related events",
          "Hybrid Logical Clocks (HLC): combines physical time + logical — used by CockroachDB",
          "TrueTime (Spanner): GPS + atomic clocks with bounded uncertainty — enables external consistency",
          "Event ordering: without global clock, use Lamport timestamps or vector clocks for ordering",
        ],
      },
      {
        id: "ch6-failure",
        label: "6.5 Failure Models",
        tone: "bullets",
        bullets: [
          "Crash-stop: node fails by stopping, never sends wrong data — simplest to handle",
          "Crash-recovery: node may restart, might replay old state — need idempotency",
          "Byzantine fault: node sends incorrect/malicious data — needs BFT algorithms (blockchain)",
          "Network partition: nodes can't communicate but both still running — most common in practice",
          "Gray failure: node partially works (slow responses, intermittent drops) — hardest to detect",
          "Cascading failure: one failure overloads others → chain reaction. Prevent with bulkheads + circuit breakers.",
        ],
      },
      {
        id: "ch6-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Explain the CAP theorem. Which properties does Cassandra sacrifice?",
          "What is split-brain and how do you prevent it?",
          "How does Raft achieve consensus? Walk through a leader election.",
          "What is the difference between a network partition and a node failure?",
          "How would you implement a distributed lock?",
        ],
      },
    ],
  },

  // ─── CH 07 ──────────────────────────────────────────────────────────────
  {
    num: 7,
    phaseLabel: "CH 07",
    kind: "phase",
    title: "Replication, Partitioning & Consistency",
    subtitle:
      "How data is copied, split across nodes, and kept correct when writes conflict.",
    sections: [
      {
        id: "ch7-replication",
        label: "7.1 Database Replication",
        tone: "table",
        table: {
          headers: ["Type", "How It Works", "Pros", "Cons"],
          rows: [
            ["Single-Leader", "All writes to leader, replicate", "Simple, consistent", "Leader bottleneck, failover complexity"],
            ["Multi-Leader", "Write to any leader, sync", "Multi-region writes", "Conflict resolution needed"],
            ["Leaderless", "Write to W nodes, read from R", "High availability", "Complex quorum math"],
          ],
        },
        bullets: [
          "Synchronous replication: leader waits for replica ACK before confirming write — durable but slow",
          "Asynchronous replication: leader confirms immediately, replicates in background — fast but can lose writes on leader crash",
          "Replication lag: replica is behind leader by N ms/s. Read-your-writes requires reading from leader or waiting for lag.",
          "Quorum reads/writes: W + R > N guarantees you'll read latest write. e.g. N=3, W=2, R=2",
          "Read replicas: add read capacity horizontally. All writes still go to primary.",
          "Failover: automatic (VIP, Patroni) or manual. Watch out for split-brain during failover.",
        ],
      },
      {
        id: "ch7-partitioning",
        label: "7.2 Partitioning / Sharding",
        tone: "table",
        table: {
          headers: ["Strategy", "How", "Pros", "Cons"],
          rows: [
            ["Range-based", "Shard by key range (A-M, N-Z)", "Simple, range queries easy", "Hot spots if keys skewed"],
            ["Hash-based", "Hash(key) mod N = shard", "Even distribution", "Range queries across all shards"],
            ["Consistent Hashing", "Hash ring, minimal reshuffling", "Easy node add/remove", "Slightly complex"],
            ["Directory-based", "Lookup table: key → shard", "Flexible routing", "Lookup table bottleneck"],
            ["Geo-based", "Shard by user geography", "Data residency, latency", "Uneven if geo traffic skewed"],
          ],
        },
        bullets: [
          "Hot spot: one shard gets disproportionate traffic (celebrity user, popular product). Fix: sub-shard, salting, caching.",
          "Cross-shard queries: expensive — JOIN across shards requires scatter-gather. Design schema to avoid.",
          "Shard key selection: highest-cardinality column that matches your most common query pattern",
          "Resharding: adding new shards requires redistributing data — major operational pain. Plan capacity early.",
          "Consistent hashing: used by Cassandra, DynamoDB, Memcached. Virtual nodes smooth distribution.",
        ],
      },
      {
        id: "ch7-conflict",
        label: "7.3 Conflict Resolution",
        tone: "bullets",
        bullets: [
          "Last Write Wins (LWW): timestamp determines winner — simple but can lose writes",
          "Version vectors: track causality, detect true concurrent writes vs sequential",
          "CRDTs (Conflict-free Replicated Data Types): data structures that merge automatically (counters, sets, maps)",
          "Application-level merge: expose conflict to application or user to resolve",
          "Operational Transformation: Google Docs approach — transform operations for concurrent edits",
        ],
        sources: [
          { label: "DDIA Book — Replication Chapter", url: "https://dataintensive.net" },
          { label: "Consistent Hashing Explained", url: "https://www.toptal.com/big-data/consistent-hashing" },
          { label: "Vitess — MySQL Sharding", url: "https://vitess.io/docs/" },
        ],
      },
      {
        id: "ch7-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design a sharding strategy for a user database that will grow to 10B rows.",
          "What is consistent hashing? Why is it better than modulo sharding?",
          "Explain replication lag. How does it affect read-your-writes consistency?",
          "What is a hot shard and how do you fix it for a celebrity user scenario?",
        ],
      },
    ],
  },

  // ─── CH 08 ──────────────────────────────────────────────────────────────
  {
    num: 8,
    phaseLabel: "CH 08",
    kind: "phase",
    title: "Storage Systems",
    subtitle:
      "Block, file, and object storage — and the disk-level internals that drive database design.",
    sections: [
      {
        id: "ch8-types",
        label: "8.1 Storage Types",
        tone: "table",
        table: {
          headers: ["Type", "Access Pattern", "Examples", "Use For"],
          rows: [
            ["Block", "Fixed-size blocks", "AWS EBS, iSCSI, SAN", "Databases, OS volumes, VMs"],
            ["File", "Hierarchical path", "NFS, EFS, Ceph FS", "Shared files, home dirs, legacy"],
            ["Object", "Key → blob via API", "S3, GCS, MinIO", "Images, videos, backups, static assets"],
            ["In-memory", "Direct RAM access", "Redis, Memcached", "Cache, session, hot data"],
            ["Archive", "Rare retrieval", "S3 Glacier, Tape", "Compliance, cold backup"],
          ],
        },
      },
      {
        id: "ch8-object",
        label: "8.2 Object Storage (S3)",
        tone: "bullets",
        bullets: [
          "Bucket + Key design: prefix-based pseudo-directories (e.g. users/{id}/avatar.jpg)",
          "Multipart upload: for files >100MB — parallel upload in parts, atomic completion",
          "Pre-signed URLs: grant time-limited access to private objects without API keys",
          "S3 storage classes: Standard → IA → Glacier Instant → Glacier Flexible → Deep Archive (cost/access trade-off)",
          "Versioning: keep old versions of objects — protects against accidental delete",
          "Event notifications: S3 → SQS/Lambda → trigger processing pipeline on upload",
          "Lifecycle policies: auto-transition objects between storage classes by age",
          "Strong consistency: S3 provides strong read-after-write consistency (since 2020)",
        ],
      },
      {
        id: "ch8-internals",
        label: "8.3 RAID, SSDs, and Storage Internals",
        tone: "bullets",
        bullets: [
          "RAID 0: stripe across disks (speed, no redundancy). RAID 1: mirror (redundancy). RAID 5: stripe + parity (balance).",
          "SSD vs HDD: SSD random read ~100µs, HDD ~10ms. SSD write amplification and wear levelling.",
          "NVMe: PCIe-attached SSD — 3-5 GBps vs SATA SSD 600 MBps",
          "B-Tree: used by most SQL databases — balanced tree, O(log n) reads, good for range queries",
          "LSM-Tree: used by Cassandra, RocksDB, LevelDB — fast sequential writes, compaction for reads",
          "Write amplification: ratio of bytes written to disk vs bytes written by application — SSD killer",
        ],
        sources: [
          { label: "AWS S3 Documentation", url: "https://docs.aws.amazon.com/s3/" },
          { label: "Ceph — Distributed Storage", url: "https://docs.ceph.com/en/latest/" },
          { label: "The Internals of PostgreSQL — Storage", url: "https://www.interdb.jp/pg/pgsql01.html" },
        ],
      },
      {
        id: "ch8-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design a file storage system like Dropbox.",
          "When would you use object storage vs block storage vs file storage?",
          "How does S3 achieve durability? What is the 11 9s claim based on?",
          "Explain LSM-Tree vs B-Tree. Why does Cassandra use LSM?",
        ],
      },
    ],
  },

  // ─── CH 09 ──────────────────────────────────────────────────────────────
  {
    num: 9,
    phaseLabel: "CH 09",
    kind: "phase",
    title: "API Design — REST, GraphQL, gRPC, WebSockets",
    subtitle:
      "Picking the right API paradigm and designing endpoints that scale and evolve.",
    sections: [
      {
        id: "ch9-paradigms",
        label: "9.0 API Paradigms",
        heading: "Choosing a Paradigm",
        tone: "table",
        table: {
          headers: ["Paradigm", "Protocol", "Data Format", "Best For", "Weakness"],
          rows: [
            ["REST", "HTTP/1.1-3", "JSON (usually)", "CRUD, public APIs, simple", "Over/under-fetching"],
            ["GraphQL", "HTTP", "JSON", "Flexible queries, BFF layer", "N+1 queries, complexity"],
            ["gRPC", "HTTP/2", "Protocol Buffers", "Microservice-to-service", "Browser support limited"],
            ["WebSockets", "TCP (WS)", "Any binary/text", "Real-time, bidirectional", "Stateful, hard to scale"],
            ["SSE", "HTTP", "Text", "Server-push, one-directional", "Client-only initiation"],
            ["tRPC", "HTTP", "JSON", "TypeScript monorepo", "TS only ecosystem"],
          ],
        },
      },
      {
        id: "ch9-rest",
        label: "9.1 REST Best Practices",
        tone: "bullets",
        bullets: [
          "Resource naming: nouns not verbs. /users/{id}/orders not /getUserOrders",
          "HTTP method semantics: GET (safe+idempotent), PUT (idempotent), POST (neither), DELETE (idempotent)",
          "Status codes: 200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized, 403 Forbidden, 404, 409 Conflict, 422 Unprocessable, 429 Rate Limited, 500, 503",
          "Versioning: /v1/users (URL path — most common), Accept: application/vnd.api+json;version=2 (header)",
          "Pagination: cursor-based (opaque next_cursor) > offset-based (page=3&limit=20) for large datasets",
          "HATEOAS: links in response tell client what to do next — rarely fully implemented in practice",
          "Idempotency keys: POST /payments with Idempotency-Key header — safe to retry",
          "OpenAPI / Swagger: document your API — generate SDKs and mocks from spec",
        ],
      },
      {
        id: "ch9-grpc",
        label: "9.2 gRPC Deep Dive",
        tone: "bullets",
        bullets: [
          "Protocol Buffers: binary serialisation — 3-10x smaller than JSON, faster to parse",
          "Service definition in .proto file: defines services, methods, request/response messages",
          "Streaming modes: unary, server-streaming, client-streaming, bidirectional streaming",
          "Code generation: protoc generates client/server stubs in any language",
          "Interceptors: middleware for auth, logging, metrics (equivalent to HTTP middleware)",
          "gRPC-Web: browser-compatible gRPC via HTTP/1.1 wrapper (Envoy proxy required)",
          "Deadlines/timeouts: every gRPC call should have a deadline — propagated through call chain",
        ],
        sources: [
          { label: "REST API Design Best Practices", url: "https://restfulapi.net" },
          { label: "gRPC Documentation", url: "https://grpc.io/docs/" },
          { label: "GraphQL Official Docs", url: "https://graphql.org/learn/" },
          { label: "API Design Patterns (book)", url: "https://www.manning.com/books/api-design-patterns" },
          { label: "Stripe API Design Blog", url: "https://stripe.com/blog/payment-api-design" },
        ],
      },
      {
        id: "ch9-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design the API for a ride-sharing app like Uber. What would the core endpoints be?",
          "When would you use gRPC over REST?",
          "What is the N+1 problem in GraphQL? How does DataLoader fix it?",
          "How do you version an API without breaking existing clients?",
          "Design an API for real-time collaborative document editing.",
        ],
      },
    ],
  },

  // ─── CH 10 ──────────────────────────────────────────────────────────────
  {
    num: 10,
    phaseLabel: "CH 10",
    kind: "phase",
    title: "Search Systems",
    subtitle:
      "Inverted indexes, relevance scoring, and the architecture behind full-text search.",
    sections: [
      {
        id: "ch10-fulltext",
        label: "10.1 How Full-Text Search Works",
        tone: "bullets",
        bullets: [
          "Inverted index: maps term → list of documents containing term (with positions + frequencies)",
          "Text analysis pipeline: tokenise → lowercase → remove stopwords → stem/lemmatise → index",
          "TF-IDF: term frequency × inverse document frequency — classic relevance scoring",
          "BM25: improved TF-IDF with document length normalisation — Elasticsearch/Lucene default",
          "Query types: match (full-text), term (exact), range, fuzzy (edit distance), phrase, bool (must/should/must_not)",
          "Relevance tuning: field boosting (title^3 body^1), function score, freshness boost",
          "Analyzer: standard, language-specific (english, german), custom (ICU for CJK languages)",
        ],
      },
      {
        id: "ch10-elasticsearch",
        label: "10.2 Elasticsearch Architecture",
        tone: "bullets",
        bullets: [
          "Index: logical collection of documents. Shard: distributed unit of an index.",
          "Primary shard: handles writes. Replica shard: serves reads, failover.",
          "Document: JSON stored with metadata (_id, _source, _score)",
          "Mapping: field types (text, keyword, date, integer, geo_point, dense_vector)",
          "text vs keyword: text is analysed (for search), keyword is exact (for aggregations, sorting)",
          "Aggregations: terms, histogram, date_histogram, stats — like SQL GROUP BY",
          "Index lifecycle management (ILM): hot → warm → cold → delete based on age",
          "Near-real-time (NRT): new documents visible for search within ~1 second",
        ],
        sources: [
          { label: "Elasticsearch Guide", url: "https://www.elastic.co/guide/en/elasticsearch/reference/current/" },
          { label: "Elasticsearch: The Definitive Guide (free)", url: "https://www.elastic.co/guide/en/elasticsearch/guide/current/" },
          { label: "Algolia — Search Best Practices", url: "https://www.algolia.com/blog/" },
        ],
      },
      {
        id: "ch10-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design a search system for an e-commerce site with 100M products.",
          "What is the difference between text and keyword field types in Elasticsearch?",
          "How would you implement autocomplete/typeahead for a search box?",
          "Design a system to handle typo-tolerant search.",
        ],
      },
    ],
  },

  // ─── CH 11 ──────────────────────────────────────────────────────────────
  {
    num: 11,
    phaseLabel: "CH 11",
    kind: "phase",
    title: "Rate Limiting, Auth & Security",
    subtitle:
      "Protecting your APIs: throttling abusive traffic, authenticating users, authorising actions.",
    sections: [
      {
        id: "ch11-rate-limiting",
        label: "11.1 Rate Limiting Algorithms",
        tone: "table",
        table: {
          headers: ["Algorithm", "How It Works", "Pros", "Cons"],
          rows: [
            ["Fixed Window", "Count in fixed time window", "Simple", "Burst at window edge"],
            ["Sliding Window Log", "Log each request timestamp", "Accurate", "Memory: O(requests)"],
            ["Sliding Window Counter", "Weighted count across 2 windows", "Low memory, accurate", "Slightly approximate"],
            ["Token Bucket", "Tokens refill at rate R, burst up to B", "Handles bursts", "Complex implementation"],
            ["Leaky Bucket", "Queue drains at fixed rate", "Smooth output", "Delay under burst"],
          ],
        },
        bullets: [
          "Token bucket in Redis: INCR + EXPIRE per key, or use Redis Cell module",
          "Rate limit dimensions: per-user, per-IP, per-API-key, per-endpoint, global",
          "Response headers: X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, Retry-After",
          "Distributed rate limiting: Redis INCR atomic operations work across multiple app instances",
          "Tiered limits: free tier 100/day, paid tier 10,000/day, enterprise unlimited",
        ],
      },
      {
        id: "ch11-auth",
        label: "11.2 Authentication & Authorization",
        tone: "bullets",
        bullets: [
          "JWT (JSON Web Token): header.payload.signature — stateless auth. Store in HttpOnly cookie, not localStorage.",
          "JWT claims: sub (subject/user_id), iat (issued at), exp (expiry), iss (issuer), aud (audience)",
          "JWT signature: HMAC-SHA256 (symmetric) or RS256 (asymmetric — public key verifiable)",
          "Access token vs Refresh token: access token short-lived (15min), refresh token long-lived (30 days)",
          "OAuth 2.0 flows: Authorization Code (web apps), PKCE (SPAs/mobile), Client Credentials (server-to-server)",
          "OIDC (OpenID Connect): OAuth 2.0 extension for authentication — adds ID token",
          "API Key: simple, for server-to-server. Hash before storing in DB. Add rate limits per key.",
          "Session-based auth: server stores session in Redis, client has session cookie (HttpOnly, Secure, SameSite)",
          "RBAC: Role-Based Access Control — user has roles, roles have permissions",
          "ABAC: Attribute-Based Access Control — policies on attributes (user.department == resource.department)",
          "mTLS: mutual TLS — both client and server authenticate with certificates (service mesh)",
        ],
        sources: [
          { label: "OAuth 2.0 — oauth.net", url: "https://oauth.net/2/" },
          { label: "JWT.io — Debugger and Docs", url: "https://jwt.io" },
          { label: "OWASP Authentication Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html" },
          { label: "Auth0 Docs — IAM Concepts", url: "https://auth0.com/docs" },
        ],
      },
      {
        id: "ch11-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "Design a rate limiter for an API with 10,000 users making 1M requests/day.",
          "What are the security risks of storing JWT in localStorage?",
          "Explain OAuth 2.0 Authorization Code flow step by step.",
          "Design a permissions system for a multi-tenant SaaS application.",
          "How would you implement API key rotation without downtime?",
        ],
      },
    ],
  },

  // ─── CH 12 ──────────────────────────────────────────────────────────────
  {
    num: 12,
    phaseLabel: "CH 12",
    kind: "phase",
    title: "Observability — Metrics, Logs, Traces",
    subtitle:
      "Knowing what your system is doing in production: the three pillars of observability.",
    sections: [
      {
        id: "ch12-pillars",
        label: "12.0 The Three Pillars",
        heading: "The Three Pillars",
        tone: "table",
        table: {
          headers: ["Pillar", "What It Is", "Tools", "Answers"],
          rows: [
            ["Metrics", "Numeric measurements over time", "Prometheus, Datadog, CloudWatch", "Is the system healthy right now?"],
            ["Logs", "Timestamped event records", "ELK, Loki, Splunk", "What happened and when?"],
            ["Traces", "Request flow across services", "Jaeger, Zipkin, Tempo, OTEL", "Where is the latency coming from?"],
          ],
        },
      },
      {
        id: "ch12-metrics",
        label: "12.1 Metrics",
        tone: "bullets",
        bullets: [
          "The Four Golden Signals: Latency, Traffic, Errors, Saturation (Google SRE Book)",
          "RED method: Rate, Errors, Duration — for services",
          "USE method: Utilisation, Saturation, Errors — for resources (CPU, disk)",
          "Histogram: track distribution of values (latency p50, p95, p99) — more useful than averages",
          "Counter: monotonically increasing (requests total, errors total)",
          "Gauge: current value (active connections, memory usage, queue depth)",
          "Prometheus: pull-based metrics. Metric endpoints scraped every 15s. PromQL for queries.",
          "Alerting: page on p99 latency > SLO, error rate > threshold, not average latency",
        ],
      },
      {
        id: "ch12-logging",
        label: "12.2 Logging",
        tone: "bullets",
        bullets: [
          "Structured logging: JSON logs with consistent fields — makes search and parsing easy",
          "Required fields: timestamp, level, service, trace_id, user_id, message, duration_ms",
          "Log levels: DEBUG (dev only), INFO (normal ops), WARN (degraded), ERROR (broken), FATAL",
          "Correlation ID / Trace ID: single ID passed through all services — find all logs for one request",
          "Log sampling: log 100% of errors, sample 1% of successful requests at INFO",
          "ELK Stack: Elasticsearch (store) + Logstash (process) + Kibana (visualise)",
          "Loki: Prometheus-compatible log aggregation — queries by label not full-text index",
          "Log retention: PII considerations, cost, compliance (GDPR, SOC2) — typically 30-90 days",
        ],
      },
      {
        id: "ch12-tracing",
        label: "12.3 Distributed Tracing",
        tone: "bullets",
        bullets: [
          "Span: a single operation with start/end time and metadata",
          "Trace: tree of spans representing a full request journey across services",
          "Context propagation: trace-id passed via HTTP headers (W3C traceparent, X-B3-TraceId)",
          "Sampling: head-based (decide at entry) vs tail-based (decide after seeing full trace)",
          "OpenTelemetry: vendor-neutral instrumentation standard — one SDK, many backends",
          "Service map: visualise dependencies discovered from trace data",
        ],
        sources: [
          { label: "Google SRE Book (free online)", url: "https://sre.google/sre-book/table-of-contents/" },
          { label: "Prometheus Docs", url: "https://prometheus.io/docs/" },
          { label: "OpenTelemetry Docs", url: "https://opentelemetry.io/docs/" },
          { label: "Grafana + Loki + Tempo Stack", url: "https://grafana.com/docs/" },
        ],
      },
      {
        id: "ch12-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "What are the Four Golden Signals? How would you alert on them?",
          "How does distributed tracing work? What is a span vs a trace?",
          "Design an observability stack for a microservices application.",
          "What is the difference between monitoring and observability?",
        ],
      },
    ],
  },

  // ─── CH 13 ──────────────────────────────────────────────────────────────
  {
    num: 13,
    phaseLabel: "CH 13",
    kind: "phase",
    title: "Scalability Patterns & Reliability Engineering",
    subtitle:
      "Patterns for scaling out and staying up: from horizontal scaling to error budgets.",
    sections: [
      {
        id: "ch13-scalability",
        label: "13.1 Scalability Patterns",
        tone: "table",
        table: {
          headers: ["Pattern", "What It Does", "Trade-off"],
          rows: [
            ["Horizontal scaling", "Add more servers (scale out)", "Needs stateless design"],
            ["Vertical scaling", "Bigger server (scale up)", "Hard ceiling, single point of failure"],
            ["Read replicas", "Scale read traffic separately", "Replication lag"],
            ["CQRS", "Separate read/write models", "Complexity, eventual consistency"],
            ["Event sourcing", "Store events, derive state", "Complex queries, storage growth"],
            ["Microservices", "Independent deployable services", "Network calls, operational overhead"],
            ["Data denormalisation", "Duplicate data to avoid JOINs", "Write complexity, consistency"],
            ["Async processing", "Offload work to queue + worker", "Eventual result, complexity"],
          ],
        },
      },
      {
        id: "ch13-reliability",
        label: "13.2 Reliability Patterns",
        tone: "bullets",
        bullets: [
          "Circuit Breaker: if N% of requests fail, open circuit — stop calling failing service. Half-open after timeout.",
          "Retry with backoff: retry failed requests with exponential backoff + jitter",
          "Bulkhead: isolate failure domains — separate thread pools per service (like ship compartments)",
          "Timeout: every network call needs a timeout — never wait forever",
          "Fallback: return cached result, default response, or degraded functionality on failure",
          "Idempotency: safe to retry any operation — critical for payments, emails, state mutations",
          "Health checks: /health endpoint returns 200 (ready to serve) or 503 (degraded)",
          "Graceful degradation: serve partial functionality rather than complete failure",
          "Chaos engineering: intentionally inject failures to test resilience (Netflix Chaos Monkey)",
        ],
      },
      {
        id: "ch13-slo",
        label: "13.3 SLAs, SLOs, SLIs",
        tone: "bullets",
        bullets: [
          "SLI (Indicator): the metric — e.g. p99 latency of API requests",
          "SLO (Objective): the target — e.g. p99 latency < 500ms for 99.9% of requests",
          "SLA (Agreement): the contract — consequences if SLO breached (refunds, credits)",
          "Error budget: 100% - SLO = budget for downtime. 99.9% SLO = 8.7 hours/year error budget.",
          "Error budget burn rate: how fast you're consuming the error budget — alert at 2% burn/hour",
          "Toil: manual repetitive operational work — automate it, measure %, target <50% of SRE time",
        ],
      },
      {
        id: "ch13-availability",
        label: "13.3 Availability Targets",
        heading: "The Nines",
        tone: "table",
        table: {
          headers: ["Availability", "Downtime/Year", "Downtime/Month", "Downtime/Week"],
          rows: [
            ["99%", "3.65 days", "7.3 hours", "1.68 hours"],
            ["99.9%", "8.7 hours", "43.8 minutes", "10.1 minutes"],
            ["99.95%", "4.4 hours", "21.9 minutes", "5 minutes"],
            ["99.99%", "52.6 minutes", "4.4 minutes", "1 minute"],
            ["99.999%", "5.26 minutes", "26.3 seconds", "6 seconds"],
          ],
        },
        sources: [
          { label: "Google SRE Workbook", url: "https://sre.google/workbook/table-of-contents/" },
          { label: "Netflix Tech Blog — Chaos Engineering", url: "https://netflixtechblog.com" },
          { label: "AWS Architecture Best Practices", url: "https://aws.amazon.com/architecture/" },
          { label: "Resilience4j — Java Circuit Breaker", url: "https://resilience4j.readme.io" },
        ],
      },
      {
        id: "ch13-interview",
        label: "Interview Questions",
        heading: "Practice these aloud",
        tone: "bullets",
        bullets: [
          "What is an error budget? How would you use it to make release decisions?",
          "Explain the circuit breaker pattern. What are the three states?",
          "What is the difference between fault tolerance and high availability?",
          "How would you design a system to handle 10x traffic spike on Black Friday?",
          "What is chaos engineering? How would you implement it?",
        ],
      },
    ],
  },

  // ─── CH 14 ──────────────────────────────────────────────────────────────
  {
    num: 14,
    phaseLabel: "CH 14",
    kind: "phase",
    title: "Real System Designs A–Z",
    subtitle:
      "These are the most common interview questions. Every answer follows the same framework: requirements → capacity → high-level → deep dive → scale → failure modes.",
    sections: [
      {
        id: "ch14-url-shortener",
        label: "Design URL Shortener (bit.ly)",
        tone: "bullets",
        bullets: [
          "Write: POST /shorten → generate 7-char Base62 code → store code:URL in Redis + Postgres",
          "Read: GET /{code} → Redis hit → 301/302 redirect. Redis miss → Postgres → cache + redirect",
          "ID generation: Base62(auto-increment ID) OR random 7-char with collision check",
          "Scale: 100M URLs, 10B redirects/day → read-heavy, Redis for 99% hit rate",
          "Analytics: async write click events to Kafka → Flink → time-series DB",
          "Custom URLs: check availability, store in same table with custom flag",
          "Video walkthrough: https://www.youtube.com/watch?v=fMZMm_0ZhK4",
        ],
      },
      {
        id: "ch14-twitter-timeline",
        label: "Design Twitter/X Timeline",
        tone: "bullets",
        bullets: [
          "Fan-out on write: on tweet, push to all followers' timeline caches — fast read",
          "Fan-out on read: on load, query followers' tweets and merge — works for celebrities",
          "Hybrid: fan-out on write for ≤10K followers, fan-out on read for celebrities",
          "Timeline storage: Redis ZSet sorted by timestamp — ZREVRANGE returns feed",
          "Tweet storage: Postgres for metadata, S3 for media, CDN for delivery",
          "Search: Elasticsearch index of tweets — query by keyword, hashtag, user",
          "Video walkthrough: https://www.youtube.com/watch?v=wYk0xPP_P_8",
        ],
      },
      {
        id: "ch14-youtube",
        label: "Design YouTube / Video Streaming",
        tone: "bullets",
        bullets: [
          "Upload: chunked upload → S3 → SQS trigger → transcoding workers (FFmpeg) → CDN",
          "Transcoding: generate multiple resolutions (360p, 720p, 1080p, 4K) + formats (HLS, DASH)",
          "HLS: video split into .ts segments + .m3u8 manifest — adaptive bitrate streaming",
          "CDN: video segments cached at edge — 95%+ cache hit rate",
          "Metadata: Postgres (video info) + Cassandra (views, likes — high write throughput)",
          "Recommendations: offline batch ML model, results cached in Redis",
          "Video walkthrough: https://www.youtube.com/watch?v=jPKTo1iGQiE",
        ],
      },
      {
        id: "ch14-whatsapp",
        label: "Design WhatsApp / Chat System",
        tone: "bullets",
        bullets: [
          "Connection: WebSocket per user — maintained by connection service (stateful)",
          "Message routing: connection service → Kafka → recipient's connection service → WebSocket push",
          "Offline delivery: message stored in Cassandra, delivered on reconnect",
          "Message ordering: Cassandra partition key = conversation_id, clustering = timestamp",
          "Delivery receipts: sent(✓), delivered(✓✓), read(✓✓ blue) — async ACKs",
          "E2E encryption: Signal Protocol — keys generated on device, server never sees plaintext",
          "Group messages: fan-out to all group members' inboxes",
          "Video walkthrough: https://www.youtube.com/watch?v=vvhC64hQZMk",
        ],
      },
      {
        id: "ch14-uber",
        label: "Design Uber / Ride-Sharing",
        tone: "bullets",
        bullets: [
          "Location updates: driver sends GPS every 4s → WebSocket → location service → Redis Geo",
          "Matching: on ride request, query Redis GEORADIUS for nearby drivers → scoring → offer",
          "Redis Geo: GEOADD, GEORADIUS, GEOPOS commands — O(N+log(M)) for radius query",
          "Trip lifecycle: state machine (requested → matched → pickup → in_trip → completed)",
          "Surge pricing: demand/supply ratio → pricing service → real-time fare calculation",
          "Maps: integrate Google Maps / MapBox for routing, ETA calculation",
          "Video walkthrough: https://www.youtube.com/watch?v=lsKU38RKQSo",
        ],
      },
      {
        id: "ch14-google-drive",
        label: "Design Google Drive / Dropbox",
        tone: "bullets",
        bullets: [
          "Upload: client chunks file (4MB) → parallel upload → S3 → merge → metadata in Postgres",
          "Sync: client maintains local index. File change → diff → upload changed chunks only",
          "Delta sync: only upload changed blocks — hash each block, compare with server",
          "Conflict resolution: last-write-wins with conflict copy creation for simultaneous edits",
          "Sharing: access control table: user_id + file_id + permission (view/edit/owner)",
          "Notifications: long-polling or WebSocket — server pushes change events to open clients",
          "Video walkthrough: https://www.youtube.com/watch?v=U0xTu6E2CT8",
        ],
      },
      {
        id: "ch14-rate-limiter",
        label: "Design Rate Limiter",
        tone: "bullets",
        bullets: [
          "Token bucket in Redis: MULTI/EXEC for atomic INCR + EXPIRE per user key",
          "Sliding window counter: Redis ZADD timestamp + ZREMRANGEBYSCORE + ZCARD",
          "Distributed: Redis single-threaded ops are atomic — safe across multiple app instances",
          "Headers: 429 response with Retry-After header when limit exceeded",
          "Configuration: per-user, per-endpoint, per-tier limits in config service",
          "Bypass: whitelist internal services, ops team IPs",
          "Video walkthrough: https://www.youtube.com/watch?v=FU4WlwfS3G0",
        ],
      },
      {
        id: "ch14-notification",
        label: "Design Notification System",
        tone: "bullets",
        bullets: [
          "Channels: push (FCM/APNs), SMS (Twilio), email (SendGrid), in-app",
          "Flow: event → Kafka topic → channel-specific workers → delivery",
          "Priority queue: critical alerts bypass queue, batch notifications batched",
          "Preferences: user opt-in/out per channel per notification type",
          "Deduplication: idempotency key on each notification — prevent duplicate sends",
          "Retry: DLQ for failed deliveries, retry with backoff, alert on DLQ depth",
          "Video walkthrough: https://www.youtube.com/watch?v=bBTPZ9NdSk8",
        ],
      },
      {
        id: "ch14-web-crawler",
        label: "Design Web Crawler",
        tone: "bullets",
        bullets: [
          "Frontier: URL queue (Redis or Kafka) — seeded with start URLs",
          "Fetch: download HTML, respect robots.txt, rate limit per domain",
          "Parse: extract links + content, normalise URLs, deduplicate with Bloom filter",
          "Storage: raw HTML in S3, parsed content + metadata in Postgres/Cassandra",
          "Politeness: limit request rate per domain (1 req/s default)",
          "Distributed: consistent hash domain → specific crawler node for politeness",
          "Video walkthrough: https://www.youtube.com/watch?v=BKZxZwUgL3Y",
        ],
      },
      {
        id: "ch14-autocomplete",
        label: "Design Search Autocomplete",
        tone: "bullets",
        bullets: [
          "Trie: in-memory prefix tree → O(prefix_length) lookup — great up to millions of terms",
          "At scale: pre-compute top-K suggestions per prefix, store in Redis",
          "Real-time updates: log queries → Flink aggregation → update top-K every hour",
          "Personalisation: blend global popularity with user's own history",
          "Typo tolerance: fuzzy matching using Elasticsearch or trie with Levenshtein distance",
          "Low latency: target <100ms p99 — serve from CDN edge if possible",
          "Video walkthrough: https://www.youtube.com/watch?v=xrYTjaK5QVM",
        ],
      },
      {
        id: "ch14-sources",
        label: "Study Sources",
        heading: "Study Sources",
        tone: "bullets",
        sources: [
          { label: "System Design Interview Vol 1 — Alex Xu", url: "https://bytebytego.com" },
          { label: "System Design Interview Vol 2 — Alex Xu", url: "https://bytebytego.com" },
          { label: "Grokking System Design (Educative)", url: "https://www.educative.io/courses/grokking-modern-system-design-interview-for-engineers-managers" },
          { label: "Exponent — System Design Practice", url: "https://www.tryexponent.com/courses/system-design-interview" },
          { label: "ByteByteGo YouTube", url: "https://youtube.com/@ByteByteGo" },
          { label: "Jordan Has No Life — System Design", url: "https://youtube.com/@jordanhasnolife5163" },
          { label: "Gaurav Sen — System Design", url: "https://youtube.com/@gkcs" },
          { label: "Hussein Nasser — Backend Engineering", url: "https://youtube.com/@hnasr" },
        ],
      },
    ],
  },

  // ─── CH 15 ──────────────────────────────────────────────────────────────
  {
    num: 15,
    phaseLabel: "CH 15",
    kind: "phase",
    title: "The Interview Framework",
    subtitle:
      "How to structure your answer to ANY system design question in 45 minutes.",
    sections: [
      {
        id: "ch15-clarify",
        label: "15.1 Step 1 — Clarify Requirements (5 min)",
        tone: "bullets",
        bullets: [
          "Functional requirements: what does the system DO? (core features only)",
          "Non-functional: scale (DAU, QPS, data size), latency SLO, consistency, availability",
          "Out of scope: explicitly state what you're NOT designing",
          "Ask: 'How many daily active users?', 'What is the read:write ratio?', 'Global or single region?'.",
        ],
      },
      {
        id: "ch15-capacity",
        label: "15.2 Step 2 — Capacity Estimation (3 min)",
        tone: "bullets",
        bullets: [
          "DAU × actions/day = QPS. Peak = 3× average.",
          "Storage: records/day × record_size × retention_days",
          "Bandwidth: QPS × response_size for both read and write",
          "Example: 100M DAU, 10 tweets/day avg → 1000 tweets/sec write, 100K reads/sec.",
        ],
      },
      {
        id: "ch15-highlevel",
        label: "15.3 Step 3 — High-Level Design (10 min)",
        tone: "bullets",
        bullets: [
          "Draw client → LB → API servers → DB / cache / queue",
          "One box per major component, arrows showing data flow",
          "Don't over-engineer at this stage — get feedback before going deep",
          "Identify read path vs write path separately",
        ],
      },
      {
        id: "ch15-deepdive",
        label: "15.4 Step 4 — Deep Dive (20 min)",
        tone: "bullets",
        bullets: [
          "Interviewer will guide: 'Tell me more about the DB schema', 'How does the feed work?'",
          "Go deep on 2-3 components: data model, algorithms, specific technology choices",
          "Justify choices: 'I chose Cassandra because...' not just 'I'd use Cassandra'",
          "Draw sequences: user request → service A → queue → service B → DB → response",
        ],
      },
      {
        id: "ch15-scale-failure",
        label: "15.5 Step 5 — Scale & Failure Modes (7 min)",
        tone: "bullets",
        bullets: [
          "Identify bottlenecks: what breaks first at 10× load?",
          "Add horizontal scaling: LB + stateless app servers",
          "Data layer: read replicas, sharding, caching strategy",
          "Failure scenarios: what if DB primary goes down? What if queue is full?",
          "Trade-offs: acknowledge what you sacrificed (consistency, complexity, cost)",
        ],
      },
      {
        id: "ch15-numbers",
        label: "15.6 Numbers Every Engineer Must Know",
        heading: "Numbers Every Engineer Must Know",
        tone: "table",
        table: {
          headers: ["Operation", "Latency", "Notes"],
          rows: [
            ["L1 cache reference", "0.5 ns", ""],
            ["L2 cache reference", "7 ns", "14× L1"],
            ["RAM access", "100 ns", "200× L1"],
            ["SSD random read", "100 µs", "1,000× RAM"],
            ["HDD seek", "10 ms", "100,000× RAM"],
            ["Intra-datacenter round trip", "0.5 ms", ""],
            ["Cross-region round trip (US-EU)", "75 ms", "Speed of light"],
            ["Redis operation", "0.5–1 ms", "Network overhead"],
            ["Postgres query (indexed)", "1–5 ms", "Connection pool assumed"],
            ["S3 GET", "10–50 ms", "First byte"],
            ["Mutex lock/unlock", "25 ns", ""],
            ["Compress 1KB with Snappy", "3 µs", ""],
            ["Send 1MB over 1Gbps network", "10 ms", ""],
            ["Read 1MB from SSD sequentially", "1 ms", ""],
          ],
        },
        sources: [
          { label: "Latency Numbers Every Programmer Should Know", url: "https://colin-scott.github.io/personal_website/research/interactive_latency.html" },
          { label: "Numbers Every Engineer Should Know — ByteByteGo", url: "https://bytebytego.com/courses/system-design-interview/scale-from-zero-to-millions-of-users" },
        ],
      },
    ],
  },

  // ─── APPENDIX ───────────────────────────────────────────────────────────
  {
    num: 16,
    phaseLabel: "APPENDIX",
    kind: "appendix",
    title: "Top Interview Questions by Category",
    subtitle:
      "Top questions across all major categories. Every question here is answerable after completing this roadmap.",
    sections: [
      {
        id: "appendix-networking",
        label: "Networking",
        heading: "Networking",
        tone: "bullets",
        bullets: [
          "What happens when you type google.com in a browser?",
          "TCP vs UDP — when do you use each?",
          "What is a DNS lookup? Walk through every step.",
          "How does HTTP/2 differ from HTTP/1.1? What is multiplexing?",
          "How does HTTPS/TLS work? What is certificate pinning?",
          "What is a CDN? How does edge caching work?",
          "Explain WebSockets. How do they differ from HTTP polling?",
          "What is CORS and how do you configure it?",
        ],
      },
      {
        id: "appendix-databases",
        label: "Databases",
        heading: "Databases",
        tone: "bullets",
        bullets: [
          "Explain ACID. Can you have ACID guarantees in a distributed system?",
          "When would you choose NoSQL over SQL?",
          "What is an index? How does a B-Tree index work?",
          "Explain database normalisation. When do you denormalise?",
          "What is the N+1 query problem? How do you fix it?",
          "What is MVCC and how does Postgres use it?",
          "Explain the difference between OLTP and OLAP.",
          "Design a schema for a social network. How do you store the follow graph?",
          "How do you handle soft deletes at scale?",
          "What is connection pooling? Why is it necessary?",
        ],
      },
      {
        id: "appendix-caching",
        label: "Caching",
        heading: "Caching",
        tone: "bullets",
        bullets: [
          "What is cache-aside? Write-through? When to use each?",
          "How do you handle cache invalidation across services?",
          "What is cache stampede? How do you prevent it?",
          "Design a distributed cache. How do you handle node failure?",
          "What Redis data structure would you use for a leaderboard?",
          "What is a Bloom filter and when would you use it?",
          "How does CDN caching differ from application caching?",
        ],
      },
      {
        id: "appendix-distributed",
        label: "Distributed Systems",
        heading: "Distributed Systems",
        tone: "bullets",
        bullets: [
          "Explain the CAP theorem. Give examples of CP and AP systems.",
          "What is eventual consistency? When is it acceptable?",
          "How does Raft achieve consensus?",
          "What is a distributed lock? How do you implement one with Redis?",
          "Explain split-brain. How do you prevent it?",
          "What is a vector clock? When do you need it?",
          "How do you implement distributed transactions?",
          "What is the two-generals problem?",
        ],
      },
      {
        id: "appendix-scalability",
        label: "Scalability & Architecture",
        heading: "Scalability & Architecture",
        tone: "bullets",
        bullets: [
          "Design a system to handle Black Friday traffic (10× normal load).",
          "What is CQRS? When would you use it?",
          "Explain the saga pattern for distributed transactions.",
          "What is a microservices architecture? When is it the wrong choice?",
          "How do you handle database migrations with zero downtime?",
          "What is a bulkhead pattern? How does it prevent cascading failures?",
          "Explain event sourcing. What are its trade-offs?",
          "How do you implement blue/green deployment for a stateful service?",
        ],
      },
      {
        id: "appendix-message-queues",
        label: "Message Queues",
        heading: "Message Queues",
        tone: "bullets",
        bullets: [
          "Kafka vs RabbitMQ vs SQS — when do you choose each?",
          "How does Kafka guarantee ordering within a partition?",
          "What is the difference between a queue and a topic?",
          "How do you handle duplicate message processing?",
          "What is a dead letter queue? When do messages go there?",
          "Design an event-driven architecture for an e-commerce order system.",
        ],
      },
      {
        id: "appendix-security",
        label: "Security",
        heading: "Security",
        tone: "bullets",
        bullets: [
          "Explain OAuth 2.0. What are the different grant types?",
          "JWT vs session tokens — when do you use each?",
          "What is SQL injection and how do you prevent it?",
          "How do you securely store passwords?",
          "What is a CSRF attack? How do you mitigate it?",
          "Explain zero-trust architecture.",
          "How do you implement rate limiting to prevent DDoS?",
        ],
      },
      {
        id: "appendix-real-designs",
        label: "Real System Designs",
        heading: "Real System Designs",
        tone: "bullets",
        bullets: [
          "Design a URL shortener (bit.ly).",
          "Design Twitter's news feed.",
          "Design a video streaming service (YouTube).",
          "Design WhatsApp.",
          "Design Uber.",
          "Design Google Drive.",
          "Design a web crawler.",
          "Design a rate limiter.",
          "Design a notification system.",
          "Design a search autocomplete.",
          "Design a distributed job scheduler.",
          "Design a metrics monitoring system.",
          "Design a distributed key-value store.",
          "Design a payment processing system.",
          "Design an API gateway.",
        ],
      },
      {
        id: "appendix-books",
        label: "Must-Read Books",
        heading: "Must-Read Books",
        tone: "bullets",
        sources: [
          { label: "Designing Data-Intensive Applications — Kleppmann (READ THIS FIRST)", url: "https://dataintensive.net" },
          { label: "System Design Interview Vol 1 — Alex Xu", url: "https://bytebytego.com" },
          { label: "System Design Interview Vol 2 — Alex Xu", url: "https://bytebytego.com" },
          { label: "Google SRE Book (free)", url: "https://sre.google/sre-book/" },
          { label: "The Art of Scalability", url: "https://www.amazon.com/Art-Scalability-Architecture-Organizations-Enterprise/dp/0134032802" },
          { label: "High Performance Browser Networking (free)", url: "https://hpbn.co" },
          { label: "Database Internals — Petrov", url: "https://www.databass.dev" },
        ],
      },
      {
        id: "appendix-youtube",
        label: "Must-Watch YouTube Channels",
        heading: "Must-Watch YouTube Channels",
        tone: "bullets",
        sources: [
          { label: "ByteByteGo — System Design", url: "https://youtube.com/@ByteByteGo" },
          { label: "Gaurav Sen", url: "https://youtube.com/@gkcs" },
          { label: "Jordan Has No Life", url: "https://youtube.com/@jordanhasnolife5163" },
          { label: "Hussein Nasser", url: "https://youtube.com/@hnasr" },
          { label: "Arpit Bhayani — System Design", url: "https://youtube.com/@ArpitBhayani" },
          { label: "Tech Dummies Narendra L", url: "https://youtube.com/@TechDummiesNarendraL" },
        ],
      },
    ],
  },
];

export function getSysdesPhase(num: number): AiePhase | undefined {
  return SYSDES_PHASES.find((p) => p.num === num);
}
