import type { AwsDay } from "@/types";
import { s, lesson, review } from "./section-helpers";

// PHASE 4 — SECURITY (Days 51–60)
export const PHASE_4: AwsDay[] = [
  lesson({
    day: 51, phase: 4, weekInPhase: 1, phaseProgress: 10,
    topic: "KMS — Key Management Service",
    task: "Create a Customer Managed Key (CMK). Encrypt a small file via `aws kms encrypt`. Decrypt. Generate a data key for envelope encryption. Rotate the CMK on a 1-year schedule.",
    depth: "AWS-managed vs Customer Managed (CMK) vs Customer Provided (SSE-C) keys, envelope encryption, key rotation, key policies",
    source: "AWS KMS docs · 'Encryption Best Practices' whitepaper",
    examWeight: "VERY HIGH — Domain 1",
    whyMatters: "KMS is the foundation of encryption at rest in AWS. Every encrypted service (S3, EBS, RDS, DynamoDB, Secrets Manager) talks to KMS under the hood. CMKs give you key rotation, CloudTrail audit per call, cross-account sharing, and the ability to revoke access (delete the key → data is inaccessible forever).",
    howToDoIt: "Create a CMK with `aws kms create-key`. Add an alias for easier reference. Attach a Key Policy controlling who can use vs administer the key. Enable rotation (yearly automatic). For large data, use envelope encryption: KMS generates a data key, you encrypt data locally with the data key, store the encrypted data key alongside.",
    watchOutFor: "Key Policies are MANDATORY — IAM policies alone aren't enough. A CMK without a policy is unusable, even by the root. KMS keys are regional — can't use a us-east-1 key for us-west-2 data (use Multi-Region Keys for that). Deleting a key has a 7–30 day waiting period.",
    doneWhen: "You can encrypt and decrypt via CLI. Rotation enabled. KMS event visible in CloudTrail.",
    examTrap: "'Audit every decryption' = CMK with CloudTrail (AWS-managed keys don't give per-call audit). 'Encrypt large data' = envelope encryption with data keys.",
    realWorld: "Compliance frameworks (PCI, HIPAA, SOC2) often require CMKs (not AWS-managed) because you need to prove key control and audit. Multi-Region Keys power cross-region encrypted DR.",
    sections: [
      s("intro", "What KMS does", "intro",
        "KMS holds encryption keys. You never see the key material. You ask KMS to encrypt or decrypt (small payloads) or generate data keys (for large payloads, envelope-encrypted). Every operation is CloudTrail-logged."),
      s("key-types", "Key types", "compare",
        "",
        {
          table: {
            headers: ["Type", "Who controls", "Cost", "Use case"],
            rows: [
              ["AWS Managed Key (aws/service)", "AWS", "Free", "Default encryption for most services"],
              ["Customer Managed Key (CMK)", "You", "$1/month + per-call", "Custom rotation, cross-account, audit trail"],
              ["Customer Provided Key (SSE-C)", "You manage entirely", "You manage", "S3 only — you send key per request"],
              ["CloudHSM", "You (FIPS 140-2 L3)", "$1.45/hr", "Full key custody, regulated industries"],
            ],
          },
        }),
      s("envelope", "Envelope encryption", "concept",
        "For data larger than 4 KB you don't encrypt with KMS directly. Instead: (1) ask KMS for a data key (KMS returns the key in plaintext + the same key encrypted under the CMK). (2) Encrypt your data with the plaintext key locally. (3) Discard plaintext key, store encrypted data key alongside ciphertext. To decrypt: ask KMS to decrypt the encrypted data key, then use the plaintext key locally. This is how S3, EBS, RDS all encrypt."),
      s("project", "Mini-project — encrypt / decrypt", "project",
        "",
        {
          code: { lang: "bash", source: '# Create CMK + alias\nKEY=$(aws kms create-key --description "App key" \\\n  --key-usage ENCRYPT_DECRYPT --query KeyMetadata.KeyId --output text)\naws kms create-alias --alias-name alias/my-app-key --target-key-id $KEY\n\n# Enable yearly rotation\naws kms enable-key-rotation --key-id $KEY\n\n# Encrypt small payload\naws kms encrypt --key-id alias/my-app-key \\\n  --plaintext "Hello World" \\\n  --query CiphertextBlob --output text | base64 -d > encrypted.bin\n\n# Decrypt\naws kms decrypt --ciphertext-blob fileb://encrypted.bin \\\n  --query Plaintext --output text | base64 -d\n\n# Generate data key for envelope encryption\naws kms generate-data-key --key-id alias/my-app-key --key-spec AES_256' },
        }),
      s("traps", "Exam traps", "trap",
        "**Key Policy is mandatory.** IAM alone is not enough.\n\n**KMS keys are regional.** For cross-region, use Multi-Region Keys.\n\n**Key deletion** has 7–30 day waiting period. Disable instead of delete unless you mean it.\n\n**Asymmetric keys** (RSA, ECC) for signing or asymmetric encryption — separate use case from the default symmetric KMS keys."),
      s("real", "Real-world — compliance & DR", "real",
        "PCI/HIPAA/SOC2 mandate CMKs. Multi-Region Keys power cross-region encrypted DR — same key ID in both regions, encrypted snapshots replicate without re-encrypting."),
    ],
  }),
  lesson({
    day: 52, phase: 4, weekInPhase: 1, phaseProgress: 20,
    topic: "Secrets Manager & SSM Parameter Store",
    task: "Store an RDS master password in Secrets Manager with automatic rotation. Read it from a Lambda via the SDK. Compare with SSM Parameter Store SecureString for app config.",
    depth: "Secrets Manager (rotation, cross-account, replication), SSM Parameter Store (Standard vs Advanced)",
    source: "AWS Secrets Manager docs · SSM Parameter Store docs",
    examWeight: "HIGH — Domain 1",
    whyMatters: "Hard-coded credentials are the #1 source of breaches. Secrets Manager + SSM Parameter Store eliminate them. Secrets Manager adds automatic rotation (Lambda-driven) — passwords change every N days without your app noticing. The exam tests when to pick which.",
    howToDoIt: "Secrets Manager for passwords and API keys that need rotation. Parameter Store for application config (feature flags, endpoint URLs). Both support KMS encryption. Both fetch in code via SDK — never hardcode. For RDS, Secrets Manager has a native rotation Lambda (changes RDS password, updates secret) on a schedule.",
    watchOutFor: "Secrets Manager: $0.40/secret/month + $0.05/10K API calls — adds up at scale. Parameter Store Standard is FREE up to 10K parameters, Advanced is $0.05/parameter/month. SecureString in Parameter Store gives you KMS encryption at no extra cost.",
    doneWhen: "RDS password rotates every 30 days automatically. Lambda fetches secret on cold start, caches it. No password in source code.",
    examTrap: "'Database password with rotation' = Secrets Manager. 'Application config (URLs, flags)' = SSM Parameter Store. 'Cross-account secret sharing' = Secrets Manager.",
    realWorld: "Every modern AWS app uses Secrets Manager for DB credentials and external API keys. Parameter Store for everything else. CI/CD pipelines fetch secrets at deploy time, not bake them in.",
    sections: [
      s("compare", "Secrets Manager vs SSM Parameter Store", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Secrets Manager", "SSM Parameter Store"],
            rows: [
              ["Automatic rotation", "Yes (Lambda-driven)", "No"],
              ["Cross-account sharing", "Yes", "No"],
              ["Cross-region replication", "Yes (multi-region secrets)", "No"],
              ["Cost", "$0.40/secret/month + API", "Free Standard / $0.05 Advanced"],
              ["Encryption", "KMS (always)", "KMS for SecureString (free)"],
              ["Use case", "Passwords, API keys (rotation)", "App config, feature flags"],
            ],
          },
        }),
      s("rotation", "Automatic rotation for RDS", "config",
        "",
        {
          code: { lang: "bash", source: '# Create secret with RDS credentials\naws secretsmanager create-secret --name prod/mydb/master \\\n  --description "RDS master credentials" \\\n  --secret-string \\\'{"username":"admin","password":"InitialPass123!","engine":"postgres","host":"mydb.us-east-1.rds.amazonaws.com","port":5432,"dbname":"app"}\\\' \\\n  --kms-key-id alias/my-app-key\n\n# Enable rotation every 30 days using AWS-managed Lambda\naws secretsmanager rotate-secret \\\n  --secret-id prod/mydb/master \\\n  --rotation-lambda-arn arn:aws:lambda:us-east-1:123:function:SecretsManagerRDSPostgreSQLRotationSingleUser \\\n  --rotation-rules AutomaticallyAfterDays=30' },
        }),
      s("read", "Read in Lambda", "config",
        "",
        {
          code: { lang: "python", source: 'import boto3, json, os\n\nclient = boto3.client("secretsmanager")\n_secret_cache = None\n\ndef get_db_creds():\n    global _secret_cache\n    if _secret_cache is None:\n        resp = client.get_secret_value(SecretId="prod/mydb/master")\n        _secret_cache = json.loads(resp["SecretString"])\n    return _secret_cache\n\ndef lambda_handler(event, context):\n    creds = get_db_creds()  # cached across invocations on warm Lambda\n    # connect to RDS with creds["username"], creds["password"], ...' },
        }),
      s("traps", "Exam traps", "trap",
        "**Secrets Manager** for rotation. **Parameter Store** for config.\n\n**Cache secrets** in your function (across warm invocations). Don't fetch every call.\n\n**SSM SecureString** = KMS encryption included free. Strong default for app config."),
      s("real", "Real-world — eliminate hardcoded creds", "real",
        "Standard pattern: Secrets Manager for DB + API keys with rotation, Parameter Store for URLs/flags/feature toggles. CI/CD fetches at deploy time."),
    ],
  }),
  lesson({
    day: 53, phase: 4, weekInPhase: 1, phaseProgress: 30,
    topic: "ACM & Certificate Manager",
    task: "Request a public ACM certificate for your domain. Validate via DNS (add the CNAME to Route 53). Attach the cert to an ALB and CloudFront. Verify HTTPS.",
    depth: "ACM public vs private CAs, DNS vs email validation, regional vs us-east-1 (for CloudFront), auto-renewal",
    source: "AWS Certificate Manager docs",
    examWeight: "HIGH — Domain 1",
    whyMatters: "ACM provides free public TLS certs that auto-renew. Manual cert management was a top cause of outages (cert expires → users see browser warnings). ACM ends that. Private CA (paid) for internal mTLS.",
    howToDoIt: "Request cert in the right region (ALB: same region as ALB; CloudFront: must be us-east-1; API Gateway edge-optimised: us-east-1; regional: same region). Validate via DNS (add CNAME to Route 53) or email. Wait minutes; cert becomes Issued. Attach to your service.",
    watchOutFor: "Public ACM certs cannot be exported (you can't download the private key). For non-AWS use, use ACM Private CA (paid). CloudFront cert MUST be in us-east-1 regardless of where your origin is.",
    doneWhen: "ALB and CloudFront serving HTTPS with valid cert. Cert auto-renews 60 days before expiry. Browser shows green padlock.",
    examTrap: "'CloudFront certificate' = us-east-1 always. 'Free TLS cert with auto-renewal' = ACM. 'Cert for on-prem app' = ACM Private CA or external (Let's Encrypt).",
    realWorld: "ACM eliminated certificate-related outages at most AWS shops. Combined with Route 53 + ALB + CloudFront, you get HTTPS-everywhere for free with zero manual rotation.",
    sections: [
      s("intro", "What ACM does", "intro",
        "ACM issues, manages, and auto-renews public TLS certificates for AWS services (ALB, NLB, CloudFront, API Gateway, Cognito, App Runner, MQ). Private CA mode issues internal certs for mTLS / internal services."),
      s("validation", "DNS vs email validation", "compare",
        "**DNS validation** (recommended) — ACM gives you a CNAME to add to Route 53. ACM keeps checking until it sees it. After issuance, the CNAME enables auto-renewal forever.\n\n**Email validation** — ACM sends to WHOIS contacts + 5 well-known addresses (admin@, hostmaster@, etc.). Manual link click. Doesn't enable auto-renewal — annual re-validation."),
      s("region", "Regional vs global cert location", "concept",
        "ACM is regional — a cert in us-east-1 cannot be used by an ALB in us-west-2. **Special case**: CloudFront certs MUST be in us-east-1 because CloudFront is global. API Gateway edge-optimised: us-east-1. Regional API Gateway / ALB / NLB: same region."),
      s("traps", "Exam traps", "trap",
        "**CloudFront → cert in us-east-1.** No exceptions.\n\n**DNS validation enables auto-renewal.** Email validation does not.\n\n**Public ACM certs can't be exported.** For exportable, use ACM Private CA."),
      s("real", "Real-world — HTTPS everywhere", "real",
        "ACM + Route 53 + ALB + CloudFront = HTTPS-everywhere for free, zero rotation, zero outages. Standard hygiene."),
    ],
  }),
  lesson({
    day: 54, phase: 4, weekInPhase: 2, phaseProgress: 40,
    topic: "WAF — Web Application Firewall",
    task: "Attach WAF to your ALB. Add the `AWSManagedRulesCommonRuleSet` (OWASP). Add a rate limit (block IPs > 2000 req / 5 min). Add a custom regex block for `../` path traversal. Test with a curl that should be blocked.",
    depth: "Web ACLs, managed rule groups (AWS, marketplace, third-party), rate-based rules, IP sets, regex patterns, geo-match, custom rules",
    source: "AWS WAF docs · 'AWS Managed Rules' reference",
    examWeight: "VERY HIGH — Domain 1",
    whyMatters: "WAF inspects HTTP/HTTPS requests at L7 and blocks malicious ones (SQLi, XSS, bots, OWASP Top 10, DDoS at L7). Free with managed rule groups; you don't need to write SQLi regex from scratch. Attaches to CloudFront (global), ALB, API Gateway, AppSync.",
    howToDoIt: "Create a Web ACL. Add rules: AWS Managed Rules (OWASP common, known-bad-IP, anonymous IPs, bot control), rate-based (block IPs over a threshold), IP sets (your blocklist or allowlist), regex/string match (custom). Order matters — rules evaluated top to bottom; first match wins. Attach the Web ACL to your CloudFront or ALB.",
    watchOutFor: "Managed rules cost per rule group + per request. Start with Count mode to see what would be blocked before flipping to Block. False positives WILL happen — have an exception process.",
    doneWhen: "Curl with `'; DROP TABLE--` in URL gets a 403. Rate limit kicks in after 2000 req/5min. CloudWatch shows WAF metrics (blocked / allowed counts).",
    examTrap: "'OWASP Top 10 protection' = WAF managed rules. 'DDoS protection' = Shield Standard (free) or Advanced (paid). 'Bot mitigation' = WAF Bot Control.",
    realWorld: "Every public-facing AWS app has WAF in front. Banks, gov, healthcare have additional managed rule groups + custom rules. Bot Control mitigates scraping and credential stuffing.",
    sections: [
      s("intro", "What WAF does", "intro",
        "WAF inspects every HTTP/HTTPS request at L7 BEFORE it reaches your app. Decides Allow / Block / Count / Captcha based on Web ACL rules. Attaches to CloudFront (global), ALB / API Gateway / AppSync (regional)."),
      s("rule-types", "Rule types", "concept",
        "• **Managed Rule Groups** — pre-built rule sets by AWS or marketplace (OWASP, IP reputation, anonymous IPs, bot control).\n• **Rate-based** — block an IP after N requests in 5 min.\n• **IP sets** — your allowlist / blocklist (CIDR list).\n• **Regex / string match** — custom patterns in URI, query, headers, body.\n• **Geo-match** — by country.\n• **Label match** — fire on labels added by upstream managed rules."),
      s("config", "Web ACL + managed rules + rate limit", "config",
        "",
        {
          code: { lang: "bash", source: '# Create Web ACL with AWS Managed Common Rule Set + rate limit\naws wafv2 create-web-acl \\\n  --name prod-acl --scope REGIONAL \\\n  --default-action Allow={} \\\n  --visibility-config SampledRequestsEnabled=true,CloudWatchMetricsEnabled=true,MetricName=prod-acl \\\n  --rules \\\'[\n    {\n      "Name": "AWSCommon", "Priority": 10,\n      "Statement": {"ManagedRuleGroupStatement":{"VendorName":"AWS","Name":"AWSManagedRulesCommonRuleSet"}},\n      "OverrideAction": {"None":{}},\n      "VisibilityConfig":{"SampledRequestsEnabled":true,"CloudWatchMetricsEnabled":true,"MetricName":"AWSCommon"}\n    },\n    {\n      "Name": "RateLimit", "Priority": 20,\n      "Statement": {"RateBasedStatement":{"Limit":2000,"AggregateKeyType":"IP"}},\n      "Action": {"Block":{}},\n      "VisibilityConfig":{"SampledRequestsEnabled":true,"CloudWatchMetricsEnabled":true,"MetricName":"RateLimit"}\n    }\n  ]\\\'\n\n# Attach to ALB\naws wafv2 associate-web-acl \\\n  --web-acl-arn $ACL_ARN \\\n  --resource-arn $ALB_ARN' },
        }),
      s("traps", "Exam traps", "trap",
        "**Start in Count mode**, then flip to Block once you've vetted false positives.\n\n**WAF on CloudFront = global** (scope=CLOUDFRONT, ACL in us-east-1). **WAF on ALB / API GW = regional**.\n\n**Rate-based rule** is the simplest DDoS-at-L7 defence."),
      s("real", "Real-world — layered defence", "real",
        "WAF + Shield Advanced + GuardDuty + CloudFront make up the standard public-facing edge protection."),
    ],
  }),
  lesson({
    day: 55, phase: 4, weekInPhase: 2, phaseProgress: 50,
    topic: "Shield, Shield Advanced & Firewall Manager",
    task: "Confirm Shield Standard is on (it's automatic and free). Compare with Shield Advanced features. Use Firewall Manager (if in an Organization) to centrally enforce a WAF policy across all accounts.",
    depth: "Shield Standard (auto, free) vs Advanced (paid, 24/7 DRT, cost protection), Firewall Manager",
    source: "AWS Shield docs · Firewall Manager",
    examWeight: "HIGH — Domain 1",
    whyMatters: "Shield Standard auto-protects you from L3/L4 DDoS at no cost. Shield Advanced ($3000/month) adds L7 protection, 24/7 DDoS Response Team (DRT), and 'cost protection' (refund of scaling charges incurred during an attack). Firewall Manager enforces WAF + Shield across an Organization.",
    howToDoIt: "Shield Standard is on by default for all AWS customers — no action needed. Shield Advanced: subscribe in the Shield console, enroll specific resources (CloudFront, ALB, NLB, Route 53 hosted zones, EIPs). Firewall Manager: needs Organizations + delegated admin; define a Web ACL policy, FM applies to all accounts in scope.",
    watchOutFor: "Shield Advanced is $3000/MONTH minimum (~$36K/year) — only worth it for genuinely high-value targets (banks, gov, top-tier SaaS). Cost protection refunds scaling charges, NOT base service charges.",
    doneWhen: "You can recite when to add Shield Advanced and when Standard is enough. Firewall Manager applies a WAF policy across all org accounts without per-account work.",
    examTrap: "'DDoS protection automatically' = Shield Standard. 'L7 DDoS + DRT + cost protection' = Shield Advanced. 'Centralised security across all accounts in an Organization' = Firewall Manager.",
    realWorld: "Most companies run Shield Standard only. Banks, gov, e-commerce on Black Friday weekend run Shield Advanced. Firewall Manager standard at any company with 10+ accounts.",
    sections: [
      s("tiers", "Shield Standard vs Advanced", "compare",
        "",
        {
          table: {
            headers: ["Tier", "Coverage", "Cost", "Extras"],
            rows: [
              ["Shield Standard", "Automatic L3/L4 DDoS", "Free", "All AWS customers"],
              ["Shield Advanced", "L3/L4/L7 DDoS + 24/7 DRT", "$3 000/month minimum", "Cost protection (refund), advanced metrics"],
            ],
          },
        }),
      s("fm", "Firewall Manager", "concept",
        "Org-wide policy engine for WAF, Shield Advanced, AWS Network Firewall, Security Group baselines. Define once, applies everywhere. Requires AWS Organizations + delegated admin account."),
      s("traps", "Exam traps", "trap",
        "**Shield Standard is free + automatic** for all customers.\n\n**Shield Advanced** is $3 000/month — only justified for high-value targets.\n\n**Firewall Manager** for org-wide enforcement of WAF/Shield/SG baselines."),
      s("real", "Real-world — when Advanced pays back", "real",
        "Black Friday e-commerce, banks, gov targets. Cost protection alone can be worth it during a serious sustained attack — refunds the 10× scaling bill."),
    ],
  }),
  lesson({
    day: 56, phase: 4, weekInPhase: 2, phaseProgress: 60,
    topic: "Cognito — User Pools & Identity Pools",
    task: "Create a Cognito User Pool. Add a User Pool Client for your web app. Wire it as an authoriser to API Gateway / ALB. Sign up + sign in with the Hosted UI. Decode the JWT.",
    depth: "User Pool vs Identity Pool, Hosted UI, OAuth flows, social/SAML federation, advanced security, MFA",
    source: "AWS Cognito docs",
    examWeight: "HIGH — Domain 1",
    whyMatters: "Cognito is AWS-managed end-user identity. User Pools = user directory + sign-in (issues JWTs). Identity Pools = exchange any token for temporary AWS credentials (so mobile/web users can read S3 / DDB directly). Used by every mobile/web AWS app that has end users.",
    howToDoIt: "Create User Pool (decide MFA, password policy, attributes). Create User Pool Client (for your app — public client without secret for SPAs, confidential with secret for server-side). Optionally enable Hosted UI (AWS gives you a sign-in/up page). Wire the JWT issuer URL into API Gateway / ALB as authoriser. Optionally federate with Google / Facebook / SAML.",
    watchOutFor: "User Pool ≠ Identity Pool. User Pool issues JWTs for your app. Identity Pool exchanges JWTs (from User Pool or any IdP) for AWS credentials (STS). They're often combined but they're separate services.",
    doneWhen: "User can sign up, sign in via Hosted UI, get a JWT, call your API. API Gateway validates JWT. (Optional) Identity Pool exchange returns AWS creds for direct S3 upload.",
    examTrap: "'Sign-in for end users' = User Pool. 'Temporary AWS credentials for end users to call AWS services directly' = Identity Pool. 'IAM Users for end users' = WRONG (IAM is for AWS account access, not millions of end users).",
    realWorld: "Most consumer-facing AWS apps use Cognito. Mobile app uploads photos directly to S3? Identity Pool. Web app calls REST API with JWT? User Pool authoriser on API Gateway.",
    sections: [
      s("two-pools", "User Pool vs Identity Pool", "compare",
        "",
        {
          table: {
            headers: ["Feature", "User Pool", "Identity Pool"],
            rows: [
              ["Purpose", "User directory + sign-in", "Exchange tokens for AWS credentials"],
              ["Output", "JWT (id, access, refresh)", "Temporary AWS STS credentials"],
              ["Use case", "Your app's login system", "Direct AWS API access from clients"],
            ],
          },
        }),
      s("federation", "Federation", "concept",
        "User Pool can federate with: Google, Facebook, Amazon, Apple, SAML IdPs (corporate SSO), OIDC IdPs. Federated identities show up in the User Pool as new users. JWTs the same regardless of IdP."),
      s("project", "Mini-project — Cognito + API Gateway", "project",
        "",
        {
          code: { lang: "bash", source: '# Create User Pool with email sign-in + MFA optional\nPOOL=$(aws cognito-idp create-user-pool --pool-name AppUsers \\\n  --auto-verified-attributes email \\\n  --mfa-configuration OPTIONAL \\\n  --policies \\\'{"PasswordPolicy":{"MinimumLength":12,"RequireUppercase":true,"RequireLowercase":true,"RequireNumbers":true,"RequireSymbols":true}}\\\' \\\n  --query UserPool.Id --output text)\n\n# Create app client (public, for SPA)\naws cognito-idp create-user-pool-client --user-pool-id $POOL \\\n  --client-name web-app \\\n  --no-generate-secret \\\n  --explicit-auth-flows ALLOW_USER_SRP_AUTH ALLOW_REFRESH_TOKEN_AUTH\n\n# Wire as HTTP API JWT authoriser:\n#   issuer:   https://cognito-idp.us-east-1.amazonaws.com/$POOL\n#   audience: [client-id]' },
        }),
      s("traps", "Exam traps", "trap",
        "**User Pool ≠ Identity Pool.** Two services.\n\n**Don't use IAM for end users** — Cognito scales to millions; IAM doesn't.\n\n**Advanced Security** detects compromised credentials and unusual sign-ins (extra cost).\n\n**Hosted UI** = AWS-provided sign-in page; saves you from building one."),
      s("real", "Real-world — mobile app", "real",
        "Mobile app: Cognito User Pool for sign-in; Identity Pool to upload photos directly to S3 with temporary STS creds — no backend in the upload path."),
    ],
  }),
  lesson({
    day: 57, phase: 4, weekInPhase: 2, phaseProgress: 70,
    topic: "IAM Identity Center & federation",
    task: "Set up IAM Identity Center (formerly SSO). Federate with Okta (or a SAML test IdP). Create permission sets (AdminAccess, ReadOnlyAccess). Assign users to AWS accounts.",
    depth: "IAM Identity Center, SAML/OIDC federation, permission sets, AWS Organizations integration",
    source: "AWS IAM Identity Center docs",
    examWeight: "HIGH — Domain 1",
    whyMatters: "IAM Identity Center is how modern enterprises do AWS access — federate corporate SSO (Okta, Azure AD), define permission sets centrally, assign users to accounts. Engineers don't have IAM Users at all; they sign in via SSO and get 1-hour STS credentials.",
    howToDoIt: "Enable Identity Center in the management account of an Organization. Pick identity source: built-in directory, Active Directory, or external SAML/OIDC (Okta, Azure AD). Define Permission Sets (groups of IAM policies). Assign users + groups to AWS accounts with permission sets. Users sign in via the AWS access portal URL.",
    watchOutFor: "Replaces both AWS SSO (renamed) and per-account IAM Users for humans. Permission sets are templates that materialise as IAM roles in each target account. Don't confuse with Cognito (which is for end-user app auth, not engineer AWS access).",
    doneWhen: "Engineer logs in via Okta → sees a list of accounts + roles → clicks → gets 1-hour console access. CLI: `aws sso login --profile X`.",
    examTrap: "'Centralised access for engineers across many AWS accounts' = IAM Identity Center. 'End-user app login' = Cognito. 'Per-account IAM Users' = wrong for any team > 5 people.",
    realWorld: "Every modern enterprise AWS shop runs Identity Center federated to Okta / Azure AD. Engineers never see an IAM User. CloudTrail audit ties every action to a real human via the federated identity.",
    sections: [
      s("intro", "What Identity Center solves", "concept",
        "Without it: per-account IAM Users, password rotation hell, audit nightmare. With it: one corporate identity (Okta/Azure AD) → access to every AWS account with the right role → 1-hour STS credentials → clean CloudTrail audit."),
      s("perm-sets", "Permission sets", "concept",
        "A permission set is a named bundle of IAM policies (e.g., 'EngineerProd' = ReadOnlyAccess + custom deploy policy). When you assign User + Account + PermSet, Identity Center materialises an IAM role in the target account that the user can assume."),
      s("traps", "Exam traps", "trap",
        "**Identity Center for engineers**, Cognito for end users.\n\n**Federation source** can be built-in directory, AD, or external SAML/OIDC.\n\n**STS credentials are 1 hour default**, up to 12h."),
      s("real", "Real-world — federation to Okta", "real",
        "Engineer logs in to Okta → clicks 'AWS' → picks account + role → gets 1-hour console. Same flow via `aws sso login` for CLI."),
    ],
  }),
  lesson({
    day: 58, phase: 4, weekInPhase: 3, phaseProgress: 80,
    topic: "GuardDuty & Detective — threat detection",
    task: "Enable GuardDuty in every region. Generate a test finding (cryptocurrency-mining DNS lookup from a test instance). Review the finding. Optionally enable Detective for investigation.",
    depth: "GuardDuty (ML-based threat detection), data sources (VPC Flow, DNS, CloudTrail), Detective for investigation, finding types",
    source: "AWS GuardDuty docs · Detective docs",
    examWeight: "VERY HIGH — Domain 1",
    whyMatters: "GuardDuty is AWS's managed IDS — ML-based threat detection that watches CloudTrail, VPC Flow Logs, and DNS queries for known-bad patterns: cryptocurrency miners, exfiltration to known C2 servers, anomalous API behaviour, leaked credentials being used. Costs nothing to start, catches real attacks.",
    howToDoIt: "Click Enable. Done. GuardDuty starts ingesting CloudTrail + Flow + DNS in background. Findings appear in the console. Multi-account: enable from a delegated admin account in an Organization to consolidate findings. Auto-archive low-priority findings to reduce noise.",
    watchOutFor: "GuardDuty has no agent. It's pure cloud-side analysis of metadata you already have. Per-region service — enable in every region you use (set up CloudFormation StackSet). Detective is a separate paid service that visualises findings as graphs.",
    doneWhen: "GuardDuty enabled in all regions. Test finding appears. Notifications go to SNS / Security Hub. Real findings investigated.",
    examTrap: "'AWS-native threat detection' = GuardDuty. 'Forensic investigation graph' = Detective. 'Vulnerability scanning' = Inspector. 'Sensitive data discovery' = Macie.",
    realWorld: "Every mature AWS account has GuardDuty in every region. It has caught: Capital One-style credential theft, cryptocurrency miners on compromised EC2s, port-scanning bots, anonymising-VPN logins from foreign IPs.",
    sections: [
      s("intro", "What GuardDuty does", "intro",
        "GuardDuty continuously analyses three data sources: VPC Flow Logs (network), CloudTrail (API calls), DNS queries. It applies ML + threat-intel feeds + AWS-curated detectors to flag anomalies. Findings are categorised by severity (Low / Medium / High)."),
      s("detective", "Detective for investigation", "concept",
        "After GuardDuty raises a finding, Detective lets you investigate: see all related API calls, network connections, IAM activity for the affected resource. Builds a graph automatically. Paid (per-event) but invaluable during real incident."),
      s("traps", "Exam traps", "trap",
        "**GuardDuty per region** — enable in every region.\n\n**No agent needed** — cloud-side metadata analysis only.\n\n**Org-wide via delegated admin** consolidates findings into one console.\n\n**Routes findings to EventBridge** → SNS / Slack / PagerDuty pipelines."),
      s("real", "Real-world — catches you weren't expecting", "real",
        "Cryptocurrency miner on a compromised EC2 — GuardDuty flagged the DNS lookup to a known mining pool within minutes. Tons of breaches were stopped by this kind of automatic alert."),
    ],
  }),
  lesson({
    day: 59, phase: 4, weekInPhase: 3, phaseProgress: 88,
    topic: "Macie & Inspector — data + vulnerability scanning",
    task: "Enable Macie in one region; let it scan your S3 buckets for PII. Enable Inspector for EC2 + ECR; review CVE findings. Compare with GuardDuty (different purpose).",
    depth: "Macie (S3 sensitive data discovery), Inspector (EC2/ECR vulnerability scanning), how they pair with GuardDuty",
    source: "AWS Macie docs · Inspector docs",
    examWeight: "HIGH — Domain 1",
    whyMatters: "Macie finds PII / PHI / PCI data in S3 buckets you didn't know contained sensitive data. Inspector scans EC2 and container images for CVEs continuously. Together with GuardDuty (threats) and Security Hub (aggregation), they form the AWS-native security stack.",
    howToDoIt: "Macie: enable in S3 region, configure jobs (one-shot or scheduled). Pays per GB scanned. Inspector: enable; auto-discovers EC2 + Lambda + ECR images; continuous scanning. Critical findings → EventBridge → notify.",
    watchOutFor: "Macie costs per GB scanned — sample first, then run targeted jobs on at-risk buckets. Inspector is per-resource per-month; covers EC2, Lambda code packages, ECR container images.",
    doneWhen: "Macie identifies a test PII file in S3. Inspector flags a known-CVE in a container image. Findings flow to Security Hub.",
    examTrap: "'Find PII in S3' = Macie. 'CVE in EC2 / containers' = Inspector. 'Threat detection (miners, exfiltration)' = GuardDuty. 'Aggregate everything' = Security Hub.",
    realWorld: "Compliance teams use Macie before audits to verify they don't have rogue PII in non-PCI buckets. Inspector wired into CI/CD gates deploys on HIGH/CRITICAL CVEs.",
    sections: [
      s("trio", "Macie vs Inspector vs GuardDuty", "compare",
        "",
        {
          table: {
            headers: ["Service", "Scans", "Looks for"],
            rows: [
              ["Macie", "S3 buckets", "PII, PHI, PCI, credentials in files"],
              ["Inspector", "EC2, Lambda, ECR", "OS / package / container CVEs"],
              ["GuardDuty", "CloudTrail, VPC Flow, DNS", "Threats / anomalies / exfiltration"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**Macie = S3 data discovery.** Not GuardDuty (threats).\n\n**Inspector = vulnerabilities.** EC2 + ECR + Lambda packages.\n\n**Pay-per-GB Macie scans** — target your jobs."),
      s("real", "Real-world — compliance + CI/CD", "real",
        "Macie pre-audit to find rogue PII. Inspector wired into CI/CD to block deploys with HIGH/CRITICAL CVEs."),
    ],
  }),
  lesson({
    day: 60, phase: 4, weekInPhase: 3, phaseProgress: 100,
    topic: "Security Hub & Config — aggregation and compliance",
    task: "Enable Security Hub. Turn on AWS Foundational Security Best Practices standard. Enable Config in every region with the conformance pack for CIS AWS Foundations Benchmark. Review compliance score.",
    depth: "Security Hub (aggregation, standards), Config (resource state tracking, rules, conformance packs), remediation",
    source: "AWS Security Hub docs · AWS Config docs",
    examWeight: "VERY HIGH — Domain 1",
    whyMatters: "Security Hub aggregates findings from GuardDuty, Inspector, Macie, 3rd-party tools — single pane of glass. Config tracks every resource's configuration state over time and evaluates it against rules. Together they answer 'are we compliant?' in real time.",
    howToDoIt: "Security Hub: enable, pick standards (AWS Foundational, CIS, PCI-DSS, NIST). Findings stream in. Config: enable in every region; pick recording scope (all resources by default). Add Config Rules (managed or custom Lambda). Conformance packs bundle rules for a standard.",
    watchOutFor: "Config records every change to every resource — that's a lot of data. Filter recorder to specific resources for cost. Security Hub charges per finding ingested + per check.",
    doneWhen: "Security Hub dashboard shows aggregated findings + compliance score. Config catches a manually-modified security group and flags it as non-compliant.",
    examTrap: "'Track config drift / changes to resources' = AWS Config. 'Aggregate findings + compliance score' = Security Hub. 'CIS / PCI compliance auto-check' = Config conformance pack or Security Hub standard.",
    realWorld: "Standard hygiene in every regulated industry. Config + Security Hub in every account, org-wide via delegated admin. Auto-remediation Lambdas fix common drift (e.g., a public bucket → make private).",
    sections: [
      s("hub", "Security Hub", "concept",
        "Aggregates findings from GuardDuty, Inspector, Macie, IAM Access Analyzer, Firewall Manager, and 3rd-party tools (Snyk, Wiz, Checkmarx). Single dashboard. Built-in security standards (AWS Foundational, CIS, PCI-DSS, NIST 800-53) auto-evaluate."),
      s("config", "AWS Config", "concept",
        "Records every configuration change to every resource. Lets you ask 'what did this SG look like 30 days ago?', 'who changed it and when?'. Rules (managed or Lambda-based) evaluate compliance continuously. Conformance Packs bundle rules for a standard (CIS, PCI)."),
      s("project", "Mini-project — enable both + a conformance pack", "project",
        "",
        {
          code: { lang: "bash", source: '# Enable Security Hub + AWS Foundational standard\naws securityhub enable-security-hub --enable-default-standards\n\n# Enable Config recorder\naws configservice put-configuration-recorder \\\n  --configuration-recorder name=default,roleARN=$CONFIG_ROLE_ARN \\\n  --recording-group allSupported=true,includeGlobalResourceTypes=true\n\naws configservice put-delivery-channel \\\n  --delivery-channel name=default,s3BucketName=$CONFIG_BUCKET\n\naws configservice start-configuration-recorder \\\n  --configuration-recorder-name default\n\n# Deploy a CIS conformance pack via CFN' },
        }),
      s("remediation", "Auto-remediation", "concept",
        "Config rule fires non-compliant → EventBridge → SSM Automation runbook OR Lambda fixes it. Common: public S3 bucket → flip private. Open security group → restrict. CloudTrail disabled → re-enable."),
      s("traps", "Exam traps", "trap",
        "**Config = state + history.** Asks 'what does this look like now / 30 days ago / who changed it?'\n\n**Security Hub = aggregator.** Doesn't generate findings on its own (mostly).\n\n**Org-wide via delegated admin.** Enable everywhere."),
      s("real", "Real-world — regulated industries", "real",
        "Banks, healthcare, gov: Config + Security Hub in every account. Auto-remediation Lambdas fix drift. Pre-audit reports come straight from Security Hub."),
    ],
  }),
];
