import type { AwsDay } from "@/types";
import { s, lesson, review } from "./section-helpers";

// PHASE 3 — NETWORKING (Days 36–50)
// Route 53, CloudFront, ALB/NLB/API Gateway, VPC Advanced, Direct Connect & VPN
export const PHASE_3: AwsDay[] = [
  lesson({
    day: 36, phase: 3, weekInPhase: 1, phaseProgress: 6,
    topic: "Route 53 — DNS fundamentals",
    task: "Register a domain (or use one you own). Create a Public Hosted Zone. Add A, CNAME, and Alias records. Point one record at an ALB. Verify resolution with `dig`.",
    depth: "Hosted zones (public/private), record types (A, AAAA, CNAME, MX, TXT, NS, Alias), TTL",
    source: "AWS Route 53 docs · 'DNS for the Cloud' AWS blog",
    examWeight: "VERY HIGH — Domain 2 + Domain 3",
    whyMatters: "Route 53 is AWS's managed DNS — but it's much more than a record store. It does health checks, failover, latency-based routing, geolocation routing, weighted A/B testing — the traffic management layer for global apps. The exam treats Route 53 routing policies as bedrock.",
    howToDoIt: "Create a Public Hosted Zone for your domain. Add records: A (IPv4), AAAA (IPv6), CNAME (alias to another DNS name), MX (mail), TXT (SPF/DKIM/verification), Alias (AWS-only superpower). For internal-only DNS, use Private Hosted Zones tied to one or more VPCs.",
    watchOutFor: "Alias records are FREE (no DNS query charge) and work at the zone apex (root domain like example.com). CNAME has a per-query charge and CANNOT be used at the zone apex. Use Alias for any AWS-resource target (ALB, CloudFront, S3 website, API Gateway).",
    doneWhen: "`dig example.com` returns the right IP. `dig www.example.com` returns the right CNAME or alias. TTLs are sane (60 s for things you might fail over, 300 s+ for static).",
    examTrap: "Zone apex (example.com, not www.example.com) cannot be a CNAME — must be A or Alias. AWS resources almost always want Alias.",
    realWorld: "Every AWS-hosted app uses Route 53 for DNS. `*.example.com` wildcards point at CloudFront. Apex points via Alias to ALB or CloudFront.",
    sections: [
      s("intro", "What Route 53 is", "intro",
        "Route 53 is AWS's authoritative DNS. It hosts your zone, answers DNS queries from a global anycast network, and supports advanced routing policies (latency, geo, failover) that turn DNS into a traffic-management layer."),
      s("records", "Record types", "concept",
        "• **A** — IPv4 address.\n• **AAAA** — IPv6 address.\n• **CNAME** — alias to another DNS name (NOT at zone apex).\n• **Alias** — AWS-only A/AAAA that points at AWS resources (ALB, CloudFront, S3 website, API GW). Free, works at apex.\n• **MX** — mail servers.\n• **TXT** — SPF, DKIM, domain verification.\n• **NS / SOA** — zone delegation."),
      s("alias-vs-cname", "Alias vs CNAME", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Alias", "CNAME"],
            rows: [
              ["Cost", "Free queries", "Charged per query"],
              ["Apex (root) support", "Yes — works at example.com", "No — apex must be A or Alias"],
              ["Target", "AWS resources only", "Any DNS name"],
              ["TTL", "Managed by AWS", "You set"],
            ],
          },
        }),
      s("project", "Mini-project — apex + www to ALB", "project",
        "",
        {
          code: { lang: "bash", source: '# Create hosted zone\nZONE=$(aws route53 create-hosted-zone --name example.com \\\n  --caller-reference $(date +%s) --query HostedZone.Id --output text | sed s,/hostedzone/,,)\n\n# Apex Alias to ALB (zone apex requires Alias, not CNAME)\ncat > apex.json <<EOF\n{\n  "Changes": [{\n    "Action": "UPSERT",\n    "ResourceRecordSet": {\n      "Name": "example.com",\n      "Type": "A",\n      "AliasTarget": {\n        "HostedZoneId": "Z35SXDOTRQ7X7K",\n        "DNSName": "my-alb-123.us-east-1.elb.amazonaws.com",\n        "EvaluateTargetHealth": true\n      }\n    }\n  }]\n}\nEOF\naws route53 change-resource-record-sets --hosted-zone-id $ZONE --change-batch file://apex.json' },
        }),
      s("traps", "Exam traps", "trap",
        "**Alias > CNAME** for AWS resources. Free + apex-capable.\n\n**TTL trade-off** — short TTL means faster failover but more DNS load. 60 s is a common compromise.\n\n**Public vs Private Hosted Zone** — Private is internal-only, tied to VPCs. Use for `*.internal` service discovery."),
      s("real", "Real-world — apex + wildcards", "real",
        "Standard pattern: apex Alias → ALB or CloudFront. `*.example.com` Alias → CloudFront. Internal `*.svc.internal` → Private Hosted Zone."),
    ],
  }),
  lesson({
    day: 37, phase: 3, weekInPhase: 1, phaseProgress: 13,
    topic: "Route 53 — 7 routing policies",
    task: "Create a weighted record (80% to prod ALB, 20% to canary ALB). Then add a failover policy with health checks (primary us-east-1, secondary us-west-2). Verify health-check failure flips traffic.",
    depth: "Simple, Weighted, Latency, Failover, Geolocation, Geoproximity, Multi-Value Answer",
    source: "AWS Route 53 Routing Policies docs",
    examWeight: "VERY HIGH — Domain 2 (Resilient)",
    whyMatters: "Routing policies turn DNS into a traffic shaper. The exam tests every single one: 'A/B test' = Weighted. 'Send users to the closest region' = Latency. 'Active-passive DR' = Failover. 'Block by country' = Geolocation. Memorise all 7.",
    howToDoIt: "Each routing policy is set per record. Combine with health checks for any policy that needs to skip unhealthy targets. Geolocation: by continent / country / state. Geoproximity (Route 53 Traffic Flow only): by physical distance with bias.",
    watchOutFor: "Failover requires a Route 53 health check (separate resource — checks an HTTP/HTTPS/TCP endpoint every 10 or 30 s from multiple locations globally). Latency policy uses AWS's latency table — you can't tune it.",
    doneWhen: "Weighted split sends ~80/20. Killing primary's health check flips DNS to secondary within 60 s.",
    examTrap: "'Active-passive DR with automatic failover' = Failover routing + health checks. 'A/B test' = Weighted. 'Closest region' = Latency.",
    realWorld: "Multi-region production apps run all 7 in combination: Latency for closest region, Failover within each region, Weighted for canary, Geolocation for legal compliance.",
    sections: [
      s("seven", "All 7 routing policies", "compare",
        "",
        {
          table: {
            headers: ["Policy", "How it works", "Use case"],
            rows: [
              ["Simple", "Single record, no health checks", "Basic single-server"],
              ["Weighted", "Split traffic by % across records", "A/B testing, canary"],
              ["Latency", "Route to lowest-latency region", "Multi-region global apps"],
              ["Failover", "Primary → Secondary on health-check failure", "Active-passive DR"],
              ["Geolocation", "By continent / country / state", "Legal compliance, content localisation"],
              ["Geoproximity", "By physical distance + bias", "Fine-grained regional routing"],
              ["Multi-Value Answer", "Up to 8 healthy IPs returned", "Client-side load balancing"],
            ],
          },
        }),
      s("weighted", "Weighted — canary deploy", "config",
        "",
        {
          code: { lang: "bash", source: '# 80% prod, 20% canary\naws route53 change-resource-record-sets --hosted-zone-id $ZONE --change-batch \\\'{\n  "Changes": [\n    {\n      "Action": "UPSERT",\n      "ResourceRecordSet": {\n        "Name": "api.example.com", "Type": "A", "SetIdentifier": "Production", "Weight": 80,\n        "AliasTarget": {"HostedZoneId":"ZXXX","DNSName":"prod-alb.us-east-1.elb.amazonaws.com","EvaluateTargetHealth":true}\n      }\n    },\n    {\n      "Action": "UPSERT",\n      "ResourceRecordSet": {\n        "Name": "api.example.com", "Type": "A", "SetIdentifier": "Canary", "Weight": 20,\n        "AliasTarget": {"HostedZoneId":"ZYYY","DNSName":"canary-alb.us-east-1.elb.amazonaws.com","EvaluateTargetHealth":true}\n      }\n    }\n  ]\n}\\\'' },
        }),
      s("health", "Health checks", "concept",
        "Independent resources that probe an endpoint every 10 or 30 s from multiple AWS locations. Fail = mark record unhealthy = skip in failover/multi-value/weighted-with-health. Three types: endpoint (HTTP/HTTPS/TCP), calculated (combo of others), CloudWatch alarm-based."),
      s("traps", "Exam traps", "trap",
        "**Failover requires health checks.**\n\n**Geolocation vs Geoproximity** — Geolocation is by political boundary (country); Geoproximity is by physical distance + bias and requires Traffic Flow.\n\n**Latency uses AWS's table** — clients in 'closest' region by network latency to AWS, not physical distance."),
      s("real", "Real-world — multi-region production", "real",
        "Latency for closest region, Failover within each region, Weighted for canary, Geolocation for legal compliance — all combined in one app."),
    ],
  }),
  lesson({
    day: 38, phase: 3, weekInPhase: 1, phaseProgress: 20,
    topic: "Route 53 — Resolver, DNSSEC, hybrid DNS",
    task: "Set up Route 53 Resolver inbound + outbound endpoints to bridge on-prem DNS and AWS Private Hosted Zones. Enable DNSSEC on a public zone.",
    depth: "Route 53 Resolver, conditional forwarding, Private Hosted Zones, DNSSEC, Traffic Flow",
    source: "AWS Route 53 Resolver docs",
    examWeight: "MEDIUM — Domain 1 + Domain 2",
    whyMatters: "Hybrid DNS is required when on-prem clients need to resolve AWS internal names and vice versa. Resolver inbound endpoints accept queries from on-prem; outbound forward AWS queries to on-prem DNS. DNSSEC adds cryptographic integrity to public DNS.",
    howToDoIt: "Resolver runs inside your VPC. **Inbound endpoint**: gives on-prem a target IP to send AWS-zone queries to (over Direct Connect / VPN). **Outbound endpoint** + Resolver Rules: forward queries for `*.corp.local` to on-prem DNS. DNSSEC on Route 53 public zone: enable signing, AWS publishes DS record to your registrar.",
    watchOutFor: "Resolver endpoints have hourly + per-query cost. They sit on ENIs in your VPC. DNSSEC validation happens on the resolver side; not all clients validate. Conditional forwarding via Resolver Rules is per-domain.",
    doneWhen: "On-prem laptop resolves `db.aws.internal`. Cloud workloads resolve `intranet.corp.local`. DNSSEC chain validates from root to your zone.",
    examTrap: "'Hybrid DNS between on-prem and AWS' = Route 53 Resolver. Not VPC peering DNS, not Private Hosted Zone alone.",
    realWorld: "Most enterprises have hybrid Resolver. Migrations from on-prem to AWS depend on it — apps reference `*.internal` names that need to keep working as services move.",
    sections: [
      s("hybrid", "Resolver inbound vs outbound", "compare",
        "",
        {
          table: {
            headers: ["Direction", "Use case", "Mechanism"],
            rows: [
              ["Inbound", "On-prem queries AWS Private Hosted Zone", "Endpoint with ENIs; on-prem DNS forwards to it"],
              ["Outbound", "AWS workloads resolve on-prem names", "Endpoint + Resolver Rules per domain"],
            ],
          },
        }),
      s("dnssec", "DNSSEC", "concept",
        "Domain Name System Security Extensions: cryptographic signatures on DNS responses. Prevents DNS hijacking. On Route 53: enable DNSSEC signing, AWS rotates KSK/ZSK, you publish a DS record at your registrar."),
      s("traps", "Exam traps", "trap",
        "**Resolver = hybrid DNS.** Different from Private Hosted Zone alone (which is just AWS-side internal DNS).\n\n**DNSSEC on Route 53** rotates keys automatically; you only set the DS record at the registrar.\n\n**Traffic Flow** is a visual policy editor on top of routing policies — useful for complex multi-region setups."),
      s("real", "Real-world — hybrid migrations", "real",
        "Migrations depend on hybrid Resolver — apps reference `*.internal` names that keep working as services move from on-prem to AWS."),
    ],
  }),
  lesson({
    day: 39, phase: 3, weekInPhase: 2, phaseProgress: 26,
    topic: "CloudFront — global CDN basics",
    task: "Create a CloudFront distribution in front of an S3 static website. Configure cache policy, viewer protocol policy (redirect-to-HTTPS), and HTTP/3. Verify edge caching by hitting from multiple locations.",
    depth: "Distributions, origins, cache behaviours, cache policies, viewer protocol policy, HTTP/3, signed URLs/cookies",
    source: "AWS CloudFront docs · 'CloudFront Best Practices' video",
    examWeight: "VERY HIGH — Domain 3",
    whyMatters: "CloudFront caches content at 450+ edge locations worldwide. Latency drops from 200ms to <20ms. Plus free DDoS protection (Shield Standard), free SSL via ACM, and HTTPS everywhere. Used in 90% of AWS architectures.",
    howToDoIt: "Pick origin (S3, ALB, EC2, custom HTTP). Define cache behaviours per path pattern (`*.jpg` cache long, `/api/*` no cache). Pick a Cache Policy + Origin Request Policy (controls what gets cached and what's forwarded). Set viewer protocol to redirect-to-HTTPS. Attach an ACM cert from us-east-1 (CloudFront cert region).",
    watchOutFor: "ACM certificates for CloudFront MUST be in us-east-1, regardless of where your origin is. Cache invalidation costs money after the first 1000 paths/month. New deploys need invalidation OR versioned filenames (`/static/v123/app.js`).",
    doneWhen: "Site loads from CloudFront. HTTPS only. Cache hit ratio > 80% in CloudWatch. Latency from a far-away test < 50ms.",
    examTrap: "'CDN' = CloudFront. 'Static site fast globally' = S3 + CloudFront + OAC. 'Cache invalidation expensive' = use versioned paths instead.",
    realWorld: "Every modern AWS app has CloudFront in front of public traffic. SPA frontends, API endpoints, static assets, images. Even API Gateway sits behind CloudFront.",
    sections: [
      s("intro", "What CloudFront is", "intro",
        "CloudFront is AWS's global CDN. 450+ edge locations on every continent. Caches content close to users so they don't traverse the internet to your origin. Bonus: free Shield Standard DDoS protection, ACM-issued TLS certs, and HTTP/3."),
      s("config", "Distribution config", "config",
        "Pick an Origin (S3 bucket, ALB, custom HTTP). Pick a Default Cache Behavior (cache TTL, allowed methods, viewer protocol). Add additional behaviours for specific path patterns (e.g., `/api/*` no cache).",
        {
          code: { lang: "bash", source: '# Minimal CloudFront for S3 static site (UI is easier; CLI for IaC)\naws cloudfront create-distribution \\\n  --distribution-config \\\'{\n    "CallerReference": "my-site-001",\n    "Origins": {\n      "Quantity": 1,\n      "Items": [{\n        "Id": "S3-my-site",\n        "DomainName": "my-site.s3.amazonaws.com",\n        "S3OriginConfig": {"OriginAccessIdentity": ""}\n      }]\n    },\n    "DefaultCacheBehavior": {\n      "TargetOriginId": "S3-my-site",\n      "ViewerProtocolPolicy": "redirect-to-https",\n      "CachePolicyId": "658327ea-f89d-4fab-a63d-7e88639e58f6",\n      "Compress": true,\n      "AllowedMethods": {"Quantity": 2, "Items": ["GET", "HEAD"]}\n    },\n    "PriceClass": "PriceClass_100",\n    "Enabled": true,\n    "DefaultRootObject": "index.html",\n    "HttpVersion": "http2and3"\n  }\\\'' },
        }),
      s("policies", "Cache & origin request policies", "concept",
        "**Cache Policy** decides what's part of the cache key (URL, query strings, headers, cookies) and the TTL.\n\n**Origin Request Policy** decides what gets forwarded to the origin — broader than cache key.\n\n**Response Headers Policy** adds/modifies response headers (CORS, security headers) without origin code changes."),
      s("price", "Price classes", "compare",
        "",
        {
          table: {
            headers: ["Class", "Coverage", "Cost"],
            rows: [
              ["PriceClass_All", "All edge locations globally", "Highest"],
              ["PriceClass_200", "All except SA / South Africa", "Mid"],
              ["PriceClass_100", "US / Canada / Europe / Israel only", "Lowest"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**ACM certs for CloudFront live in us-east-1.** Always.\n\n**Invalidations cost money** after first 1000/month. Use versioned filenames or hashes.\n\n**OAC** (Origin Access Control) is the modern way to lock CloudFront-S3; OAI is legacy.\n\n**Field-Level Encryption** encrypts specific form fields (credit cards) at the edge before reaching origin — for PCI scope reduction."),
      s("real", "Real-world — every modern app", "real",
        "SPA frontends, API endpoints, static assets, images — all through CloudFront. Even API Gateway often sits behind it for global edge caching."),
    ],
  }),
  lesson({
    day: 40, phase: 3, weekInPhase: 2, phaseProgress: 32,
    topic: "CloudFront — Lambda@Edge, CloudFront Functions, signed URLs",
    task: "Add a CloudFront Function that adds security headers (HSTS, CSP) on every response. Then implement signed URLs for a private S3 bucket of premium video.",
    depth: "Lambda@Edge events, CloudFront Functions, signed URLs vs signed cookies, geo-restriction",
    source: "AWS Lambda@Edge docs",
    examWeight: "MEDIUM — Domain 1 + Domain 3",
    whyMatters: "Edge compute lets you A/B test, rewrite URLs, add headers, or check auth without hitting your origin. Signed URLs/cookies gate access to premium content (paid videos, private downloads). Geo-restriction enforces content licensing.",
    howToDoIt: "**CloudFront Functions** for cheap, fast (sub-ms) JS at viewer-request/viewer-response. **Lambda@Edge** for full Node/Python at all 4 events (viewer-request, origin-request, origin-response, viewer-response) with bigger memory and timeout. **Signed URLs**: per-object access with expiry. **Signed cookies**: access to a tree of objects.",
    watchOutFor: "CloudFront Functions: 1ms timeout, 2 MB memory, JS only. Lambda@Edge: 5-30s timeout, 128 MB-10 GB. CloudFront Functions are cheaper. Signed URLs use a CloudFront key pair (public+private), not regular IAM.",
    doneWhen: "Security headers added on every response. Premium video URL only works with signed URL; expires after 1 hour. Geo-restriction blocks specified countries.",
    examTrap: "'Add header at edge' → CloudFront Function (cheaper). 'Auth check at edge' → Lambda@Edge (more capable).",
    realWorld: "Netflix uses Lambda@Edge to A/B test homepage layouts per region. Disney+ uses signed URLs to gate premium content per subscription tier.",
    sections: [
      s("compare", "Lambda@Edge vs CloudFront Functions", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Lambda@Edge", "CloudFront Functions"],
            rows: [
              ["Languages", "Node, Python", "JS only"],
              ["Memory", "128 MB – 10 GB", "2 MB"],
              ["Timeout", "5 s viewer / 30 s origin", "1 ms"],
              ["Trigger events", "All 4 (viewer/origin × request/response)", "Viewer request/response only"],
              ["Cost", "Higher", "~6× cheaper"],
              ["Use case", "Auth, A/B test, body manipulation", "Headers, redirects, simple URL rewrite"],
            ],
          },
        }),
      s("function", "CloudFront Function — security headers", "config",
        "",
        {
          code: { lang: "javascript", source: 'function handler(event) {\n  var response = event.response;\n  response.headers["strict-transport-security"] = { value: "max-age=63072000" };\n  response.headers["x-content-type-options"]   = { value: "nosniff" };\n  response.headers["x-frame-options"]          = { value: "DENY" };\n  response.headers["content-security-policy"]  = { value: "default-src \'self\'" };\n  return response;\n}' },
        }),
      s("signed", "Signed URLs vs signed cookies", "compare",
        "**Signed URL** — one URL = access to one specific object until expiry. Use for share links.\n\n**Signed cookies** — set on browser, grant access to many objects under a path until expiry. Use for paid video subscribers (one cookie unlocks the whole catalogue)."),
      s("geo", "Geo-restriction", "concept",
        "Whitelist or blacklist countries on a distribution. Useful for content-licensing compliance (`region: JP only` for some anime). Enforced at the edge."),
      s("traps", "Exam traps", "trap",
        "**CloudFront Function ≠ Lambda@Edge.** Functions cheaper, smaller, JS-only.\n\n**Signed URLs use CloudFront key pair**, not IAM.\n\n**OAC needs a Bucket Policy** allowing the distribution's principal."),
      s("real", "Real-world — Netflix A/B at edge", "real",
        "Lambda@Edge picks an A/B variant per user-region without hitting origin. Sub-50ms decision."),
    ],
  }),
  lesson({
    day: 41, phase: 3, weekInPhase: 2, phaseProgress: 38,
    topic: "CloudFront — Origin Shield, real-time logs, multiple origins",
    task: "Enable Origin Shield in your CloudFront distribution. Configure two origins (primary S3, secondary failover S3). Stream real-time logs to Kinesis Data Streams.",
    depth: "Origin Shield, origin failover, multi-origin distributions, real-time logs, standard logs",
    source: "AWS CloudFront Origin Shield docs",
    examWeight: "MEDIUM — Domain 3",
    whyMatters: "Origin Shield is an extra cache layer in one region between edge and origin — increases hit ratio and protects origin from regional cache misses. Origin failover sends traffic to a backup origin if primary fails. Real-time logs power custom analytics.",
    howToDoIt: "Origin Shield: pick the AWS region closest to your origin; CloudFront edges fetch through Shield first. Origin failover: define an Origin Group of two origins with HTTP status codes that trigger failover. Real-time logs: ship to Kinesis Data Streams (every request, sub-second).",
    watchOutFor: "Origin Shield adds an extra request charge but typically reduces origin load enough to be net cheaper. Real-time logs are expensive at scale; standard logs (S3) are cheap and good enough for most.",
    doneWhen: "Origin Shield in your closest region. Killing primary S3 fails over to secondary with no user-visible error. Real-time logs flowing to Kinesis.",
    examTrap: "'Reduce origin load' → Origin Shield. 'Failover origin' → Origin Group with failover criteria.",
    realWorld: "Disney+ uses Origin Shield to consolidate edge fetches and reduce S3 / origin egress. Multi-origin failover saves them on streaming launch days when origin spikes hit.",
    sections: [
      s("shield", "Origin Shield", "concept",
        "An extra cache layer between edge locations and origin, in ONE region. All edges fetch through Shield first → Shield checks its cache → only on miss does it hit origin. Increases cache hit ratio and protects origin."),
      s("failover", "Origin failover", "config",
        "Define an Origin Group with primary + secondary. List HTTP status codes (e.g., 500, 502, 503, 504) that trigger failover. CloudFront retries the secondary on those codes."),
      s("logs", "Real-time vs standard logs", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Standard logs", "Real-time logs"],
            rows: [
              ["Destination", "S3", "Kinesis Data Streams"],
              ["Latency", "Hours", "Sub-second"],
              ["Cost", "Low", "Higher (KDS shards)"],
              ["Use case", "Audit, analytics on a delay", "Live dashboards, fraud detection"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**Origin Shield = ONE extra cache layer** in a chosen region.\n\n**Origin Group** = primary + secondary with failover criteria.\n\n**WAF on CloudFront** filters at the edge — best place for OWASP rules."),
      s("real", "Real-world — Disney+ launch day", "real",
        "Origin Shield consolidated edge fetches, dropped origin egress 3-5×. Multi-origin failover handled regional origin spikes during streaming launches."),
    ],
  }),
  lesson({
    day: 42, phase: 3, weekInPhase: 3, phaseProgress: 44,
    topic: "ALB — Application Load Balancer (Layer 7)",
    task: "Build an ALB with two target groups (frontend, backend). Add path-based routing rules (`/api/*` → backend, else → frontend) and host-based routing (`api.example.com` → backend). Attach WAF.",
    depth: "ALB listeners, target groups, rules (path, host, header, query, source IP), sticky sessions, gRPC support",
    source: "AWS Application Load Balancer docs",
    examWeight: "VERY HIGH — Domain 2 + Domain 3",
    whyMatters: "ALB is Layer 7 (HTTP/HTTPS/gRPC) — sees the URL, headers, host. That lets it path-route, host-route, and integrate with WAF, Cognito, AWS-managed JWT auth. The default load balancer for web apps and microservices.",
    howToDoIt: "Create ALB across 2+ public subnets. Define a listener (443 HTTPS with ACM cert). Create target groups (one per service); attach instances or IPs (or use auto-attach via ASG/ECS). Define rules per path/host. Default rule = catch-all.",
    watchOutFor: "ALB is regional — can't span regions (use Route 53 + Global Accelerator for that). It does NOT preserve client IP at Layer 4 (use NLB if you need that). For sticky sessions, ALB sets a cookie. Listener rules are evaluated in priority order.",
    doneWhen: "`/api/*` hits backend; everything else hits frontend. WAF blocks SQL-injection-shaped requests. Healthy/unhealthy targets visible in target group health.",
    examTrap: "'Layer 7 routing by path' = ALB. 'Layer 4 ultra-low latency' = NLB. 'Static IP / private link' = NLB.",
    realWorld: "Most AWS web apps use ALB — path routing, host routing, WAF, Cognito auth. ECS / EKS service routing all funnels through ALB.",
    sections: [
      s("listeners", "Listeners + rules", "concept",
        "A listener is a port + protocol (e.g., HTTPS:443). Each listener has rules evaluated in priority order. A rule has conditions (path-pattern, host-header, http-header, source-ip, query-string) and actions (forward, redirect, fixed-response, authenticate-cognito, authenticate-oidc)."),
      s("rules", "Add path + host rules", "config",
        "",
        {
          code: { lang: "bash", source: '# Path rule: /api/* → backend\naws elbv2 create-rule \\\n  --listener-arn $LISTENER_ARN \\\n  --priority 10 \\\n  --conditions \\\'[{"Field":"path-pattern","Values":["/api/*"]}]\\\' \\\n  --actions \\\'[{"Type":"forward","TargetGroupArn":"\'$BACKEND_TG\'"}]\\\'\n\n# Host rule: api.example.com → backend\naws elbv2 create-rule \\\n  --listener-arn $LISTENER_ARN \\\n  --priority 20 \\\n  --conditions \\\'[{"Field":"host-header","Values":["api.example.com"]}]\\\' \\\n  --actions \\\'[{"Type":"forward","TargetGroupArn":"\'$BACKEND_TG\'"}]\\\'' },
        }),
      s("auth", "Built-in auth", "concept",
        "ALB can authenticate users via Cognito User Pool or any OIDC provider BEFORE traffic reaches your app. The action is `authenticate-cognito` or `authenticate-oidc`. Saves you from implementing auth in every microservice."),
      s("traps", "Exam traps", "trap",
        "**ALB = Layer 7** (HTTP/HTTPS/gRPC). **NLB = Layer 4** (TCP/UDP/TLS).\n\n**ALB does NOT preserve client IP** at Layer 4 — sets `X-Forwarded-For` header instead.\n\n**Sticky sessions** via ALB cookie or app cookie.\n\n**WAF can attach to ALB** (regional) or CloudFront (global)."),
      s("real", "Real-world — microservice routing", "real",
        "Each microservice = one target group. ALB rules route `/users/*` → users-svc, `/orders/*` → orders-svc. New service = new TG + new rule, no app redeploy."),
    ],
  }),
  lesson({
    day: 43, phase: 3, weekInPhase: 3, phaseProgress: 50,
    topic: "NLB & GWLB — Layer 4 and Layer 3 load balancers",
    task: "Provision an NLB with a static Elastic IP for a TCP service. Compare client IP visibility (NLB preserves it; ALB doesn't). Briefly explore GWLB for inspecting traffic through 3rd-party security appliances.",
    depth: "NLB (TCP/UDP/TLS), static IP, client IP preservation, PrivateLink, GWLB for security appliance chains",
    source: "AWS NLB docs · 'GWLB' AWS blog",
    examWeight: "HIGH — Domain 2 + Domain 3",
    whyMatters: "NLB shines for: ultra-low latency (millions of req/s), static IPs (Elastic IPs you can publish to firewalls), preserving client IP, and TLS pass-through. GWLB threads traffic through 3rd-party appliances (Palo Alto, Fortinet) at Layer 3 — a niche but powerful pattern.",
    howToDoIt: "NLB at Layer 4: TCP, UDP, TLS pass-through. Each AZ subnet gets one ENI with one Elastic IP (or auto-assigned). Targets can be instances, IPs, or ALBs (NLB → ALB chaining for static IP + L7 features). GWLB uses GENEVE encapsulation to route traffic through appliances.",
    watchOutFor: "NLB does NOT have rules engine like ALB — just forward to TG. NLB cross-zone load balancing is OFF by default (charges per AZ if turned on); ALB is ON by default. NLB supports PrivateLink (expose your service to other VPCs / accounts).",
    doneWhen: "Your TCP service has a fixed public IP. Backend sees the real client IP. Latency stable under load.",
    examTrap: "'Static IP / PrivateLink / TCP/UDP' = NLB. 'Layer 7 routing' = ALB. 'Traffic through 3rd-party firewall' = GWLB.",
    realWorld: "Financial trading: NLB for ultra-low-latency TCP. SaaS PrivateLink: NLB so customers reach your service via private endpoint. Healthcare: GWLB threading through HIPAA-certified inspection appliances.",
    sections: [
      s("trio", "ALB vs NLB vs GWLB", "compare",
        "",
        {
          table: {
            headers: ["Type", "OSI Layer", "Protocols", "Key features", "Use case"],
            rows: [
              ["ALB", "7", "HTTP/HTTPS/gRPC", "Path/host routing, WAF, sticky", "Web apps, microservices, containers"],
              ["NLB", "4", "TCP/UDP/TLS", "Ultra-low latency, static IP, client-IP preservation, PrivateLink", "Real-time gaming, IoT, financial trading"],
              ["GWLB", "3", "IP", "GENEVE encapsulation, route through appliances", "3rd-party firewalls, IDS/IPS"],
            ],
          },
        }),
      s("nlb-create", "Create NLB with EIPs", "config",
        "",
        {
          code: { lang: "bash", source: 'aws elbv2 create-load-balancer \\\n  --name prod-nlb \\\n  --type network \\\n  --subnet-mappings \\\n    "SubnetId=$PUB1,AllocationId=$EIP1" \\\n    "SubnetId=$PUB2,AllocationId=$EIP2" \\\n  --scheme internet-facing\n\n# Listener\naws elbv2 create-listener \\\n  --load-balancer-arn $NLB_ARN \\\n  --protocol TCP --port 1883 \\\n  --default-actions Type=forward,TargetGroupArn=$TG_ARN' },
        }),
      s("traps", "Exam traps", "trap",
        "**NLB cross-zone is OFF by default** (charges if enabled). ALB cross-zone is ON by default and free.\n\n**NLB preserves client IP** by default for instance/IP targets.\n\n**NLB supports PrivateLink** — expose your service to other VPCs as an endpoint."),
      s("real", "Real-world — SaaS PrivateLink", "real",
        "Many SaaS providers (Snowflake, Datadog) expose their service via NLB + PrivateLink. Customers reach the service over private VPC endpoints, no public internet."),
    ],
  }),
  lesson({
    day: 44, phase: 3, weekInPhase: 3, phaseProgress: 56,
    topic: "API Gateway — REST API, HTTP API, WebSocket",
    task: "Build an HTTP API with API Gateway → Lambda. Add JWT authoriser (Cognito User Pool). Configure throttling. Add a stage variable for dev/prod. Compare cost vs REST API.",
    depth: "REST API vs HTTP API vs WebSocket API, integrations, authorisers (Cognito, Lambda, IAM, JWT), throttling, usage plans, custom domains",
    source: "AWS API Gateway docs",
    examWeight: "VERY HIGH — Domain 2 + Domain 3",
    whyMatters: "API Gateway is the front door for serverless backends. Two tiers: HTTP API (cheaper, faster, modern) and REST API (full feature set including API keys, usage plans, request/response transformation). Pick HTTP API by default; REST only when you need its specific features.",
    howToDoIt: "Pick HTTP API for new builds. Define routes (`POST /users`). Pick integration (Lambda, ALB, NLB, HTTP). Pick authoriser (JWT for Cognito/Auth0, Lambda authoriser for custom auth, IAM for AWS service-to-service). Set throttling at the stage or per-route. Deploy to a stage (dev/prod). Map a custom domain via ACM cert.",
    watchOutFor: "REST API has API Keys + Usage Plans (per-customer rate limits) — HTTP API doesn't. HTTP API is ~70% cheaper and lower-latency. REST API has more authoriser options (request authoriser caches per token).",
    doneWhen: "JWT-protected API responding via Lambda. Throttle at 100 req/s. Custom domain `api.example.com`.",
    examTrap: "'Cheap modern serverless API' = HTTP API. 'Need API keys + usage plans + request transformation' = REST API. 'Real-time bidirectional' = WebSocket API.",
    realWorld: "Most modern serverless backends use HTTP API. REST API still common in legacy or when monetising APIs (per-customer keys + plans). WebSocket for real-time chat / notifications.",
    sections: [
      s("compare", "REST vs HTTP vs WebSocket", "compare",
        "",
        {
          table: {
            headers: ["Feature", "HTTP API", "REST API", "WebSocket API"],
            rows: [
              ["Cost", "~70% cheaper", "Higher", "Per message + connection minutes"],
              ["Features", "JWT, CORS, simpler", "API keys, usage plans, caching, request/response transform, WAF", "Bidirectional, persistent connection"],
              ["Latency", "Lower", "Higher (more middleware)", "Persistent — low per-message"],
              ["Use case", "Modern serverless apps", "Legacy, monetised APIs", "Chat, notifications, real-time dashboards"],
            ],
          },
        }),
      s("auth", "Authorisers", "concept",
        "• **JWT (HTTP API)** — verifies a JWT against an issuer (Cognito, Auth0, your own). Built-in.\n• **Lambda authoriser** — custom logic; cache result per token to avoid invoking on every request.\n• **IAM** — SigV4-signed requests; for service-to-service or AWS internal apps.\n• **Cognito User Pool (REST API)** — auto-validates Cognito JWTs."),
      s("project", "Mini-project — HTTP API + Cognito JWT", "project",
        "",
        {
          code: { lang: "yaml", source: '# SAM snippet\nMyApi:\n  Type: AWS::Serverless::HttpApi\n  Properties:\n    StageName: prod\n    Auth:\n      Authorizers:\n        CognitoAuth:\n          IdentitySource: $request.header.Authorization\n          JwtConfiguration:\n            issuer: !Sub https://cognito-idp.us-east-1.amazonaws.com/${UserPool}\n            audience:\n              - !Ref UserPoolClient\n      DefaultAuthorizer: CognitoAuth\n\nGetUserFunction:\n  Type: AWS::Serverless::Function\n  Properties:\n    Handler: handler.get_user\n    Runtime: python3.12\n    Events:\n      GetUser:\n        Type: HttpApi\n        Properties:\n          ApiId: !Ref MyApi\n          Path: /users/{id}\n          Method: get' },
        }),
      s("traps", "Exam traps", "trap",
        "**HTTP API by default; REST when you need its features.**\n\n**Throttling** — account default 10 000 req/s, 5 000 burst. Tune per-stage or per-route.\n\n**Custom domain** requires ACM cert (us-east-1 for edge-optimised, regional for any region)."),
      s("real", "Real-world — modern serverless", "real",
        "Most modern serverless backends use HTTP API + Lambda + DynamoDB. REST API for legacy or monetised APIs."),
    ],
  }),
  lesson({
    day: 45, phase: 3, weekInPhase: 4, phaseProgress: 62,
    topic: "Transit Gateway — hub for many VPCs",
    task: "Connect 3 VPCs to a single Transit Gateway. Use TGW route tables to allow VPC-A↔VPC-B but isolate VPC-C. Verify with `traceroute` between EC2 instances.",
    depth: "Transit Gateway, attachments, route tables, propagation, TGW peering across regions",
    source: "AWS Transit Gateway docs",
    examWeight: "VERY HIGH — Domain 1 + Domain 2",
    whyMatters: "TGW is the hub that replaces VPC peering meshes once you have ~5+ VPCs. One attachment per VPC; route tables on the TGW decide who talks to whom. Connects to on-prem via Direct Connect or VPN. Used by every multi-VPC enterprise.",
    howToDoIt: "Create TGW. Attach each VPC (one ENI per AZ). On the VPC route tables: add routes for inter-VPC CIDRs pointing to TGW. On the TGW: route tables decide which attachments share routes (segmentation). Optional: connect on-prem via Direct Connect Gateway or Site-to-Site VPN attachment.",
    watchOutFor: "TGW is regional — for cross-region, peer two TGWs (one per region). Per-attachment + per-GB charges. Don't try to use TGW for tiny networks; peering is cheaper.",
    doneWhen: "VPC-A and VPC-B can reach each other; VPC-C isolated. Cross-region via TGW peering works. On-prem reachable through TGW.",
    examTrap: "'Hub-and-spoke for many VPCs' → TGW. 'Just two VPCs' → Peering. 'Service-to-service across accounts' → PrivateLink.",
    realWorld: "Enterprises with dozens of VPCs (per-team, per-environment) all funnel through TGW. New VPC = one attachment + one route. Migration from peering mesh to TGW is a common project.",
    sections: [
      s("intro", "Why TGW", "intro",
        "VPC Peering is 1:1 and non-transitive. With N VPCs you need O(N²) peerings. TGW makes it O(N): one attachment per VPC, hub topology. Plus connects to on-prem and supports cross-region peering."),
      s("segmentation", "Route table segmentation", "concept",
        "By default all attachments share one route table. Create multiple route tables to isolate groups. Example: dev-RT, prod-RT, shared-services-RT. Dev and prod attachments share the shared-services RT (so both can reach the directory service) but not each other's RT."),
      s("multiregion", "TGW peering across regions", "concept",
        "Two TGWs (one per region) can peer. Routes propagate. Combined with Route 53 latency routing, you get a global mesh."),
      s("traps", "Exam traps", "trap",
        "**TGW is regional.** Cross-region requires TGW peering.\n\n**Per-attachment + per-GB cost.** Compare vs peering for small networks.\n\n**Direct Connect Gateway** lets one DX connection serve multiple VPCs across regions via TGW."),
      s("real", "Real-world — peering → TGW migration", "real",
        "Common project at growth-stage enterprises. Once peering count crosses ~10, TGW pays back fast in operational simplicity and route-table sanity."),
    ],
  }),
  lesson({
    day: 46, phase: 3, weekInPhase: 4, phaseProgress: 68,
    topic: "PrivateLink — expose services privately",
    task: "Create a PrivateLink endpoint service in VPC-A (backed by an NLB). Expose to VPC-B via an Interface Endpoint. Verify VPC-B reaches VPC-A's service privately, with no internet, no peering.",
    depth: "PrivateLink, endpoint services, interface endpoints, cross-account, accept/reject mode",
    source: "AWS PrivateLink docs",
    examWeight: "HIGH — Domain 1",
    whyMatters: "PrivateLink lets you expose a service in one VPC (or account) to consumers in others — privately, without peering, without internet exposure. The standard for: SaaS providers (Snowflake, Datadog), shared internal services across accounts, AWS service access without NAT.",
    howToDoIt: "Provider side: NLB with your service behind it; expose as VPC Endpoint Service. Consumer side: create Interface Endpoint pointing at the provider's service name; an ENI in your VPC gets a private IP. Acceptance mode: auto-accept (open) or manual-accept (you approve each consumer).",
    watchOutFor: "Backed by NLB only (not ALB — though NLB → ALB chaining works). Consumer pays for endpoint hours + GB. Cross-region requires endpoint in target region (PrivateLink is regional).",
    doneWhen: "Consumer VPC reaches provider service via private IP. No public internet, no VPC peering, no NAT.",
    examTrap: "'Expose internal service privately to another account/VPC' = PrivateLink. 'Mesh between many VPCs' = TGW. 'Just two VPCs' = Peering.",
    realWorld: "SaaS providers offer PrivateLink endpoints so enterprise customers don't have to expose their VPC to the internet. AWS itself uses PrivateLink for services like SQS, Secrets Manager (via Interface Endpoints).",
    sections: [
      s("intro", "What PrivateLink solves", "concept",
        "Three problems: (1) expose a service to other VPCs without peering chaos, (2) expose to other accounts without trust complexity, (3) reach AWS services from a private subnet without NAT."),
      s("provider", "Provider — endpoint service", "config",
        "",
        {
          code: { lang: "bash", source: '# Provider: create NLB-backed endpoint service\naws ec2 create-vpc-endpoint-service-configuration \\\n  --network-load-balancer-arns $NLB_ARN \\\n  --acceptance-required' },
        }),
      s("consumer", "Consumer — interface endpoint", "config",
        "",
        {
          code: { lang: "bash", source: '# Consumer: connect to provider\'s service\naws ec2 create-vpc-endpoint \\\n  --vpc-id $CONSUMER_VPC \\\n  --service-name com.amazonaws.vpce.us-east-1.vpce-svc-0abc \\\n  --vpc-endpoint-type Interface \\\n  --subnet-ids $CONSUMER_PRIV1 $CONSUMER_PRIV2 \\\n  --security-group-ids $CONSUMER_SG' },
        }),
      s("traps", "Exam traps", "trap",
        "**NLB-backed only** (or ALB chained behind NLB).\n\n**Acceptance required** option lets you approve each consumer.\n\n**Endpoint Policy** (resource-based) controls which IAM principals can use the endpoint."),
      s("real", "Real-world — Snowflake PrivateLink", "real",
        "Enterprise customers connect to Snowflake via PrivateLink so data never crosses public internet. Same pattern: Datadog, Confluent, MongoDB Atlas."),
    ],
  }),
  lesson({
    day: 47, phase: 3, weekInPhase: 4, phaseProgress: 74,
    topic: "VPC advanced — IPv6, Flow Logs, Reachability Analyzer",
    task: "Enable VPC Flow Logs to CloudWatch Logs. Run Reachability Analyzer to debug a Security Group blocking SSH. Add IPv6 to a subnet and verify dual-stack.",
    depth: "VPC Flow Logs, Reachability Analyzer, IPv6 dual-stack, BYOIP, IPAM",
    source: "AWS VPC Flow Logs docs · Reachability Analyzer",
    examWeight: "MEDIUM — Domain 1 + Domain 5",
    whyMatters: "Flow Logs capture every packet (5-tuple) for forensics, debugging, and security. Reachability Analyzer simulates network paths — answers 'why can't A reach B?' without trial-and-error. IPv6 is increasingly required for compliance and global scale.",
    howToDoIt: "Flow Logs: enable on VPC/subnet/ENI; ship to CloudWatch Logs or S3. Reachability Analyzer: pick source + destination + port; AWS evaluates SGs, NACLs, route tables, gateways, peering. IPv6: add an IPv6 CIDR to the VPC + each subnet; instances get dual-stack ENIs.",
    watchOutFor: "Flow Logs don't capture every packet — 5-tuple summaries on a 1- or 10-minute window. Don't expect packet captures. Reachability Analyzer is a one-shot evaluation; not continuous monitoring.",
    doneWhen: "Flow Logs visible in CloudWatch Insights. Reachability Analyzer found the misconfigured SG. EC2 has a public IPv6 address.",
    examTrap: "'Why can't my EC2 reach RDS?' = Reachability Analyzer. 'What ports got hit?' = Flow Logs. 'Need full packet capture' = VPC Traffic Mirroring (different feature).",
    realWorld: "SOC teams ship Flow Logs to a central account for cross-account forensics. Reachability Analyzer is the first tool a network engineer reaches for when triaging connectivity tickets.",
    sections: [
      s("flow-logs", "VPC Flow Logs", "concept",
        "Capture 5-tuple summaries (src, dst, src-port, dst-port, protocol, action, bytes) per ENI. Aggregation window 1 or 10 minutes. Destinations: CloudWatch Logs (queryable via Insights), S3 (cheap long-term), Kinesis Data Firehose."),
      s("reachability", "Reachability Analyzer", "concept",
        "Pick source + destination + port. AWS simulates the path through SGs, NACLs, route tables, IGW, NAT, peering, TGW. Returns 'reachable / not reachable' + the exact rule that blocked. Pay per analysis."),
      s("ipv6", "IPv6 dual-stack", "concept",
        "Add an IPv6 CIDR (`/56` to the VPC, `/64` per subnet). Instances get both IPv4 and IPv6. IPv6 doesn't need NAT (each instance gets a globally unique IPv6). Egress-only Internet Gateway = IPv6 equivalent of NAT (outbound only)."),
      s("traps", "Exam traps", "trap",
        "**Flow Logs ≠ packet capture.** For full packets, use VPC Traffic Mirroring.\n\n**Reachability Analyzer = one-shot.** For continuous monitoring, use Network Access Analyzer.\n\n**Egress-only IGW** = IPv6 equivalent of NAT GW."),
      s("real", "Real-world — central SOC Flow Logs", "real",
        "All Flow Logs ship to a central security account for forensics, threat detection, and audit. Cross-account aggregation via S3 + CloudWatch."),
    ],
  }),
  lesson({
    day: 48, phase: 3, weekInPhase: 5, phaseProgress: 82,
    topic: "Site-to-Site VPN — connect on-prem to VPC",
    task: "Set up a Site-to-Site VPN: Customer Gateway (your on-prem router) + Virtual Private Gateway (or TGW attachment) + VPN connection with two IPSec tunnels. Verify with `ping` from on-prem to VPC.",
    depth: "Customer Gateway, Virtual Private Gateway / TGW, IPSec tunnels (always 2), BGP vs static routing",
    source: "AWS Site-to-Site VPN docs",
    examWeight: "HIGH — Domain 1",
    whyMatters: "Most enterprises run hybrid (on-prem + AWS). Site-to-Site VPN is the encrypted tunnel over the public internet. Cheap, fast to set up, but throughput-limited (~1.25 Gbps per tunnel). For more, use Direct Connect.",
    howToDoIt: "On AWS: Create Customer Gateway (your on-prem router's public IP + BGP ASN), Virtual Private Gateway (attached to VPC) or TGW attachment. Create VPN Connection: AWS provisions 2 tunnels (HA across AZs). Download config for your router vendor. Bring up tunnels. BGP for dynamic routing OR static routes.",
    watchOutFor: "Two tunnels are always created (HA). Each tunnel has its own IKE/IPSec config. BGP recommended over static — auto-failover when a tunnel drops. Throughput per tunnel ~1.25 Gbps; aggregate two tunnels for ~2.5 Gbps.",
    doneWhen: "Both tunnels UP/UP. On-prem hosts can reach VPC instances by private IP. BGP routes propagated.",
    examTrap: "'Quick hybrid connectivity over internet' = Site-to-Site VPN. 'Dedicated, low-latency, high-throughput' = Direct Connect.",
    realWorld: "Most companies start hybrid with VPN. As traffic grows, they add Direct Connect. Both can coexist — VPN as backup for DX.",
    sections: [
      s("intro", "Site-to-Site VPN architecture", "concept",
        "Site-to-Site VPN = IPSec tunnels over the public internet between your on-prem router (Customer Gateway) and AWS (Virtual Private Gateway or TGW). AWS always provisions 2 tunnels for HA. Encryption + integrity via IPSec."),
      s("routing", "BGP vs static routing", "compare",
        "**BGP** — dynamic routing protocol. Tunnels exchange routes; auto-failover if one drops. Recommended.\n\n**Static** — you configure routes manually on both sides. No auto-failover. Acceptable only for very simple setups."),
      s("traps", "Exam traps", "trap",
        "**2 tunnels always created** for HA — bring up both.\n\n**BGP > static** for dynamic failover.\n\n**Throughput** ~1.25 Gbps per tunnel.\n\n**TGW attachment vs VGW** — TGW for hub connectivity to multiple VPCs."),
      s("real", "Real-world — VPN as DX backup", "real",
        "Companies often run VPN as automatic backup for Direct Connect — same routes, lower priority via BGP. If DX dies, traffic auto-fails over to VPN."),
    ],
  }),
  lesson({
    day: 49, phase: 3, weekInPhase: 5, phaseProgress: 90,
    topic: "Direct Connect — dedicated private connectivity",
    task: "Compare Direct Connect vs Site-to-Site VPN. Sketch a hybrid architecture: DX primary, VPN backup. Optional: provision a Hosted Connection if your AWS partner provides one.",
    depth: "DX dedicated vs hosted, DX Gateway, Direct Connect Gateway + TGW, VLAN / VIF (private, public, transit), MACsec",
    source: "AWS Direct Connect docs",
    examWeight: "HIGH — Domain 1 + Domain 2",
    whyMatters: "DX gives you private fibre to AWS — predictable latency, high throughput (1/10/100 Gbps), no internet variability. Required for: regulatory compliance, large data transfer, latency-sensitive workloads. Combined with VPN for HA.",
    howToDoIt: "Pick a DX location near you (250+ globally) or a partner. Order a connection (10 Gbps takes weeks; 1 Gbps via partner is faster). Create Virtual Interfaces: Private VIF (to one VPC), Public VIF (to AWS public services), Transit VIF (to a Direct Connect Gateway → many VPCs across regions). Add MACsec for L2 encryption.",
    watchOutFor: "DX takes weeks to months to provision (physical fibre). For faster, use a Hosted Connection from an AWS Direct Connect Partner. DX itself does NOT encrypt; pair with VPN for encryption-in-transit, or use MACsec on supported devices.",
    doneWhen: "VIF up/up. On-prem reaches AWS via DX. VPN is configured as backup with lower-priority BGP routes. Traffic auto-fails over if DX drops.",
    examTrap: "'Dedicated private high-throughput' = DX. 'Quick / cheap' = VPN. 'DX + VPN failover' = HA hybrid.",
    realWorld: "Banks, healthcare, large enterprises: DX as primary, VPN as backup. Manufacturing IoT: DX for predictable throughput. The 'big' hybrid pattern.",
    sections: [
      s("compare", "DX vs VPN", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Direct Connect", "Site-to-Site VPN"],
            rows: [
              ["Throughput", "1 / 10 / 100 Gbps", "~1.25 Gbps per tunnel"],
              ["Latency", "Predictable, low", "Variable (internet)"],
              ["Provisioning time", "Weeks to months", "Hours"],
              ["Cost", "Higher (port + data)", "Lower"],
              ["Encryption", "None native (use MACsec or VPN over DX)", "IPSec built-in"],
            ],
          },
        }),
      s("vifs", "Virtual Interfaces (VIFs)", "concept",
        "• **Private VIF** — to one VPC via VGW.\n• **Public VIF** — to AWS public services (S3, DynamoDB) over private fibre.\n• **Transit VIF** — to a Direct Connect Gateway → multiple VPCs across regions via TGW."),
      s("dx-gw", "Direct Connect Gateway", "concept",
        "Connects ONE DX connection to MULTIPLE VPCs across multiple regions. Avoids needing one DX per region. Combined with TGW, you get one DX → many VPCs everywhere."),
      s("ha", "HA pattern: DX + VPN failover", "concept",
        "Most production hybrid: DX primary (high throughput, low latency) + VPN as backup. BGP weights ensure DX is preferred; if DX drops, traffic auto-fails to VPN."),
      s("traps", "Exam traps", "trap",
        "**DX has no native encryption.** Use MACsec (on supported ports) or VPN over DX.\n\n**Public VIF** lets you reach S3 etc. without internet.\n\n**Transit VIF + DX Gateway + TGW** = the standard for global enterprises."),
      s("real", "Real-world — bank hybrid", "real",
        "DX primary, VPN backup. Public VIF for S3 access without internet. DX Gateway routes to TGW for global VPC reach."),
    ],
  }),
  review(50, 3, 5, 100,
    "Phase 3 review — Networking",
    "Sketch and rebuild the global multi-region architecture: Route 53 latency policy → CloudFront → ALB → ECS, with TGW connecting VPCs and DX/VPN bridging on-prem. 5 SAA-C03 sample questions on Domain 2 networking."),
];
