import type { AwsDay } from "@/types";
import { s, lesson, review, capstone } from "./section-helpers";

// PHASE 2 — COMPUTE & DATABASES (Days 16–35)
// Lambda, RDS/Aurora, DynamoDB, ECS, EKS, ElastiCache, SQS/SNS/EventBridge
export const PHASE_2: AwsDay[] = [
  lesson({
    day: 16, phase: 2, weekInPhase: 1, phaseProgress: 4,
    topic: "Lambda — fundamentals & limits",
    task: "Write a Python Lambda triggered by API Gateway POST /users that writes to DynamoDB. Configure memory, timeout, env vars. Test locally with `sam local invoke`. Deploy with SAM.",
    depth: "Lambda runtimes, limits, triggers, execution role, env vars, layers, SAM",
    source: "AWS Lambda docs · 'Lambda Best Practices' video · SAM tutorial",
    examWeight: "VERY HIGH — Domain 2 + Domain 3",
    whyMatters: "Lambda is the cornerstone of serverless. You upload code, AWS runs it on triggers — no servers to manage, no idle cost, scales from 0 to thousands of concurrent executions automatically. The exam loves Lambda for cost-optimised event-driven architectures.",
    howToDoIt: "Pick a runtime (Python 3.12, Node 20, Java 21, etc). Write a handler function. Configure memory (128 MB – 10 GB; CPU scales with memory). Set timeout (default 3 s, max 15 min). Attach an execution role for AWS API access. Deploy via SAM, console, or `aws lambda create-function`.",
    watchOutFor: "15-minute max timeout — for longer jobs use Step Functions or ECS. 50 MB zipped deployment package; 250 MB unzipped. /tmp is 512 MB ephemeral by default (configurable up to 10 GB). Cold starts add 100ms–1s; use Provisioned Concurrency for latency-sensitive workloads.",
    doneWhen: "Your Lambda is invocable from API Gateway, writes to DynamoDB, and you've seen its CloudWatch Logs. You can recite the 6 main limits.",
    examTrap: "If the question says 'long-running batch job (30 min)', Lambda is wrong — use ECS task or Step Functions. If it says 'process every S3 upload', Lambda is right.",
    realWorld: "Slack's message processing pipeline uses Lambda extensively: content moderation → notification fan-out → search indexing — independently scalable, pay per execution.",
    sections: [
      s("intro", "What Lambda is", "intro",
        "Lambda is AWS's serverless compute. You provide a function (handler), AWS runs it in response to triggers (API Gateway, S3 event, SQS message, schedule). Bills per millisecond of execution + memory. No idle cost. Automatic scaling from 0 to 1000 concurrent (default soft limit) — request a higher limit for production."),
      s("limits", "Limits to memorise", "concept",
        "",
        {
          table: {
            headers: ["Limit", "Value", "Notes"],
            rows: [
              ["Execution timeout", "15 min max", "Default 3 s. Longer → Step Functions / ECS"],
              ["Memory", "128 MB – 10 GB", "CPU scales proportionally with memory"],
              ["/tmp ephemeral storage", "512 MB – 10 GB", "Temporary, deleted after function ends"],
              ["Deployment package", "50 MB zipped, 250 MB unzipped", "Use Layers for shared deps"],
              ["Concurrent executions", "1 000 default (soft limit)", "Request higher for production"],
              ["Env variables", "4 KB total", "Use Secrets Manager for sensitive config"],
            ],
          },
        }),
      s("handler", "Python handler example", "config",
        "",
        {
          code: { lang: "python", source: 'import json, boto3, os\n\ndynamodb = boto3.resource("dynamodb")\ntable = dynamodb.Table(os.environ["TABLE_NAME"])\n\ndef lambda_handler(event, context):\n    """Triggered by API Gateway POST /users."""\n    try:\n        body = json.loads(event["body"])\n        table.put_item(Item={\n            "userId": body["userId"],\n            "name": body["name"],\n            "createdAt": context.aws_request_id,\n        })\n        return {\n            "statusCode": 201,\n            "body": json.dumps({"message": "User created"}),\n        }\n    except Exception as e:\n        return {"statusCode": 500, "body": json.dumps({"error": str(e)})}' },
        }),
      s("sam", "SAM template — Lambda + API GW + DynamoDB", "config",
        "",
        {
          code: { lang: "yaml", source: 'AWSTemplateFormatVersion: "2010-09-09"\nTransform: AWS::Serverless-2016-10-31\n\nGlobals:\n  Function:\n    Runtime: python3.12\n    Timeout: 30\n    MemorySize: 256\n    Environment:\n      Variables:\n        TABLE_NAME: !Ref UsersTable\n\nResources:\n  CreateUserFunction:\n    Type: AWS::Serverless::Function\n    Properties:\n      Handler: handler.lambda_handler\n      CodeUri: src/\n      Policies:\n        - DynamoDBCrudPolicy:\n            TableName: !Ref UsersTable\n      Events:\n        CreateUser:\n          Type: Api\n          Properties:\n            Path: /users\n            Method: post\n\n  UsersTable:\n    Type: AWS::Serverless::SimpleTable\n    Properties:\n      PrimaryKey:\n        Name: userId\n        Type: String' },
        }),
      s("traps", "Exam traps", "trap",
        "**Cold starts** add 100ms–1s. Mitigate with Provisioned Concurrency (extra cost). For Java, use SnapStart.\n\n**Execution role** = what your function can do (S3, DynamoDB). **Resource policy** = what can invoke your function (API Gateway, S3 event). Both are needed.\n\n**15-minute timeout.** For longer, use Step Functions to orchestrate multiple Lambdas, or move to ECS / Batch."),
      s("real", "Real-world — Slack", "real",
        "Slack's message pipeline: content moderation → notification fan-out → search indexing — Lambda chain, each step independently scalable, pay per execution."),
    ],
  }),
  lesson({
    day: 17, phase: 2, weekInPhase: 1, phaseProgress: 8,
    topic: "Lambda — triggers, layers, destinations, Lambda@Edge",
    task: "Add an S3 → Lambda trigger that resizes images on upload. Use a Lambda Layer for the Pillow library. Configure async destinations (success → SNS, failure → SQS DLQ).",
    depth: "Event sources (sync vs async vs poll), Layers, Destinations, Lambda@Edge, CloudFront Functions",
    source: "AWS Lambda Triggers docs · 'Lambda Layers' AWS blog",
    examWeight: "HIGH — Domain 2 + Domain 3",
    whyMatters: "Knowing the three invocation models (sync, async, poll-based) is exam money. Layers solve the 'every Lambda packs its own pandas' problem. Destinations replace the old DLQ pattern. Lambda@Edge / CloudFront Functions run code at edge locations — sub-50ms latency globally.",
    howToDoIt: "S3, SNS, EventBridge → async (Lambda retries 2x, then DLQ/destinations). API Gateway → sync (returns response). SQS, Kinesis, DynamoDB Streams → poll-based (Lambda polls in batches). Layers package shared deps; reference by ARN, up to 5 per function. Lambda@Edge attaches to CloudFront for request/response manipulation at edge.",
    watchOutFor: "Sync invokes return errors to caller; async invokes retry asynchronously then drop. Poll-based have batch size + retry-with-backoff knobs. Lambda@Edge has stricter limits (5s timeout, 128 MB memory, no env vars). CloudFront Functions are cheaper and faster but JS-only and 1 ms timeout.",
    doneWhen: "Upload to S3 → image resized → success message in SNS topic. A failed invoke goes to SQS DLQ. You can recite which trigger types are sync vs async.",
    examTrap: "S3 → Lambda is ASYNC. Lambda retries failures 2x with exponential backoff, then drops (or sends to destination/DLQ). Don't expect S3 to retry forever.",
    realWorld: "Coca-Cola Freestyle vending machines push telemetry to Kinesis → Lambda processes batches → DynamoDB. Lambda@Edge personalises CloudFront responses based on user country.",
    sections: [
      s("invocation", "3 invocation models", "compare",
        "",
        {
          table: {
            headers: ["Model", "Examples", "Retries", "Notes"],
            rows: [
              ["Synchronous", "API Gateway, ALB, SDK invoke", "Caller's responsibility", "Returns response or error"],
              ["Asynchronous", "S3, SNS, EventBridge, CloudWatch Events", "2 attempts then DLQ/Destinations", "Returns 202 immediately"],
              ["Poll-based", "SQS, Kinesis, DynamoDB Streams, MQ", "Built-in with batch size + window", "Lambda polls; you don't push"],
            ],
          },
        }),
      s("layers", "Lambda Layers", "concept",
        "Layers package shared dependencies (pandas, Pillow, numpy) so every function doesn't repackage them. Up to 5 layers per function. 250 MB total deployment (function + layers). Layer = zip uploaded as a Layer resource; reference by ARN."),
      s("destinations", "Destinations replace DLQ", "concept",
        "Destinations send the result of an async invoke to one of: SQS, SNS, Lambda, EventBridge. Configure on success AND on failure separately. Replaces the older DLQ pattern with richer payloads (full event + result/error)."),
      s("edge", "Lambda@Edge vs CloudFront Functions", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Lambda@Edge", "CloudFront Functions"],
            rows: [
              ["Languages", "Node.js, Python", "JS only"],
              ["Memory", "128 MB – 10 GB", "Tiny — 2 MB"],
              ["Timeout", "5 s (viewer), 30 s (origin)", "1 ms"],
              ["Use case", "Auth, A/B test, request/response rewrite", "Header manipulation, redirects, simple auth"],
              ["Cost", "Higher", "~6× cheaper"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**S3/SNS → Lambda = async**. Configure DLQ or Destinations for failures.\n\n**Reserved Concurrency** caps a function's max concurrency (prevents it from starving others). **Provisioned Concurrency** keeps environments warm (eliminates cold start, costs extra).\n\n**VPC Lambdas** — if your Lambda needs RDS access, attach to VPC. Adds ~1s cold start (recently improved with Hyperplane ENIs)."),
      s("real", "Real-world — Coca-Cola Freestyle", "real",
        "Vending machines push telemetry to Kinesis → Lambda batches → DynamoDB. Edge personalisation via Lambda@Edge based on user country."),
    ],
  }),
  lesson({
    day: 18, phase: 2, weekInPhase: 1, phaseProgress: 12,
    topic: "Lambda — Step Functions, performance tuning, observability",
    task: "Build a Step Functions state machine that orchestrates 3 Lambdas (validate → enrich → save). Add a Choice state for branching, a Parallel state for fan-out. Tune Lambda memory using Lambda Power Tuning.",
    depth: "Step Functions (Standard vs Express), Lambda Insights, X-Ray tracing, Power Tuning",
    source: "AWS Step Functions docs · 'Lambda Power Tuning' GitHub",
    examWeight: "HIGH — Domain 2",
    whyMatters: "Step Functions is the answer when one Lambda isn't enough — multi-step workflows, branching, retries, parallel fan-out, human approval. Power Tuning finds the cost/perf sweet spot for memory. X-Ray traces the full request path through Lambdas.",
    howToDoIt: "Step Functions ASL (Amazon States Language) JSON describes states (Task, Choice, Parallel, Map, Wait, Pass, Succeed, Fail). Standard workflows: long-running, exactly-once, $$. Express: high-volume, at-least-once, cheap. Power Tuning runs your function at multiple memory sizes and shows cost/perf chart.",
    watchOutFor: "Standard Step Functions are billed per state transition (expensive at scale). Express are billed per duration + invocation. X-Ray adds ~5% latency but invaluable for debugging.",
    doneWhen: "Your state machine runs end-to-end with all 3 Lambdas. You've used Power Tuning to find the cost/perf optimum. X-Ray traces show the full request flow.",
    examTrap: "'Long-running workflow with retries and human approval' → Step Functions. 'Process 1M events per hour with at-least-once' → Step Functions Express. 'Single async event handler' → just Lambda.",
    realWorld: "Capital One uses Step Functions for fraud detection workflows: validate → ML score → human review (if borderline) → notify customer. Each step is a Lambda; orchestration is in Step Functions.",
    sections: [
      s("sfn", "Step Functions — Standard vs Express", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Standard", "Express"],
            rows: [
              ["Duration", "Up to 1 year", "Up to 5 min"],
              ["Execution model", "Exactly-once", "At-least-once"],
              ["Pricing", "Per state transition", "Per execution + duration"],
              ["Use case", "Long workflows, ETL, human approval", "High-volume event processing"],
            ],
          },
        }),
      s("asl", "ASL example — orchestrate 3 Lambdas", "config",
        "",
        {
          code: { lang: "json", source: '{\n  "Comment": "User onboarding workflow",\n  "StartAt": "Validate",\n  "States": {\n    "Validate": {\n      "Type": "Task",\n      "Resource": "arn:aws:lambda:us-east-1:123:function:Validate",\n      "Next": "Enrich",\n      "Retry": [{\n        "ErrorEquals": ["States.TaskFailed"],\n        "IntervalSeconds": 2, "MaxAttempts": 3, "BackoffRate": 2\n      }]\n    },\n    "Enrich": {\n      "Type": "Parallel",\n      "Branches": [\n        {"StartAt": "Geo",  "States": {"Geo":  {"Type": "Task", "Resource": "...", "End": true}}},\n        {"StartAt": "Risk", "States": {"Risk": {"Type": "Task", "Resource": "...", "End": true}}}\n      ],\n      "Next": "Save"\n    },\n    "Save": {\n      "Type": "Task",\n      "Resource": "arn:aws:lambda:us-east-1:123:function:Save",\n      "End": true\n    }\n  }\n}' },
        }),
      s("perf", "Power Tuning + X-Ray", "concept",
        "**Lambda Power Tuning** is an open-source Step Functions state machine that runs your function at multiple memory sizes (128, 256, 512, 1024, 2048) and shows the cost-vs-duration trade-off. Often more memory is CHEAPER overall because the function finishes faster.\n\n**X-Ray** captures distributed traces across Lambdas, API Gateway, DynamoDB. Enable with one flag (`TracingConfig: {Mode: Active}`). View as a service map."),
      s("traps", "Exam traps", "trap",
        "**Standard Step Functions are EXACTLY-ONCE.** Use for financial workflows.\n\n**Express are AT-LEAST-ONCE** — your Lambdas must be idempotent.\n\n**Map state** parallelises a Lambda over an array (up to 40 concurrent by default).\n\n**.sync vs .async** — `.sync` makes the state wait for the integrated service (e.g., ECS task) to finish before transitioning."),
      s("real", "Real-world — Capital One fraud detection", "real",
        "Validate → ML score → human review (if borderline) → notify. Each step is a Lambda; orchestration is Step Functions. Failed runs replay-ready from the failed state."),
    ],
  }),
  lesson({
    day: 19, phase: 2, weekInPhase: 1, phaseProgress: 16,
    topic: "RDS — managed relational databases (Part 1)",
    task: "Provision an RDS MySQL Multi-AZ instance with `--storage-encrypted`, 7-day backup retention, deletion protection. Connect from a private EC2. Trigger a failover and time how long until you can reconnect.",
    depth: "Engines (MySQL, Postgres, MariaDB, Oracle, SQL Server), Multi-AZ, automated backups, parameter groups",
    source: "AWS RDS docs · 'Choosing a DB engine' AWS blog",
    examWeight: "VERY HIGH — Domain 2 + Domain 3",
    whyMatters: "RDS is managed SQL — AWS handles backups, patching, replication, failover. You manage schema and queries. Multi-AZ gives synchronous standby + automatic failover for HA. Read replicas scale reads. Picking the right engine + topology is a recurring exam question.",
    howToDoIt: "Pick engine. Provision in a DB subnet group spanning 2+ AZs. Enable encryption, backups (1–35 day retention), deletion protection. For HA, enable Multi-AZ (synchronous replica in another AZ, automatic failover ~60–120 s). For read scaling, add read replicas (async, separate endpoint).",
    watchOutFor: "Multi-AZ standby is INVISIBLE — you can't query it. To use the second AZ for reads, you need read replicas (async, eventual consistency). Backups are deleted when you delete the DB unless you take a final snapshot.",
    doneWhen: "Multi-AZ failover takes 60–120 seconds. You can connect via the cluster endpoint (which auto-flips to the new primary). Backups are visible in the console.",
    examTrap: "'Multi-AZ for HA' vs 'Read Replica for read scaling'. Multi-AZ is HA only — its standby is unreachable. Read replicas are reachable but lag asynchronously.",
    realWorld: "Most enterprise SaaS apps run on RDS Postgres Multi-AZ. Read replicas serve analytics queries that don't need real-time data. Backups are KMS-encrypted and replicated cross-region for DR.",
    sections: [
      s("multiaz-vs-rr", "Multi-AZ vs Read Replica", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Multi-AZ", "Read Replica"],
            rows: [
              ["Purpose", "HA / DR", "Read scaling, cross-region DR"],
              ["Replication", "Synchronous", "Asynchronous (lag)"],
              ["Standby usable?", "No — invisible", "Yes — query the replica endpoint"],
              ["Failover", "Automatic ~60–120 s", "Manual promotion"],
              ["Cross-region?", "No (same region, different AZ)", "Yes — common for DR"],
              ["Cost", "2× storage + standby", "Replica instance cost"],
            ],
          },
        }),
      s("provision", "Provision Multi-AZ MySQL", "config",
        "",
        {
          code: { lang: "bash", source: '# DB subnet group spanning 2+ AZs (required)\naws rds create-db-subnet-group \\\n  --db-subnet-group-name MyDBSubnetGroup \\\n  --db-subnet-group-description "Production DB subnets" \\\n  --subnet-ids $DB_SUBNET_AZA $DB_SUBNET_AZB\n\n# Multi-AZ MySQL\naws rds create-db-instance \\\n  --db-instance-identifier prod-mysql \\\n  --db-instance-class db.t3.medium \\\n  --engine mysql --engine-version 8.0.35 \\\n  --master-username admin \\\n  --master-user-password "SecurePass123!" \\\n  --allocated-storage 100 --storage-type gp3 \\\n  --storage-encrypted \\\n  --vpc-security-group-ids $DB_SG \\\n  --db-subnet-group-name MyDBSubnetGroup \\\n  --multi-az \\\n  --backup-retention-period 7 \\\n  --deletion-protection' },
        }),
      s("traps", "Exam traps", "trap",
        "**Multi-AZ standby is INVISIBLE.** Don't try to read from it. Use read replicas for read scaling.\n\n**Backups deleted on DB delete** unless you take a final snapshot. Always create a final snapshot in production.\n\n**Read replicas** can be promoted to standalone — this is how you do cross-region DR failover.\n\n**Storage scales online** — increase `allocated-storage` without downtime. CPU/memory change requires reboot."),
      s("real", "Real-world — RDS Postgres Multi-AZ", "real",
        "Most enterprise SaaS apps run on RDS Postgres Multi-AZ. Read replicas serve analytics. Backups KMS-encrypted, replicated cross-region for DR."),
    ],
  }),
  lesson({
    day: 20, phase: 2, weekInPhase: 1, phaseProgress: 20,
    topic: "Aurora — AWS's high-performance DB engine",
    task: "Create an Aurora PostgreSQL cluster with 1 writer + 2 reader endpoints. Connect a Lambda using RDS Proxy. Test failover (delete the writer; cluster auto-promotes a reader within 30s).",
    depth: "Aurora Serverless v1 vs v2, Aurora Global Database, RDS Proxy, IAM auth, Performance Insights",
    source: "AWS Aurora docs · 'Aurora vs RDS' AWS blog",
    examWeight: "VERY HIGH — Domain 2 + Domain 3",
    whyMatters: "Aurora is AWS's custom-built, MySQL/Postgres-compatible engine — up to 5× faster than vanilla MySQL, 3× Postgres. 6 copies of data across 3 AZs (built-in). Failover < 30 s vs RDS's 60–120 s. Aurora Serverless v2 auto-scales capacity. Global Database does sub-second cross-region replication for multi-region active-active.",
    howToDoIt: "Aurora is a CLUSTER (not just an instance). 1 writer + up to 15 readers. Storage is shared and auto-grows up to 128 TB. Use the cluster endpoint for writes, reader endpoint for read load-balancing across replicas. RDS Proxy pools connections — critical for Lambda + Aurora.",
    watchOutFor: "Aurora Serverless v1 (cold-pause to zero, slow resume) vs v2 (always-on, scales 0.5 ACU minimum). Most production should use v2 or provisioned. RDS Proxy adds ~5 ms latency but prevents 'too many connections' from Lambda swarms.",
    doneWhen: "Failover < 30 s. Lambda connects via RDS Proxy without 'too many connections' errors. You can query the reader endpoint and see lag in CloudWatch.",
    examTrap: "'Lambda hammers RDS with too many connections' → use RDS Proxy. 'Need < 30s failover' → Aurora over RDS. 'Need multi-region active-active' → Aurora Global Database.",
    realWorld: "Most modern AWS-native apps use Aurora Postgres (Serverless v2) for new workloads. Capital One, Expedia, Dow Jones all moved off RDS-MySQL/Oracle to Aurora.",
    sections: [
      s("compare", "RDS MySQL vs Aurora MySQL", "compare",
        "",
        {
          table: {
            headers: ["Feature", "RDS MySQL", "Aurora MySQL"],
            rows: [
              ["Storage", "Up to 64 TB, manual scale", "Up to 128 TB, auto-scales"],
              ["Replicas", "Up to 5 read replicas", "Up to 15 Aurora Replicas"],
              ["Failover", "60–120 s", "< 30 s"],
              ["Replication", "Async", "Storage-level, near-sync (< 10 ms lag)"],
              ["Cost", "Standard", "~20% more than RDS MySQL"],
              ["Serverless option", "No", "Aurora Serverless v2 — auto-scales"],
            ],
          },
        }),
      s("proxy", "RDS Proxy — connection pooling", "concept",
        "Lambda scales to 1000s of concurrent executions, each opening a DB connection. RDS Proxy pools and reuses connections across Lambdas. Without it, you get 'too many connections' errors. Adds ~5 ms latency. Strong recommend for any Lambda + RDS/Aurora app."),
      s("global", "Aurora Global Database", "concept",
        "Multi-region replication with < 1 s lag (typically < 100 ms). One primary region writes; up to 5 secondary regions read. Failover to a secondary region in < 1 minute (manual promotion). Used by financial services for active-passive multi-region DR."),
      s("project", "Mini-project — Aurora + RDS Proxy + Lambda", "project",
        "",
        {
          code: { lang: "bash", source: '# Create Aurora cluster\naws rds create-db-cluster \\\n  --db-cluster-identifier prod-aurora \\\n  --engine aurora-postgresql --engine-version 15.3 \\\n  --master-username admin --master-user-password "SecurePass123!" \\\n  --vpc-security-group-ids $DB_SG \\\n  --db-subnet-group-name MyDBSubnetGroup \\\n  --storage-encrypted\n\n# Add 1 writer + 2 readers\naws rds create-db-instance --db-instance-identifier prod-aurora-1 \\\n  --db-cluster-identifier prod-aurora --db-instance-class db.r6g.large \\\n  --engine aurora-postgresql\n# (repeat for 2 more readers)\n\n# Create RDS Proxy\naws rds create-db-proxy --db-proxy-name prod-aurora-proxy \\\n  --engine-family POSTGRESQL \\\n  --auth file://proxy-auth.json \\\n  --role-arn $PROXY_ROLE_ARN \\\n  --vpc-subnet-ids $DB_SUBNET_AZA $DB_SUBNET_AZB' },
        }),
      s("traps", "Exam traps", "trap",
        "**RDS Proxy** = connection pool for Lambda + RDS/Aurora.\n\n**Aurora Serverless v2** = auto-scaling provisioned (0.5 ACU min). v1 is older, has cold pauses.\n\n**Aurora Global Database** = sub-second cross-region replication; not the same as a regular cross-region read replica.\n\n**Backtrack** (Aurora MySQL only) lets you rewind the cluster to a point in time without restoring from backup."),
      s("real", "Real-world — Aurora migration", "real",
        "Capital One, Expedia, Dow Jones moved off Oracle/RDS-MySQL to Aurora. The wins: faster failover, better replication, lower licensing cost, automatic storage growth."),
    ],
  }),
  lesson({
    day: 21, phase: 2, weekInPhase: 1, phaseProgress: 24,
    topic: "RDS — backup, restore, encryption, parameter groups",
    task: "Take a manual snapshot. Restore to a new cluster. Modify a parameter group (set log_statement=all in Postgres). Reboot. Verify the change took effect.",
    depth: "Automated backups, manual snapshots, point-in-time recovery (PITR), KMS encryption, parameter groups, option groups",
    source: "AWS RDS Backup & Restore docs",
    examWeight: "HIGH — Domain 2",
    whyMatters: "Backups and PITR are how you recover from human error or corruption. Parameter groups are how you tune the engine (memory, query log, replication). KMS encryption is mandatory for compliance.",
    howToDoIt: "Automated backups: 1–35 day retention; PITR within that window. Manual snapshots: persist forever (until you delete). Both go to S3 (managed by AWS, not visible). Parameter groups override engine defaults; create your own for non-default settings. Reboot to apply 'static' parameters.",
    watchOutFor: "Encryption can be enabled at create time only. To encrypt an existing unencrypted DB: snapshot → copy snapshot with encryption → restore from encrypted snapshot. Some parameters are 'dynamic' (apply immediately), others 'static' (need reboot).",
    doneWhen: "You've restored a DB from snapshot. You've changed a static parameter and rebooted. You can recite the difference between automated backup and manual snapshot.",
    examTrap: "'Encrypt an existing unencrypted RDS' → snapshot → copy with encryption → restore. You cannot encrypt in place.",
    realWorld: "PCI-DSS, HIPAA, SOC2 all require encryption at rest. Default to KMS encryption on every RDS, even non-prod — auditors love it.",
    sections: [
      s("backups", "Automated vs manual snapshots", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Automated backup", "Manual snapshot"],
            rows: [
              ["Retention", "1–35 days", "Forever (until you delete)"],
              ["PITR", "Yes", "No"],
              ["Deleted with DB?", "Yes (unless final snapshot)", "No"],
              ["Cross-region copy?", "No directly", "Yes — copy-snapshot"],
              ["Use case", "Daily ops", "Compliance, pre-major-change checkpoint"],
            ],
          },
        }),
      s("pitr", "Point-In-Time Recovery", "concept",
        "Within your backup retention window (1–35 days), you can restore to any second. AWS combines the most recent automated backup with transaction logs. Restore creates a NEW DB instance with a new endpoint. You then update your app's connection string."),
      s("encryption", "KMS encryption — must be at create time", "concept",
        "Tick `--storage-encrypted` at create time and pass `--kms-key-id`. Encrypts: storage, automated backups, snapshots, read replicas. To encrypt an existing unencrypted DB: snapshot → copy snapshot with encryption → restore."),
      s("params", "Parameter groups", "config",
        "Engine settings (max_connections, log_statement, work_mem). Default group is read-only — create your own. Some params are 'dynamic' (apply immediately), others 'static' (need reboot).",
        {
          code: { lang: "bash", source: '# Create custom parameter group\naws rds create-db-parameter-group \\\n  --db-parameter-group-name prod-pg15 \\\n  --db-parameter-group-family postgres15 \\\n  --description "production postgres 15"\n\n# Modify a parameter\naws rds modify-db-parameter-group \\\n  --db-parameter-group-name prod-pg15 \\\n  --parameters "ParameterName=log_statement,ParameterValue=all,ApplyMethod=pending-reboot"\n\n# Apply to instance + reboot\naws rds modify-db-instance --db-instance-identifier prod-mysql \\\n  --db-parameter-group-name prod-pg15 --apply-immediately\naws rds reboot-db-instance --db-instance-identifier prod-mysql' },
        }),
      s("traps", "Exam traps", "trap",
        "**Encryption at create time only.** To encrypt existing: snapshot → copy with encryption → restore.\n\n**Final snapshot** — always set on prod or you lose data on accidental delete.\n\n**Cross-region snapshots** — copy snapshot to target region for DR. Encrypt with a KMS key in the target region (KMS keys are regional)."),
      s("real", "Real-world — compliance defaults", "real",
        "PCI-DSS, HIPAA, SOC2 require encryption at rest. Default to KMS encryption on every RDS, even non-prod."),
    ],
  }),
  lesson({
    day: 22, phase: 2, weekInPhase: 2, phaseProgress: 28,
    topic: "DynamoDB — single-table design",
    task: "Create a DynamoDB table for a Users + Orders model in a single table. Use composite PK (PK = userId, SK = ORDER#timestamp). Add a GSI on country. Insert + query with Boto3.",
    depth: "Tables, items, PK/SK, GSI/LSI, on-demand vs provisioned, single-table design",
    source: "AWS DynamoDB docs · 'The DynamoDB Book' by Alex DeBrie",
    examWeight: "VERY HIGH — Domain 2 + Domain 3",
    whyMatters: "DynamoDB is AWS's serverless NoSQL — single-digit ms latency at any scale, from 1 req/s to millions. No servers, no schema migrations. Used by Lyft, Snapchat, Airbnb. The exam loves DynamoDB for any 'massive scale, simple queries' scenario.",
    howToDoIt: "Pick a Partition Key (distributes data across partitions; must have high cardinality). Optional Sort Key for range queries within a partition. Add GSIs for non-PK access patterns. Choose On-Demand (pay per request) or Provisioned (set RCU/WCU). Single-table design: put all entities in ONE table with crafted PK/SK patterns.",
    watchOutFor: "Items max 400 KB. Hot partitions: if all queries hit one PK, throttling. PK design must distribute load. Strong consistency costs 2× the RCU of eventual. Querying without a PK = `Scan` = expensive and slow.",
    doneWhen: "Your single table holds Users and Orders together. You can query 'all orders for user X' (PK = userId). GSI lets you query 'all users in country Y' without scanning.",
    examTrap: "'DynamoDB is slow' = wrong PK design (hot partition). 'DynamoDB is expensive' = using Scan instead of Query, or wrong capacity mode.",
    realWorld: "Lyft uses DynamoDB for ride state. Each ride is one item. PK is rideId; GSI on driverId gives 'all rides for driver X'. Single-digit-ms latency at peak ride hours.",
    sections: [
      s("model", "Data model", "compare",
        "",
        {
          table: {
            headers: ["Concept", "DynamoDB", "SQL"],
            rows: [
              ["Table", "Table", "Table"],
              ["Row", "Item (max 400 KB)", "Row"],
              ["Column", "Attribute (schema-less except keys)", "Column"],
              ["Primary Key", "Partition Key (+ optional Sort Key)", "Primary Key"],
              ["Index", "GSI / LSI", "Secondary index"],
              ["Joins", "None — denormalise", "JOIN"],
            ],
          },
        }),
      s("design", "Single-table design", "concept",
        "Counter-intuitive but right for DynamoDB: put MULTIPLE entity types in ONE table. Use PK/SK patterns to differentiate.\n\nUsers: `PK=USER#alice, SK=PROFILE`\nOrders: `PK=USER#alice, SK=ORDER#2024-01-15T10:30:00Z`\n\nQuery `PK=USER#alice` returns the profile + all orders in one shot. No joins."),
      s("create", "Create table with GSI", "config",
        "",
        {
          code: { lang: "python", source: 'import boto3\n\ndynamodb = boto3.resource("dynamodb")\n\ntable = dynamodb.create_table(\n    TableName="AppData",\n    KeySchema=[\n        {"AttributeName": "PK", "KeyType": "HASH"},\n        {"AttributeName": "SK", "KeyType": "RANGE"},\n    ],\n    AttributeDefinitions=[\n        {"AttributeName": "PK", "AttributeType": "S"},\n        {"AttributeName": "SK", "AttributeType": "S"},\n        {"AttributeName": "country", "AttributeType": "S"},\n    ],\n    GlobalSecondaryIndexes=[{\n        "IndexName": "CountryIndex",\n        "KeySchema": [\n            {"AttributeName": "country", "KeyType": "HASH"},\n            {"AttributeName": "SK", "KeyType": "RANGE"},\n        ],\n        "Projection": {"ProjectionType": "ALL"},\n    }],\n    BillingMode="PAY_PER_REQUEST",\n)' },
        }),
      s("query", "Query patterns", "config",
        "",
        {
          code: { lang: "python", source: 'table = dynamodb.Table("AppData")\n\n# Get user profile + all orders in one query\nresponse = table.query(\n    KeyConditionExpression="PK = :pk",\n    ExpressionAttributeValues={":pk": "USER#alice"},\n)\n\n# Just orders\nresponse = table.query(\n    KeyConditionExpression="PK = :pk AND begins_with(SK, :sk)",\n    ExpressionAttributeValues={":pk": "USER#alice", ":sk": "ORDER#"},\n)\n\n# All US users via GSI\nresponse = table.query(\n    IndexName="CountryIndex",\n    KeyConditionExpression="country = :c",\n    ExpressionAttributeValues={":c": "US"},\n)' },
        }),
      s("traps", "Exam traps", "trap",
        "**Hot partition** — if all queries go to one PK, you get throttled. Design PK to distribute traffic.\n\n**Scan = bad.** Always Query. Add a GSI if you need to query a non-PK attribute.\n\n**Item size 400 KB max.** Store large blobs in S3, store the S3 key in DynamoDB.\n\n**RCU/WCU**: 1 RCU = 1 strongly-consistent 4 KB read/sec. Eventually consistent costs half."),
      s("real", "Real-world — Lyft ride state", "real",
        "Each ride is one item. PK is rideId; GSI on driverId gives 'all rides for driver X'. Single-digit-ms latency at peak hours."),
    ],
  }),
  lesson({
    day: 23, phase: 2, weekInPhase: 2, phaseProgress: 32,
    topic: "DynamoDB — capacity modes, Streams, Global Tables, DAX",
    task: "Switch your table to Provisioned with Auto Scaling. Enable DynamoDB Streams. Wire a Lambda to the stream that logs every change. Convert the table to a Global Table replicating to us-west-2.",
    depth: "On-Demand vs Provisioned + Auto Scaling, Streams + Lambda, Global Tables, DAX",
    source: "AWS DynamoDB Streams docs · 'Global Tables' AWS blog",
    examWeight: "HIGH — Domain 2 + Domain 3",
    whyMatters: "Capacity mode = $$. Streams enable change data capture (CDC) — every write triggers Lambda. Global Tables = active-active multi-region. DAX = microsecond cache in front of DynamoDB. The exam tests when each is the right answer.",
    howToDoIt: "On-Demand: pay per request, scales infinitely, ~7× more expensive per request than provisioned. Use for spiky/unknown traffic. Provisioned + Auto Scaling: cheaper for steady load, scales between min/max. Streams: 24h retention, 4 view types, integrate with Lambda. Global Tables: multi-region active-active with last-writer-wins. DAX: in-memory cache, microsecond reads.",
    watchOutFor: "Streams retention is 24 hours — a slow Lambda can lose data. Global Tables require Streams enabled, and use last-writer-wins (no conflict resolution). DAX is DynamoDB-only, not a generic cache.",
    doneWhen: "Lambda fires on every Stream record. Global Table replicates within 1 s to us-west-2. You can recite when to use On-Demand vs Provisioned.",
    examTrap: "'Stream of every DynamoDB change' = DynamoDB Streams + Lambda. Not EventBridge, not SNS. 'Microsecond reads' = DAX, not ElastiCache.",
    realWorld: "Disney+ uses DynamoDB Global Tables for user profiles — every region has full replica, low-latency reads everywhere, last-writer-wins for the rare cross-region edit.",
    sections: [
      s("modes", "Capacity modes", "compare",
        "",
        {
          table: {
            headers: ["Mode", "Pricing", "Best for"],
            rows: [
              ["On-Demand", "Per request", "Spiky / unknown traffic, dev, new apps"],
              ["Provisioned", "RCU/WCU per hour", "Predictable steady load"],
              ["Provisioned + Auto Scaling", "Provisioned with min/max bounds", "Variable but forecastable"],
            ],
          },
        }),
      s("streams", "DynamoDB Streams + Lambda", "concept",
        "Every write (insert/update/delete) emits a stream record (24h retention). View types: KEYS_ONLY, NEW_IMAGE, OLD_IMAGE, NEW_AND_OLD_IMAGES. Lambda triggers (poll-based, batch). Used for: cross-region replication (powers Global Tables), search indexing (DDB → OpenSearch), audit logs, real-time analytics."),
      s("global", "Global Tables", "concept",
        "Active-active multi-region. Pick regions; AWS replicates. Sub-second lag. Last-writer-wins (no conflict resolution — design around it). Requires Streams enabled. Use for: low-latency global reads, active-active DR."),
      s("dax", "DAX — DynamoDB Accelerator", "concept",
        "In-memory cache fronting DynamoDB. Microsecond reads (vs single-ms for DDB). API-compatible — your code doesn't change, just point at DAX endpoint. Cache invalidation is automatic for writes through DAX. DAX is DynamoDB-only — for general caching use ElastiCache."),
      s("traps", "Exam traps", "trap",
        "**Streams retention is 24 hours.** Slow Lambda → data loss.\n\n**Global Tables** — active-active, last-writer-wins. Don't expect conflict resolution.\n\n**DAX vs ElastiCache** — DAX is DDB-only, ElastiCache is general-purpose.\n\n**TTL** lets you auto-expire items (deletes within 48h of TTL); no extra cost."),
      s("real", "Real-world — Disney+ profiles", "real",
        "Global Tables: every region has full replica, low-latency reads everywhere, last-writer-wins for rare cross-region edits."),
    ],
  }),
  lesson({
    day: 24, phase: 2, weekInPhase: 2, phaseProgress: 36,
    topic: "DynamoDB — transactions, advanced patterns, when NOT to use",
    task: "Use TransactWriteItems to atomically transfer 'tokens' between two user items. Implement optimistic locking via a version attribute. Compare cost vs separate writes.",
    depth: "Transactions (TransactWriteItems / TransactGetItems), conditional writes, optimistic locking, when DynamoDB is wrong",
    source: "AWS DynamoDB Transactions docs",
    examWeight: "MEDIUM — Domain 2",
    whyMatters: "DynamoDB is great until you need joins, complex queries, or strong consistency across rows — then it's wrong. Knowing when to pick RDS instead is exam money. Transactions give you ACID across up to 100 items / 4 MB — at 2× the cost of separate writes.",
    howToDoIt: "TransactWriteItems: up to 100 items, all-or-nothing. Use ConditionExpression to enforce optimistic locking (version attribute). For cross-item updates that need to be atomic, this is the answer. For joins, full-text search, complex aggregations — use RDS or Aurora instead.",
    watchOutFor: "Transactions cost 2× the WCU/RCU. They're not a free lunch. Conditional writes throw `ConditionalCheckFailedException` — your app must handle it as a retry, not a fatal error.",
    doneWhen: "Your transfer is atomic — either both items update or neither does. Optimistic locking detects concurrent updates and retries.",
    examTrap: "'Need joins, GROUP BY, complex SQL' → not DynamoDB, use RDS / Aurora. 'Need full-text search' → OpenSearch. 'Need < 5 ms reads at scale, simple queries' → DynamoDB.",
    realWorld: "Most fintech ledgers use DynamoDB transactions for double-entry bookkeeping. Each debit + credit is one transaction; either both happen or neither.",
    sections: [
      s("transactions", "TransactWriteItems", "config",
        "",
        {
          code: { lang: "python", source: 'client = boto3.client("dynamodb")\n\nclient.transact_write_items(TransactItems=[\n    {\n        "Update": {\n            "TableName": "Users",\n            "Key": {"userId": {"S": "alice"}},\n            "UpdateExpression": "SET tokens = tokens - :amt",\n            "ConditionExpression": "tokens >= :amt",\n            "ExpressionAttributeValues": {":amt": {"N": "10"}},\n        }\n    },\n    {\n        "Update": {\n            "TableName": "Users",\n            "Key": {"userId": {"S": "bob"}},\n            "UpdateExpression": "SET tokens = tokens + :amt",\n            "ExpressionAttributeValues": {":amt": {"N": "10"}},\n        }\n    },\n])' },
        }),
      s("locking", "Optimistic locking via version", "config",
        "",
        {
          code: { lang: "python", source: 'table.update_item(\n    Key={"PK": "USER#alice"},\n    UpdateExpression="SET email = :e, version = version + :one",\n    ConditionExpression="version = :current",\n    ExpressionAttributeValues={\n        ":e": "new@example.com",\n        ":one": 1,\n        ":current": 5,  # version we read\n    },\n)\n# Raises ConditionalCheckFailedException if version moved → retry' },
        }),
      s("when-not", "When NOT to use DynamoDB", "compare",
        "",
        {
          table: {
            headers: ["Need", "Use instead"],
            rows: [
              ["Joins, GROUP BY, complex SQL", "RDS / Aurora"],
              ["Full-text search", "OpenSearch"],
              ["Time-series at petabyte scale", "Timestream"],
              ["Graph traversal", "Neptune"],
              ["BI dashboards / OLAP", "Redshift"],
              ["Document-heavy unstructured", "DocumentDB / MongoDB"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**Transactions cost 2×** the regular WCU/RCU.\n\n**ConditionalCheckFailedException** is normal during contention — retry.\n\n**Querying without a key = Scan = bad.** Add a GSI.\n\n**No SQL.** PartiQL gets you SQL-like syntax but it's a layer on top, not native."),
      s("real", "Real-world — fintech ledger", "real",
        "Double-entry bookkeeping: each debit + credit is one transaction. Either both happen or neither — never partial."),
    ],
  }),
  lesson({
    day: 25, phase: 2, weekInPhase: 2, phaseProgress: 40,
    topic: "ECS & ECR — containers without Kubernetes",
    task: "Push a Node.js Docker image to ECR. Define an ECS Fargate task definition. Run it as a Service behind an ALB with target tracking on CPU. Verify rolling deploy by pushing a v2.",
    depth: "ECS clusters, services, task definitions, EC2 vs Fargate launch type, ECR, IAM task role vs execution role",
    source: "AWS ECS docs · ECS workshop",
    examWeight: "VERY HIGH — Domain 2",
    whyMatters: "ECS is AWS's container orchestrator — simpler than Kubernetes, AWS-native. Fargate launch type = no EC2 to manage (true serverless containers). The default container choice for AWS-only shops. Every modern AWS arch has ECS or Lambda at its compute core.",
    howToDoIt: "Build Docker image. Push to ECR (get login token first). Write a task definition (JSON: image, CPU, memory, env vars, port mappings, IAM roles). Create an ECS service: how many tasks to run, which subnets, which target group. Service auto-restarts failed tasks and rolling-deploys updates.",
    watchOutFor: "Task execution role = what ECS needs (pull from ECR, write logs). Task role = what your container needs (S3, DynamoDB). Two different roles. Fargate vs EC2: Fargate easier, EC2 cheaper at scale (and supports Windows / GPU).",
    doneWhen: "Service running, ALB returns 200, push v2 → rolling deploy completes without downtime.",
    examTrap: "'Container without managing servers' → Fargate. 'Container with Windows / GPU' → ECS EC2 launch type. 'Need Kubernetes specifically' → EKS.",
    realWorld: "Most modern AWS-native microservices run on ECS Fargate behind ALB. Frees teams from EC2 patching, AMI building, ASG management.",
    sections: [
      s("ecs-vs-eks", "ECS vs EKS vs Lambda", "compare",
        "",
        {
          table: {
            headers: ["Feature", "ECS", "EKS", "Lambda"],
            rows: [
              ["API", "AWS proprietary", "Kubernetes standard", "Lambda invoke"],
              ["Portability", "AWS-only", "k8s-compatible (multi-cloud)", "AWS-only"],
              ["Operational overhead", "Low", "Medium-high", "Lowest"],
              ["Cluster fee", "$0", "$0.10/hr per cluster", "$0"],
              ["Use when", "AWS-native simplicity", "Multi-cloud or existing k8s skills", "Event-driven, < 15 min jobs"],
            ],
          },
        }),
      s("taskdef", "Task definition", "config",
        "",
        {
          code: { lang: "json", source: '{\n  "family": "web-app",\n  "networkMode": "awsvpc",\n  "requiresCompatibilities": ["FARGATE"],\n  "cpu": "256", "memory": "512",\n  "executionRoleArn": "arn:aws:iam::123:role/ecsTaskExecutionRole",\n  "taskRoleArn": "arn:aws:iam::123:role/myTaskRole",\n  "containerDefinitions": [{\n    "name": "web",\n    "image": "123.dkr.ecr.us-east-1.amazonaws.com/my-app:latest",\n    "portMappings": [{"containerPort": 8080, "protocol": "tcp"}],\n    "secrets": [{\n      "name": "DB_PASSWORD",\n      "valueFrom": "arn:aws:secretsmanager:us-east-1:123:secret:db-pass"\n    }],\n    "logConfiguration": {\n      "logDriver": "awslogs",\n      "options": {\n        "awslogs-group": "/ecs/web-app",\n        "awslogs-region": "us-east-1",\n        "awslogs-stream-prefix": "web"\n      }\n    },\n    "healthCheck": {\n      "command": ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"],\n      "interval": 30, "timeout": 5, "retries": 3\n    }\n  }]\n}' },
        }),
      s("deploy", "Push image + create service", "config",
        "",
        {
          code: { lang: "bash", source: '# ECR login + push\naws ecr get-login-password --region us-east-1 | \\\n  docker login --username AWS \\\n  --password-stdin 123.dkr.ecr.us-east-1.amazonaws.com\ndocker build -t my-app .\ndocker tag my-app:latest 123.dkr.ecr.us-east-1.amazonaws.com/my-app:latest\ndocker push 123.dkr.ecr.us-east-1.amazonaws.com/my-app:latest\n\n# Create service\naws ecs create-service \\\n  --cluster prod-cluster \\\n  --service-name web-app \\\n  --task-definition web-app:3 \\\n  --desired-count 3 \\\n  --launch-type FARGATE \\\n  --network-configuration "awsvpcConfiguration={subnets=[$PRIV1,$PRIV2],securityGroups=[$ECS_SG],assignPublicIp=DISABLED}" \\\n  --load-balancers "targetGroupArn=$TG_ARN,containerName=web,containerPort=8080" \\\n  --deployment-configuration "maximumPercent=200,minimumHealthyPercent=100"' },
        }),
      s("traps", "Exam traps", "trap",
        "**Two IAM roles** — execution role (ECS pulling image, writing logs) AND task role (your container's AWS access).\n\n**Fargate** — no EC2, simplest, ~30% pricier at scale.\n\n**EC2 launch type** — needed for Windows / GPU / specific networking.\n\n**Service Auto Scaling** scales tasks based on CPU/memory or ALB request count."),
      s("real", "Real-world — modern AWS microservices", "real",
        "Modern AWS-only microservices run ECS Fargate behind ALB. Frees teams from EC2 patching, AMI building, ASG management."),
    ],
  }),
  lesson({
    day: 26, phase: 2, weekInPhase: 2, phaseProgress: 44,
    topic: "ECS — service auto scaling, blue/green, advanced features",
    task: "Add Service Auto Scaling to your ECS service (target tracking on ALB request count). Configure blue/green deployment via CodeDeploy. Roll out a v3.",
    depth: "Service Auto Scaling, blue/green via CodeDeploy, capacity providers, ECS Exec, sidecar pattern",
    source: "AWS ECS Service Auto Scaling · 'ECS Blue/Green' AWS blog",
    examWeight: "MEDIUM — Domain 2",
    whyMatters: "Auto Scaling ECS services keeps cost low and traffic served. Blue/green deploys via CodeDeploy give you instant rollback (just shift the ALB). ECS Exec lets you `docker exec` into a Fargate task for debugging.",
    howToDoIt: "Service Auto Scaling: register the service as a scalable target, attach target tracking. Blue/green via CodeDeploy: register two target groups, CodeDeploy shifts traffic. ECS Exec: enable on the service, then `aws ecs execute-command --cluster X --task Y --container Z --command bash --interactive`.",
    watchOutFor: "ECS rolling updates use minimumHealthyPercent / maximumPercent. minimum 100 / maximum 200 = always 100% capacity, can briefly burst to 200%. ECS Exec requires SSM agent in the container.",
    doneWhen: "Service scales 2 → 8 tasks under load. Blue/green deploy completes in < 5 min with instant rollback. You've ECS Exec'd into a running task.",
    examTrap: "'Need instant rollback' → blue/green via CodeDeploy. 'Rolling update' = default, slower rollback.",
    realWorld: "Most teams default to rolling deploys (simple, free) and use blue/green for high-stakes services where rollback speed matters (payments, auth).",
    sections: [
      s("autoscaling", "Service Auto Scaling", "config",
        "",
        {
          code: { lang: "bash", source: '# Register as scalable target\naws application-autoscaling register-scalable-target \\\n  --service-namespace ecs \\\n  --resource-id service/prod-cluster/web-app \\\n  --scalable-dimension ecs:service:DesiredCount \\\n  --min-capacity 2 --max-capacity 10\n\n# Target tracking on ALB request count per task\naws application-autoscaling put-scaling-policy \\\n  --service-namespace ecs \\\n  --resource-id service/prod-cluster/web-app \\\n  --scalable-dimension ecs:service:DesiredCount \\\n  --policy-name RequestCountScaling \\\n  --policy-type TargetTrackingScaling \\\n  --target-tracking-scaling-policy-configuration \\\'{"PredefinedMetricSpecification":{"PredefinedMetricType":"ALBRequestCountPerTarget","ResourceLabel":"app/my-alb/abc/targetgroup/my-tg/def"},"TargetValue":1000.0}\\\'' },
        }),
      s("deploy-types", "Deployment types", "compare",
        "",
        {
          table: {
            headers: ["Type", "Mechanism", "Rollback speed"],
            rows: [
              ["Rolling (default)", "Replace tasks gradually", "Slow — needs new deploy"],
              ["Blue/green (CodeDeploy)", "Two target groups, shift traffic", "Instant"],
              ["External", "You drive rollouts", "Yours to define"],
            ],
          },
        }),
      s("exec", "ECS Exec", "concept",
        "`docker exec` for Fargate. Enable on the service (`--enable-execute-command`). The task needs `ssmmessages:*` IAM permissions and the container must have the SSM agent."),
      s("traps", "Exam traps", "trap",
        "**Capacity providers** abstract Fargate / Fargate Spot / EC2. Use Fargate Spot to save 70% on non-prod.\n\n**Sidecar pattern** — second container in the task for logging, service mesh, secrets injection. App Mesh uses Envoy sidecars."),
      s("real", "Real-world — blue/green for payments", "real",
        "High-stakes services (payments, auth) use blue/green for instant rollback. Lower-stakes services use rolling for simplicity."),
    ],
  }),
  lesson({
    day: 27, phase: 2, weekInPhase: 2, phaseProgress: 48,
    topic: "ECR — container registry & image security",
    task: "Enable image scanning on push (basic + Inspector enhanced). Tag immutability. Lifecycle policy: keep last 10 images. Replicate ECR to a DR region.",
    depth: "ECR repos, image scanning (basic + enhanced via Inspector), tag immutability, lifecycle policies, cross-region replication",
    source: "AWS ECR docs · 'Container Image Security' AWS blog",
    examWeight: "MEDIUM — Domain 1 + Domain 2",
    whyMatters: "Container security starts at the registry. Scan on push catches CVEs before deploy. Tag immutability prevents 'someone overwrote prod-v1 with malicious code'. Lifecycle policies prevent storage costs from ballooning over years.",
    howToDoIt: "Enable scan-on-push (free, basic). For continuous scanning + Inspector enhanced findings, enable enhanced scanning. Set tag-immutability = true so the same tag can't be overwritten. Lifecycle policy: 'keep last N images, expire others'. CRR replicates images to a DR region for fast failover.",
    watchOutFor: "Basic scanning (free) gives Clair-based CVE list. Enhanced scanning (Inspector, paid) gives continuous scanning + ECR runtime scan. Lifecycle policies are evaluated on a schedule, not instantly.",
    doneWhen: "Scan results visible on push. Pushing the same tag twice fails. Old images auto-purged.",
    examTrap: "'Container vulnerabilities' → ECR scanning + Inspector. Not GuardDuty (which is for runtime threats), not Macie (which is for S3 data).",
    realWorld: "Production teams gate deploys on scan results: any HIGH/CRITICAL CVE blocks the deploy until patched. Wired into CI/CD.",
    sections: [
      s("scan", "Image scanning", "compare",
        "",
        {
          table: {
            headers: ["Type", "Mechanism", "Cost"],
            rows: [
              ["Basic (default)", "Clair-based, scan-on-push only", "Free"],
              ["Enhanced (Inspector)", "Continuous + runtime, deeper findings", "Per-scan charge"],
            ],
          },
        }),
      s("config", "Set up secure ECR", "config",
        "",
        {
          code: { lang: "bash", source: '# Create repo with tag immutability + scan on push\naws ecr create-repository \\\n  --repository-name my-app \\\n  --image-scanning-configuration scanOnPush=true \\\n  --image-tag-mutability IMMUTABLE\n\n# Lifecycle policy — keep last 10 prod-tagged\ncat > lifecycle.json <<EOF\n{\n  "rules": [{\n    "rulePriority": 1,\n    "selection": {\n      "tagStatus": "tagged",\n      "tagPrefixList": ["prod-"],\n      "countType": "imageCountMoreThan",\n      "countNumber": 10\n    },\n    "action": {"type": "expire"}\n  }]\n}\nEOF\naws ecr put-lifecycle-policy --repository-name my-app \\\n  --lifecycle-policy-text file://lifecycle.json' },
        }),
      s("traps", "Exam traps", "trap",
        "**Tag immutability** prevents overwrite of an existing tag.\n\n**Cross-region replication** for DR — automatic per-region copy.\n\n**ECR private vs public** — use private for production; public is the AWS docker-hub equivalent."),
      s("real", "Real-world — gating deploys on scans", "real",
        "Production teams block the deploy on any HIGH/CRITICAL CVE — wired into CI/CD as a quality gate."),
    ],
  }),
  lesson({
    day: 28, phase: 2, weekInPhase: 3, phaseProgress: 52,
    topic: "EKS — Kubernetes on AWS",
    task: "Spin up an EKS cluster with `eksctl`. Deploy a Helm chart (nginx-ingress). Configure IRSA (IAM Roles for Service Accounts) so pods can assume IAM roles. Run a Fargate profile alongside managed node groups.",
    depth: "EKS control plane, managed node groups, Fargate profiles, IRSA, ALB Ingress Controller",
    source: "AWS EKS docs · eksctl docs · 'EKS Best Practices' AWS",
    examWeight: "HIGH — Domain 2",
    whyMatters: "EKS = managed Kubernetes. Use it when you NEED Kubernetes (multi-cloud portability, existing k8s expertise) or when you're running a complex microservice mesh. Otherwise ECS is simpler. The exam tests when EKS is the right vs wrong answer.",
    howToDoIt: "EKS gives you a managed control plane (API server, etcd, scheduler). You manage worker nodes — managed node groups (AWS auto-patches), self-managed (you patch), or Fargate (serverless pods). IRSA wires k8s service accounts to IAM roles via OIDC — pods get AWS API access without instance profiles.",
    watchOutFor: "EKS has a $0.10/hr cluster fee — adds up across many environments. Fargate on EKS has more limits than ECS Fargate (no DaemonSet, no privileged pods). EKS upgrades are coupled (control plane → nodes); plan them carefully.",
    doneWhen: "kubectl get nodes returns 3 nodes. nginx-ingress is installed via Helm. A pod with IRSA can read S3 without keys.",
    examTrap: "'Containers on AWS' default = ECS Fargate. EKS only when k8s is a hard requirement.",
    realWorld: "Most large enterprises with multi-cloud ambitions or existing k8s skills run EKS. Snap, Stripe, Robinhood all on EKS at scale.",
    sections: [
      s("ecs-vs-eks", "When to pick EKS over ECS", "compare",
        "",
        {
          table: {
            headers: ["Pick EKS if", "Pick ECS if"],
            rows: [
              ["You need Kubernetes-portability (multi-cloud)", "AWS-only is fine"],
              ["Team already runs Kubernetes", "Team is AWS-native"],
              ["You use Helm, Operators, ServiceMesh ecosystem", "Simple containers, AWS integrations"],
              ["You need k8s-specific features (HPA, PDB, CRDs)", "ECS service is enough"],
            ],
          },
        }),
      s("provision", "Provision with eksctl", "config",
        "",
        {
          code: { lang: "bash", source: '# Cluster + 2 managed node groups\neksctl create cluster --name prod \\\n  --region us-east-1 \\\n  --version 1.29 \\\n  --nodegroup-name workers \\\n  --node-type m6g.large \\\n  --nodes 3 --nodes-min 2 --nodes-max 10 \\\n  --managed\n\n# Configure kubectl\naws eks update-kubeconfig --region us-east-1 --name prod\n\n# IAM Roles for Service Accounts (IRSA)\neksctl create iamserviceaccount \\\n  --cluster prod \\\n  --name s3-reader \\\n  --namespace default \\\n  --attach-policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess \\\n  --approve' },
        }),
      s("fargate", "Fargate profile on EKS", "concept",
        "Fargate profiles select pods (by namespace + labels) to run on Fargate instead of nodes. No node management. Higher per-pod cost but zero node ops."),
      s("traps", "Exam traps", "trap",
        "**Cluster fee** $0.10/hr — adds up.\n\n**Fargate-EKS ≠ Fargate-ECS** in feature parity. EKS-Fargate has more limits.\n\n**ALB Ingress Controller** (`aws-load-balancer-controller`) bridges k8s Ingress → ALB.\n\n**IRSA** is the AWS-native way to give pods IAM roles."),
      s("real", "Real-world — EKS at Snap, Stripe, Robinhood", "real",
        "Large-scale multi-cluster k8s. Heavy use of operators, custom resources, service mesh."),
    ],
  }),
  lesson({
    day: 29, phase: 2, weekInPhase: 3, phaseProgress: 56,
    topic: "EKS — networking, scaling, observability",
    task: "Install the AWS VPC CNI (default). Install Karpenter for fast node autoscaling. Install Container Insights (CloudWatch agent + ADOT collector) for metrics & traces.",
    depth: "AWS VPC CNI, Karpenter vs Cluster Autoscaler, HPA, Container Insights, ADOT",
    source: "AWS EKS Best Practices · Karpenter docs",
    examWeight: "MEDIUM — Domain 2 + Domain 5 (Operations)",
    whyMatters: "Karpenter is faster and smarter than Cluster Autoscaler — picks the right instance type per workload. Container Insights gives you CloudWatch metrics for the cluster. ADOT (AWS Distro for OpenTelemetry) ships traces to X-Ray and metrics to CloudWatch.",
    howToDoIt: "AWS VPC CNI gives every pod a real VPC IP — simplifies networking but uses up subnet space (size your subnets accordingly). Karpenter watches for unschedulable pods, provisions just-right nodes via EC2 Fleet. HPA scales pods on CPU/memory/custom metrics. Container Insights is one Helm install.",
    watchOutFor: "AWS VPC CNI: each instance type has a max-pods limit based on ENI count. Karpenter consolidation can be aggressive — tune the disruption settings. ADOT replaces the old separate X-Ray and CloudWatch agents.",
    doneWhen: "A new pod requesting GPU triggers Karpenter to launch a g4dn instance within 60 s. Container Insights shows pod-level CPU/memory in CloudWatch.",
    examTrap: "'Faster pod scaling on EKS' → Karpenter (vs Cluster Autoscaler). 'Container metrics in CloudWatch' → Container Insights.",
    realWorld: "Anthropic, Anyscale, OpenAI use Karpenter to spin up massive GPU fleets in seconds for training jobs. Cost wins are huge — pay for the exact instance type a workload needs.",
    sections: [
      s("cni", "AWS VPC CNI", "concept",
        "Each pod gets a real VPC IP via secondary ENIs on the node. Pros: full VPC integration (Security Groups for pods!), no overlay network. Cons: subnet IP usage. Right-size subnets for max-pod count."),
      s("karpenter", "Karpenter", "concept",
        "Workload-aware autoscaler. Watches for unschedulable pods, picks the right EC2 instance type (CPU, memory, GPU), launches via EC2 Fleet, and consolidates underutilised nodes. Faster (60s vs 3+ min) and more cost-efficient than Cluster Autoscaler."),
      s("observability", "Container Insights + ADOT", "concept",
        "**Container Insights** — CloudWatch agent gathers cluster/pod/node metrics. View as a dashboard.\n\n**ADOT** — AWS Distro for OpenTelemetry. Ships traces to X-Ray and metrics to CloudWatch. Replaces older standalone agents."),
      s("traps", "Exam traps", "trap",
        "**HPA** = horizontal pod autoscaler (scale pods). **Cluster Autoscaler / Karpenter** = scale nodes.\n\n**Security Groups for pods** require AWS VPC CNI + ENI Trunking.\n\n**Container Insights** is the CloudWatch-native way; Prometheus + Grafana is the open way."),
      s("real", "Real-world — GPU at scale", "real",
        "Anthropic / OpenAI use Karpenter for training fleet. Spin up 100s of GPU instances in seconds; pay for exact instance type."),
    ],
  }),
  lesson({
    day: 30, phase: 2, weekInPhase: 3, phaseProgress: 60,
    topic: "EKS — security, GitOps, App Mesh",
    task: "Install ArgoCD for GitOps. Wire it to a git repo of k8s manifests. Push a manifest change; watch ArgoCD sync. Optionally install AWS App Mesh sidecars on a service.",
    depth: "GitOps with ArgoCD/Flux, Pod Security Standards, OPA/Gatekeeper, App Mesh, EKS Pod Identity",
    source: "ArgoCD docs · 'EKS Pod Identity' AWS blog",
    examWeight: "LOW (most exams don't go deep on k8s) but real-world critical",
    whyMatters: "GitOps means git is the source of truth — your cluster matches what's in git, automatically. Pod Security Standards replace deprecated PSPs. App Mesh provides service-mesh capabilities (mTLS, retries, traffic shifting) without code changes.",
    howToDoIt: "ArgoCD: install via Helm; create an Application CRD pointing at your git repo; ArgoCD pulls and syncs every 3 min (configurable). Pod Security Standards: enforce restricted/baseline/privileged at namespace level. App Mesh: install controller + Envoy sidecar; configure VirtualService and VirtualNode CRDs.",
    watchOutFor: "ArgoCD has its own RBAC — auth to ArgoCD ≠ auth to AWS. Pod Security Standards admission can break workloads — start with `audit` mode, move to `enforce`. App Mesh adds Envoy overhead.",
    doneWhen: "Push to git → ArgoCD syncs to cluster within minutes. A privileged pod is rejected by Pod Security Standards.",
    examTrap: "'GitOps' → ArgoCD or Flux. 'Service mesh on AWS' → App Mesh (or Istio if multi-cloud).",
    realWorld: "Most modern k8s shops use GitOps. Cluster state is whatever is in git, period. Drift detection is automatic. PRs against the cluster repo replace direct `kubectl apply`.",
    sections: [
      s("gitops", "GitOps with ArgoCD", "concept",
        "ArgoCD watches a git repo of k8s manifests and reconciles the cluster to match. Out-of-band kubectl changes get reverted (or flagged). All changes are PRs — full audit trail."),
      s("psp", "Pod Security Standards", "concept",
        "Three levels: privileged (everything allowed), baseline (minimal restrictions), restricted (heavily locked down). Applied at namespace level via labels. Replaces deprecated PodSecurityPolicies."),
      s("mesh", "App Mesh", "concept",
        "AWS-managed service mesh. Envoy sidecar in each pod. Provides: mTLS encryption, traffic shifting (canary, blue/green), retries, circuit breakers, observability — without code changes."),
      s("identity", "EKS Pod Identity (newer than IRSA)", "concept",
        "EKS Pod Identity replaces IRSA's OIDC dance with a simpler API. Same idea (pods get IAM roles) with fewer moving parts. Recommended for new clusters."),
      s("traps", "Exam traps", "trap",
        "EKS-specific deep questions are rare on SAA-C03; CKA territory.\n\nKnow that EKS exists, that Fargate works on it, that IRSA gives pods IAM roles, and the ECS-vs-EKS decision tree."),
      s("real", "Real-world — GitOps at scale", "real",
        "Modern k8s shops: cluster state = git. PRs replace direct kubectl. Drift detection is automatic."),
    ],
  }),
  lesson({
    day: 31, phase: 2, weekInPhase: 3, phaseProgress: 64,
    topic: "ElastiCache — Redis (Part 1: caching basics)",
    task: "Provision an ElastiCache Redis cluster with cluster-mode disabled, 1 primary + 2 replicas. Connect from a Lambda. Cache an RDS query result. Measure cache hit ratio.",
    depth: "Redis vs Memcached, cluster mode disabled vs enabled, replication, persistence, eviction policies",
    source: "AWS ElastiCache docs · Redis docs",
    examWeight: "VERY HIGH — Domain 3",
    whyMatters: "Caching is the cheapest performance win in any architecture. Sub-ms reads from in-memory data, taking pressure off RDS. Redis is the default; it has data structures, persistence, pub/sub. Memcached is simpler, multi-threaded, no persistence.",
    howToDoIt: "Pick Redis for almost every case (data types, persistence, replication, pub/sub). Pick Memcached only for simple multi-threaded cache without persistence. Cluster mode disabled = 1 shard, 1 primary + N replicas. Cluster mode enabled = many shards, scales horizontally.",
    watchOutFor: "Eviction policy matters: `allkeys-lru` for cache (drop oldest unused). For session store: persistent storage + don't let it OOM. ElastiCache replicas are async — eventual consistency. AUTH (Redis password) and TLS in-transit are recommended.",
    doneWhen: "Lambda reads from cache, falls back to RDS on miss. Hit ratio > 80% in CloudWatch.",
    examTrap: "'Sub-ms cache for SQL DB' → ElastiCache Redis. 'Microsecond cache for DynamoDB' → DAX. 'Web session store' → Redis (with persistence).",
    realWorld: "Twitter / Pinterest / Snapchat all use Redis to cache hot timelines and feeds. The DB never sees most reads.",
    sections: [
      s("compare", "Redis vs Memcached", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Redis", "Memcached"],
            rows: [
              ["Data types", "Strings, lists, sets, hashes, sorted sets, streams", "Strings only"],
              ["Persistence", "Yes (RDB / AOF)", "No"],
              ["Replication", "Yes (primary + replicas)", "No"],
              ["Pub/sub", "Yes", "No"],
              ["Multi-threaded", "Single (Redis 6+ has threaded I/O)", "Multi-threaded"],
              ["Use case", "Cache, session, leaderboard, queue", "Simple cache, multi-threaded reads"],
            ],
          },
        }),
      s("topology", "Cluster mode disabled vs enabled", "compare",
        "**Disabled** — 1 shard, 1 primary + up to 5 replicas. Use for cache up to ~1 TB. Single endpoint.\n\n**Enabled** — sharded cluster (up to 500 shards), each with its own primary + replicas. Horizontal scaling. Multiple endpoints; client must be cluster-aware."),
      s("aside", "Cache patterns", "concept",
        "**Cache-aside (lazy loading)** — app reads cache; on miss, reads DB and writes to cache.\n**Write-through** — app writes both cache and DB.\n**Write-behind** — app writes cache; cache writes DB asynchronously (risk of loss).\n**Cache-aside with TTL** is the most common."),
      s("project", "Mini-project — Lambda + Redis cache + RDS", "project",
        "",
        {
          code: { lang: "python", source: 'import os, json, redis, psycopg2\n\nr = redis.Redis(host=os.environ["REDIS_HOST"], port=6379, decode_responses=True)\n\ndef lambda_handler(event, context):\n    user_id = event["pathParameters"]["userId"]\n    cache_key = f"user:{user_id}"\n\n    cached = r.get(cache_key)\n    if cached:\n        return {"statusCode": 200, "body": cached, "headers": {"X-Cache": "HIT"}}\n\n    conn = psycopg2.connect(os.environ["DB_URL"])\n    cur = conn.cursor()\n    cur.execute("SELECT id, name, email FROM users WHERE id = %s", (user_id,))\n    row = cur.fetchone()\n    user = {"id": row[0], "name": row[1], "email": row[2]}\n\n    r.setex(cache_key, 300, json.dumps(user))  # 5 min TTL\n    return {"statusCode": 200, "body": json.dumps(user), "headers": {"X-Cache": "MISS"}}' },
        }),
      s("traps", "Exam traps", "trap",
        "**Replicas are ASYNC.** Reads from replicas may be stale.\n\n**Multi-AZ with auto failover** for HA — replicas in other AZs.\n\n**Eviction policy** matters: `allkeys-lru` for cache, `volatile-lru` if you mark some keys persistent."),
      s("real", "Real-world — Twitter timelines", "real",
        "Hot timelines fully cached in Redis. DB sees < 5% of reads. Cache hit ratio > 95%."),
    ],
  }),
  lesson({
    day: 32, phase: 2, weekInPhase: 3, phaseProgress: 68,
    topic: "ElastiCache — Redis advanced (cluster mode, persistence, security)",
    task: "Convert your cluster to cluster mode enabled. Use a cluster-aware Redis client. Test horizontal scaling: add a shard. Enable AUTH + in-transit TLS.",
    depth: "Cluster mode enabled, sharding, resharding, AUTH, TLS, encryption at rest",
    source: "Redis Cluster spec · AWS ElastiCache security docs",
    examWeight: "MEDIUM — Domain 3",
    whyMatters: "At scale, you outgrow a single shard. Cluster mode enabled gets you to 500 shards. AUTH + TLS are mandatory for compliance. Persistence (RDB snapshots) lets you recover from total cluster loss.",
    howToDoIt: "Cluster mode enabled requires a cluster-aware client (`redis-py-cluster`, `ioredis` cluster mode). Keys are hashed to slots; slots are owned by shards. Add a shard → resharding moves slots online (no downtime). AUTH = Redis password. TLS = in-transit encryption to/from cluster.",
    watchOutFor: "Multi-key operations (MGET, MSET, transactions) only work if all keys are in the same hash slot. Use hash tags `{user1}` to force keys into the same slot. Encryption at rest can only be enabled at create time.",
    doneWhen: "Cluster has 3 shards. AUTH + TLS enabled. Resharding completes online.",
    examTrap: "'Multi-key Redis transaction in cluster mode' → keys must be in same hash slot. Use hash tags.",
    realWorld: "Snapchat runs Redis cluster with hundreds of shards. Resharding happens online during organic growth.",
    sections: [
      s("cluster", "Cluster mode enabled", "concept",
        "Keys hashed to 16384 slots; slots are owned by shards. Adding a shard = redistributing slots (online, no downtime). Client must be cluster-aware (talks to multiple endpoints, follows MOVED redirects)."),
      s("hash-tags", "Hash tags for multi-key ops", "config",
        "Multi-key ops (MGET, MSET, transactions, Lua scripts) require all keys in the same slot. Use `{tag}` syntax to force keys to the same slot.",
        {
          code: { lang: "python", source: 'r.mset({\n    "{user1}:profile": "...",\n    "{user1}:orders": "...",\n})  # both keys go to the same slot' },
        }),
      s("security", "AUTH + TLS + at-rest encryption", "config",
        "",
        {
          code: { lang: "bash", source: '# AUTH token\naws elasticache create-replication-group \\\n  --replication-group-id prod-redis \\\n  --replication-group-description "prod" \\\n  --engine redis \\\n  --auth-token "MyStrongAuthToken123!" \\\n  --transit-encryption-enabled \\\n  --at-rest-encryption-enabled \\\n  --kms-key-id alias/aws/elasticache' },
        }),
      s("traps", "Exam traps", "trap",
        "**At-rest encryption can only be enabled at create time.**\n\n**Hash tags** for multi-key ops in cluster mode.\n\n**Persistence**: RDB snapshots (point-in-time) and AOF (append-only log). Use snapshots for ElastiCache; AOF rarely makes sense in managed Redis."),
      s("real", "Real-world — Snapchat Redis", "real",
        "Hundreds of shards. Online resharding during growth. Hash tags ensure friends list operations stay in one shard."),
    ],
  }),
  lesson({
    day: 33, phase: 2, weekInPhase: 3, phaseProgress: 72,
    topic: "ElastiCache — Memcached, MemoryDB, advanced caching patterns",
    task: "Compare Redis vs Memcached vs MemoryDB. Build a cache-aside pattern with TTL + dogpile prevention (lock around DB fetch).",
    depth: "Memcached architecture, MemoryDB (durable Redis-compatible), thundering herd, dogpile mitigation",
    source: "AWS ElastiCache Memcached docs · MemoryDB docs",
    examWeight: "LOW-MEDIUM — Domain 3",
    whyMatters: "Memcached is rare today (Redis ate its lunch). MemoryDB is Redis-compatible but durable (multi-AZ replication for writes — survives node loss). Knowing the differences matters for the exam.",
    howToDoIt: "Memcached: simpler, multi-threaded, no persistence, no replication. Use only when you specifically want multi-threaded simple cache. MemoryDB: durable Redis — writes are persisted to a multi-AZ transaction log. Use when you need Redis-compatible AS A PRIMARY DATABASE (no separate DB needed).",
    watchOutFor: "MemoryDB is more expensive than ElastiCache Redis. Use it only when you genuinely need Redis-as-database. Otherwise, ElastiCache + a separate persistent DB is cheaper.",
    doneWhen: "You can recite which to pick: Redis vs Memcached vs MemoryDB. Your dogpile-prevention code stops 100 concurrent cache misses from becoming 100 RDS hits.",
    examTrap: "'Redis-compatible primary database' = MemoryDB, not ElastiCache.",
    realWorld: "Most teams: ElastiCache Redis for cache, RDS/Aurora for the source of truth. MemoryDB is niche but growing for ultra-low-latency apps where Redis is the only DB.",
    sections: [
      s("trio", "ElastiCache Memcached vs Redis vs MemoryDB", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Memcached", "ElastiCache Redis", "MemoryDB for Redis"],
            rows: [
              ["Persistence", "No", "RDB snapshots (best-effort)", "Multi-AZ durable log"],
              ["Replication", "No", "Async", "Multi-AZ"],
              ["As primary DB?", "No", "Risky (data loss possible)", "Yes — designed for it"],
              ["Cost", "Low", "Medium", "High"],
              ["Use case", "Simple multi-threaded cache", "Cache, session, queue", "Redis as primary DB"],
            ],
          },
        }),
      s("dogpile", "Dogpile / thundering herd mitigation", "config",
        "When a popular key expires, 1000 concurrent requests all miss the cache and hammer the DB. Mitigation: a distributed lock so only one request fetches; others wait.",
        {
          code: { lang: "python", source: 'import time, json\n\ndef get_user(user_id):\n    cache_key = f"user:{user_id}"\n    cached = r.get(cache_key)\n    if cached:\n        return json.loads(cached)\n\n    lock_key = f"lock:{cache_key}"\n    if r.set(lock_key, "1", nx=True, ex=10):  # I won the lock\n        try:\n            user = fetch_from_db(user_id)\n            r.setex(cache_key, 300, json.dumps(user))\n            return user\n        finally:\n            r.delete(lock_key)\n    else:\n        # Someone else is fetching — wait briefly and retry the cache\n        time.sleep(0.05)\n        cached = r.get(cache_key)\n        return json.loads(cached) if cached else fetch_from_db(user_id)' },
        }),
      s("traps", "Exam traps", "trap",
        "**MemoryDB = durable Redis as primary DB.** Different product from ElastiCache.\n\n**Memcached** has no persistence, no replication. Modern teams default to Redis."),
      s("real", "Real-world — Redis as cache, RDS as source of truth", "real",
        "Standard pattern. MemoryDB is niche but growing for ultra-low-latency apps."),
    ],
  }),
  lesson({
    day: 34, phase: 2, weekInPhase: 4, phaseProgress: 80,
    topic: "SQS, SNS & EventBridge — messaging & decoupling",
    task: "Build the SNS fan-out pattern: an S3 upload event → SNS topic → 3 subscribers (SQS for thumbnail, SQS for metadata, Lambda for audit log). Send a test event, watch all 3 fire.",
    depth: "SQS Standard vs FIFO, SNS fan-out, EventBridge content-based routing, DLQs, visibility timeout",
    source: "AWS SQS / SNS / EventBridge docs · 'Messaging Patterns' AWS blog",
    examWeight: "VERY HIGH — Domain 2 + Domain 3",
    whyMatters: "Messaging decouples. Producer pushes a message; consumer pulls when ready. If consumer is down, messages wait. The exam loves the SNS→SQS fan-out pattern: one event, many independent consumers, each at their own pace.",
    howToDoIt: "SQS: producer sends to queue, one consumer per message, message deleted after processing. SNS: pub/sub — one message, many subscribers (SQS, Lambda, HTTP, email, SMS). EventBridge: like SNS but with content-based routing rules — 'fire this Lambda when an EC2 enters terminated state'.",
    watchOutFor: "SQS Standard = at-least-once + best-effort ordering (high throughput). SQS FIFO = exactly-once + strict ordering (300/s default, 3000/s with batching). Visibility timeout: while one consumer holds a message, others can't see it. Set it to ~3× expected processing time.",
    doneWhen: "S3 upload → SNS → 3 fan-out subscribers all process. A failed message goes to a DLQ.",
    examTrap: "'One event triggers multiple independent processors' → SNS → SQS fan-out (NOT EventBridge alone). 'Filter events by content' → EventBridge with rules.",
    realWorld: "Every modern AWS architecture uses SQS for decoupling. Order pipelines: API → SQS → worker Lambda → DynamoDB + downstream services. Failed messages go to DLQ for human inspection.",
    sections: [
      s("trio", "SQS vs SNS vs EventBridge", "compare",
        "",
        {
          table: {
            headers: ["Service", "Pattern", "Use case"],
            rows: [
              ["SQS", "Pull queue (1 consumer per message)", "Decouple producer/consumer"],
              ["SNS", "Pub/sub fan-out (many subscribers)", "Notify multiple consumers"],
              ["EventBridge", "Content-based routing with rules", "Event-driven architecture across AWS + SaaS"],
            ],
          },
        }),
      s("sqs-types", "SQS Standard vs FIFO", "compare",
        "",
        {
          table: {
            headers: ["Feature", "Standard", "FIFO"],
            rows: [
              ["Ordering", "Best-effort", "Strict FIFO"],
              ["Delivery", "At-least-once", "Exactly-once"],
              ["Throughput", "Unlimited", "300/s default, 3000/s with batching"],
              ["Use case", "High throughput, order doesn't matter", "Financial / order-sensitive"],
            ],
          },
        }),
      s("fanout", "SNS fan-out pattern", "config",
        "",
        {
          code: { lang: "bash", source: '# Topic + 2 SQS subs + 1 Lambda sub\naws sns create-topic --name ImageUploaded\n\naws sns subscribe --topic-arn arn:aws:sns:us-east-1:123:ImageUploaded \\\n  --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:123:ThumbnailQueue\n\naws sns subscribe --topic-arn arn:aws:sns:us-east-1:123:ImageUploaded \\\n  --protocol sqs --notification-endpoint arn:aws:sqs:us-east-1:123:MetadataQueue\n\naws sns subscribe --topic-arn arn:aws:sns:us-east-1:123:ImageUploaded \\\n  --protocol lambda --notification-endpoint arn:aws:lambda:us-east-1:123:function:Audit' },
        }),
      s("eventbridge", "EventBridge — content-based routing", "config",
        "",
        {
          code: { lang: "bash", source: '# Rule: trigger Lambda when EC2 enters terminated state\naws events put-rule --name EC2TerminationAlert \\\n  --event-pattern \\\'{"source":["aws.ec2"],"detail-type":["EC2 Instance State-change Notification"],"detail":{"state":["terminated"]}}\\\' \\\n  --state ENABLED\n\naws events put-targets --rule EC2TerminationAlert \\\n  --targets Id=1,Arn=arn:aws:lambda:us-east-1:123:function:Alert' },
        }),
      s("traps", "Exam traps", "trap",
        "**Visibility timeout** — message invisible to other consumers while one is processing. Default 30 s; tune to ~3× processing time.\n\n**DLQ (Dead Letter Queue)** — messages that fail N times go here for inspection. Always set one in production.\n\n**SNS → SQS fan-out** is the textbook pattern.\n\n**EventBridge schema registry** + content-based routing is the modern event bus."),
      s("real", "Real-world — order pipelines", "real",
        "API → SQS → worker Lambda → DynamoDB + Stripe + email. Failed messages → DLQ. Decoupled, scales independently."),
    ],
  }),
  capstone(35, 2, 4, 100,
    "Phase 2 capstone — Three-Tier App",
    "Deploy the Three-Tier Production Web App capstone: React → S3+CloudFront, Node.js → ECS Fargate behind ALB, Aurora Postgres Multi-AZ, ElastiCache Redis. Wire CI/CD via GitHub Actions, CloudWatch dashboard + alarms, WAF on the edge."),
];
