import type { AwsDay } from "@/types";
import { s, lesson } from "./section-helpers";

// PHASE 7 — EXAM PREP (Days 83–90)
export const PHASE_7: AwsDay[] = [
  lesson({
    day: 83, phase: 7, weekInPhase: 1, phaseProgress: 12,
    topic: "Domain 1 deep-dive — Design Secure Architectures (30%)",
    task: "Review every Domain 1 topic: IAM, KMS, Secrets Manager, WAF, Shield, Cognito, Identity Center, GuardDuty, Macie, Inspector, Security Hub, Config, CloudTrail. Take 20 practice questions on Domain 1.",
    depth: "Domain 1 service map + common exam patterns",
    source: "Tutorial Dojo Domain 1 sets · Stephane Maarek practice tests · AWS sample questions",
    examWeight: "30% — biggest single domain",
    whyMatters: "30% of the exam = 20 of your 65 questions. Master this domain and you can lose another domain entirely and still pass. Most questions are scenario-based — read carefully for keywords like 'least privilege', 'encrypt at rest', 'in-transit', 'audit'.",
    howToDoIt: "Re-read Phase 1 (IAM/VPC) + Phase 4 (Security). Hit a practice question set under timed conditions. For every wrong answer, write down WHY the right answer is right and WHY each wrong one is wrong. Drill the patterns: 'EC2 + S3' → instance role. 'rotate password automatically' → Secrets Manager. 'encrypt at rest in S3' → SSE-KMS via bucket policy deny.",
    watchOutFor: "Easy to confuse: WAF vs Shield (WAF = L7 rules, Shield = DDoS). Macie vs Inspector vs GuardDuty (Macie = S3 PII, Inspector = CVEs, GuardDuty = threats). Identity Center vs Cognito (engineers vs end users).",
    doneWhen: "You score > 75% on 20 Domain 1 practice questions. You can explain every wrong answer.",
    examTrap: "Most-correct, not first-correct. 'Manage AWS access for 500 engineers across 50 accounts' = IAM Identity Center, NOT IAM users.",
    realWorld: "This domain mirrors real production security architecture. If you can pass it, you can pass a real-world AWS security review.",
    sections: [
      s("service-map", "Domain 1 service map", "concept",
        "Identity: IAM, Identity Center, Cognito, STS, Organizations.\n\nEncryption: KMS, CloudHSM, Secrets Manager, SSM Parameter Store, ACM, S3 SSE.\n\nNetwork edge: WAF, Shield (Std + Adv), Firewall Manager, Network Firewall.\n\nThreat / posture: GuardDuty, Macie, Inspector, Security Hub, Detective, Config.\n\nAudit: CloudTrail, Config history, S3 server access logs, VPC Flow Logs."),
      s("patterns", "Common exam patterns", "concept",
        "• 'EC2 needs S3 access' → Instance Profile / IAM Role, NEVER access keys.\n• 'Encrypt all uploads' → S3 default encryption + bucket policy Deny if header missing.\n• 'Audit every API call across the org' → multi-region multi-account CloudTrail to a hardened logging account.\n• 'Detect public S3 buckets' → Config rule + Security Hub.\n• 'End-user sign-in' → Cognito User Pool.\n• 'Engineer access to many accounts' → IAM Identity Center federated to Okta/Azure AD."),
      s("traps", "Trap collection", "trap",
        "**Explicit Deny always wins** — order: Deny → Allow → Implicit Deny.\n\n**S3 bucket policy vs IAM policy** — both apply; explicit Deny in either blocks.\n\n**KMS Key Policy is mandatory** — IAM alone is not enough.\n\n**MFA on root is the FIRST step** in a new account.\n\n**Multi-region trail captures every region** in one trail."),
    ],
  }),
  lesson({
    day: 84, phase: 7, weekInPhase: 1, phaseProgress: 25,
    topic: "Domain 2 deep-dive — Design Resilient Architectures (26%)",
    task: "Review Domain 2: Multi-AZ, ASG, ELB, Route 53 routing policies, RDS/Aurora replication, DR strategies, AWS Backup, multi-region patterns. Take 20 practice questions.",
    depth: "Domain 2 service map + RTO/RPO mental model",
    source: "Tutorial Dojo Domain 2 sets · AWS Well-Architected Reliability Pillar",
    examWeight: "26% — second-biggest",
    whyMatters: "26% of the exam. The mental model: every layer of the stack must survive single-component failure (HA) and the whole region (DR). Memorise the 4 DR strategies + their RTO/RPO.",
    howToDoIt: "Re-read Phase 6 (HA + DR). Practice the routing policies — every one of the 7. Drill the RTO/RPO map. For multi-region: which services replicate natively (Aurora Global, DynamoDB Global Tables, S3 CRR) and which require manual scripting.",
    watchOutFor: "RDS Multi-AZ is HA WITHIN a region (different AZ). Read Replica is for read scaling, not HA. Cross-region Read Replica adds DR. Aurora Global DB is the cross-region equivalent.",
    doneWhen: "You score > 75% on 20 Domain 2 questions. You can sketch any of the 4 DR strategies on a whiteboard from memory.",
    examTrap: "'High availability' = within-region multi-AZ. 'Disaster recovery' = cross-region. Read the question for which they're asking.",
    realWorld: "Domain 2 questions map directly to real production work. Every senior architect goes through this analysis on every system.",
    sections: [
      s("service-map", "Domain 2 service map", "concept",
        "Compute HA: Auto Scaling Groups (multi-AZ), ALB / NLB.\n\nData HA: RDS Multi-AZ, Aurora cluster, ElastiCache replicas, DynamoDB global tables, S3 (built-in 3-AZ).\n\nDNS: Route 53 health checks + failover routing.\n\nDR: AWS Backup, Aurora Global DB, S3 CRR, multi-region StackSets.\n\nGlobal: CloudFront, Global Accelerator."),
      s("rto-rpo-map", "RTO/RPO cheat sheet", "compare",
        "",
        {
          table: {
            headers: ["Strategy", "RTO", "RPO", "Cost"],
            rows: [
              ["Backup & Restore", "Hours", "Hours", "$"],
              ["Pilot Light", "Minutes-tens", "Minutes", "$$"],
              ["Warm Standby", "Minutes single-digit", "Seconds", "$$$"],
              ["Multi-Site Active-Active", "Seconds", "Near-zero", "$$$$"],
            ],
          },
        }),
      s("routing-7", "Route 53 7 routing policies", "concept",
        "Simple, Weighted (A/B), Latency (closest region), Failover (active-passive DR), Geolocation (country), Geoproximity (distance with bias), Multi-Value Answer (client-side LB)."),
      s("traps", "Trap collection", "trap",
        "**Multi-AZ = within region.** Region outage requires DR.\n\n**Read Replica vs Multi-AZ** — Replica is for read scaling, Multi-AZ for HA failover.\n\n**Aurora Global DB ≠ cross-region Read Replica** — different products.\n\n**Route 53 failover needs health checks** to flip."),
    ],
  }),
  lesson({
    day: 85, phase: 7, weekInPhase: 1, phaseProgress: 38,
    topic: "Domain 3 deep-dive — High-Performing (24%) + Domain 4 — Cost (20%)",
    task: "Review Domain 3 (CloudFront, caching, picking the right DB) and Domain 4 (Savings Plans, Spot, S3 classes, right-sizing). Take 20 questions across both.",
    depth: "Service-fit decisions + cost tactics",
    source: "Tutorial Dojo Domain 3 + Domain 4 sets",
    examWeight: "24% + 20% = 44% combined",
    whyMatters: "44% of the exam between these two. Domain 3 is service-fit decisions (right tool for the job). Domain 4 is cost — commitment vehicles, storage tiers, idle resources.",
    howToDoIt: "Drill the decision flowcharts: relational DB vs DynamoDB; Lambda vs ECS vs EC2; SQS vs SNS vs EventBridge; CloudFront vs Global Accelerator. Memorise S3 storage classes + retrieval times. Memorise Savings Plans tiers + Spot use cases.",
    watchOutFor: "Domain 3 traps: DAX (DynamoDB) vs ElastiCache (general). Domain 4 traps: Compute SP (flexible) vs RI (specific). Spot vs On-Demand — Spot only for fault-tolerant.",
    doneWhen: "You score > 75% across both domains.",
    examTrap: "'Most cost-effective WITHOUT performance loss' = right-size first + Savings Plans, NOT Spot (Spot = perf risk).",
    realWorld: "These two domains drive most FinOps and SRE decisions in real production.",
    sections: [
      s("service-fit", "Decision flowcharts", "concept",
        "**Compute**: Event-driven < 15min → Lambda. Containers → ECS Fargate. K8s required → EKS. Long-running custom → EC2.\n\n**Database**: Simple KV at scale → DynamoDB. SQL with joins → RDS / Aurora. Analytics → Redshift. Time-series → Timestream. Graph → Neptune. Search → OpenSearch.\n\n**Caching**: Edge → CloudFront. App tier → ElastiCache Redis. DynamoDB → DAX.\n\n**Messaging**: Queue (1 consumer/msg) → SQS. Fan-out → SNS → SQS. Content-based routing → EventBridge."),
      s("storage-classes", "S3 classes by access pattern", "compare",
        "",
        {
          table: {
            headers: ["Pattern", "Class"],
            rows: [
              ["Frequently accessed", "Standard"],
              ["Unknown / shifting", "Intelligent-Tiering"],
              ["Infrequent rapid", "Standard-IA"],
              ["Infrequent recreatable", "One Zone-IA"],
              ["Archive quarterly", "Glacier Instant"],
              ["Archive 1-12hr OK", "Glacier Flexible"],
              ["Archive 12-48hr OK", "Glacier Deep Archive"],
            ],
          },
        }),
      s("savings-stack", "Savings stack", "concept",
        "1. Right-size (Compute Optimizer) — free 20-50%.\n2. Compute Savings Plans for baseline — ~66% off.\n3. Spot for fault-tolerant — ~90% off.\n4. Graviton swap — additional ~20% off."),
      s("traps", "Trap collection", "trap",
        "**Spot ≠ default.** Only fault-tolerant workloads.\n\n**Compute SP > RI** for new commitments — more flexible.\n\n**Intelligent-Tiering** for unknown access; lifecycle for known.\n\n**CloudFront** caches; **Global Accelerator** routes (different).\n\n**DAX** only for DynamoDB; ElastiCache for everything else."),
    ],
  }),
  lesson({
    day: 86, phase: 7, weekInPhase: 2, phaseProgress: 50,
    topic: "Practice exam #1 — full timed run",
    task: "Take a full 65-question practice exam under exam conditions (130 min, no breaks, no notes). Score it. Mark every wrong question.",
    depth: "Timed exam practice — pacing, flagging, eliminating wrong answers",
    source: "Tutorial Dojo timed mode · AWS official sample exam · Stephane Maarek",
    examWeight: "Entire exam scope",
    whyMatters: "Practice exams are the single best predictor of pass/fail. The first one usually under-scores — that's normal. The goal isn't perfection on attempt 1; it's identifying knowledge gaps to drill.",
    howToDoIt: "Block 2.5 hours. No phone, no notes, single window. Flag any question you're not 100% on. Finish all 65. Then score. For every wrong answer: read the explanation, identify the concept, add it to a 'weak areas' list.",
    watchOutFor: "Don't memorise practice exam answers — the real exam will rephrase. Memorise the CONCEPTS that drove the right answers.",
    doneWhen: "Full practice exam completed under time. Score + weak-area list compiled.",
    examTrap: "Pacing: 65 questions / 130 min = 2 min per question. Don't get stuck — flag and move on.",
    realWorld: "Aim for > 80% on practice exams before attempting the real one. 720/1000 = 72% pass, but practice exams tend to be harder.",
    sections: [
      s("pacing", "Pacing", "concept",
        "65 questions / 130 minutes = exactly 2 minutes per question. First pass: 90 min answering all easy, flagging hard. Second pass: 40 min on flagged. Final 10 min: review flagged + first-instinct check."),
      s("read", "How to read a question", "concept",
        "1. Underline the constraint keywords: 'most cost-effective', 'minimal downtime', 'least operational overhead', 'no code changes', 'within current region'.\n2. Eliminate answers that violate the constraint, even if they technically work.\n3. Pick the AWS-preferred answer: managed > self-managed, automation > manual, least privilege > broad."),
      s("flag", "Flag-and-move", "concept",
        "If you've spent > 90 seconds on one question, flag it and move on. Come back at the end. You'll often see a hint in a later question."),
      s("traps", "Common traps to watch for", "trap",
        "**'MOST'** keyword — there will often be 2 right answers; one is more right.\n\n**'Least operational overhead'** = AWS-managed service.\n\n**'No code changes'** = managed integration, not custom Lambda.\n\n**'Existing on-prem'** = hybrid pattern (Storage Gateway, DX, VPN)."),
    ],
  }),
  lesson({
    day: 87, phase: 7, weekInPhase: 2, phaseProgress: 62,
    topic: "Practice exam #1 review + weak-area drill",
    task: "Spend a full day on yesterday's wrong answers. For each: re-read the relevant day in this roadmap; rewatch any video; do a hands-on lab if possible.",
    depth: "Closing knowledge gaps",
    source: "Yesterday's practice exam explanations",
    examWeight: "Whatever you got wrong",
    whyMatters: "The wrong answers from practice exams ARE your study plan now. Don't read the right ones — focus 100% on the wrong ones. That's where the points live.",
    howToDoIt: "For each wrong question: (1) read AWS's explanation in the practice tool, (2) revisit the relevant phase day in this roadmap, (3) optionally do a 15-min hands-on lab to make the concept stick, (4) write one sentence summarising the rule.",
    watchOutFor: "If you got > 10 wrong in one domain, slow down — don't move on. Re-read the whole phase before attempting another practice exam.",
    doneWhen: "Every wrong answer turned into a one-sentence rule in your notes. Concepts you couldn't articulate become concepts you can teach.",
    examTrap: "Same trap can appear with different services. 'Encrypt at rest' applies equally to S3, EBS, RDS, DynamoDB.",
    realWorld: "This is the actual learning step. Mock exams without serious gap closure = wasted time.",
    sections: [
      s("process", "Gap-closure process", "concept",
        "1. List every wrong question + the rule that would have got it right.\n2. Group by domain + service.\n3. Re-read the relevant roadmap day.\n4. Do a 15-min lab to internalise.\n5. Articulate the rule in your own words."),
      s("traps", "Stay self-honest", "trap",
        "If your notes say 'I should have known this' — you didn't. Add it to the weak-area list. Honesty here = pass on the real exam."),
    ],
  }),
  lesson({
    day: 88, phase: 7, weekInPhase: 2, phaseProgress: 75,
    topic: "Practice exam #2 — measure improvement",
    task: "Take a SECOND full practice exam (different question set). Score. Compare to #1. Verify improvement on weak areas.",
    depth: "Measuring readiness",
    source: "Different provider than yesterday (Tutorial Dojo / Stephane Maarek / Whizlabs / AWS official)",
    examWeight: "Full scope",
    whyMatters: "Practice exam #2 measures whether your study plan is working. If you've gone from 65 → 80%, you're on track. If 65 → 67%, the gap closure didn't stick — slow down before #3.",
    howToDoIt: "Same timed conditions as #1. Different provider or different set. Score, identify remaining weak areas, repeat the gap-closure process.",
    watchOutFor: "Tutorial Dojo runs harder than the real exam — 78% on TD ≈ 85% on real. Stephane Maarek is closer to real difficulty. AWS official sample is easiest.",
    doneWhen: "Score > 80% (or you have a clear remaining list to drill).",
    examTrap: "Don't memorise — concepts.",
    realWorld: "Pass two consecutive practice exams > 80% = high-confidence ready to book real exam.",
    sections: [
      s("compare", "Compare attempt 1 vs 2", "concept",
        "Track per-domain scores. If Domain 1 went 60 → 80%, your study worked. If it went 60 → 62%, you didn't internalise — go back."),
      s("readiness", "Readiness signals", "concept",
        "Ready: two consecutive practice exams > 80%, weak-area list shrinking, you can articulate why wrong answers are wrong without checking.\n\nNot ready: practice scores plateau below 75%, weak areas keep repeating, you're memorising answers instead of concepts."),
    ],
  }),
  lesson({
    day: 89, phase: 7, weekInPhase: 2, phaseProgress: 88,
    topic: "Final review + exam day logistics",
    task: "Skim every weak-area note one more time. Book the exam (PSI online proctored or test centre). Read the candidate handbook. Verify ID, room, internet.",
    depth: "Final consolidation + logistics",
    source: "AWS Certification candidate guide",
    examWeight: "Logistics",
    whyMatters: "A test-centre fail because your ID was wrong, or an online proctor fail because your room failed, wastes $300 and a week. Logistics matters.",
    howToDoIt: "Book exam in advance — pick test centre or online proctored (PSI). Online: clean room, single monitor, government ID matching name on AWS account exactly, stable internet, no headphones, no phone in room. Test centre: arrive 30 min early.",
    watchOutFor: "Online proctor will scan the room — clear everything off the desk. Name on ID MUST match name on Pearson VUE/PSI account exactly. Spelling, suffix, everything.",
    doneWhen: "Exam booked. ID confirmed. Room / centre prepared.",
    examTrap: "Don't drink a litre of water 30 min before — bathroom breaks aren't allowed in online proctored.",
    realWorld: "Stories of $300 fails for logistics are common. 15 minutes of prep avoids it.",
    sections: [
      s("options", "Test centre vs online proctored", "compare",
        "",
        {
          table: {
            headers: ["Option", "Pros", "Cons"],
            rows: [
              ["Test centre", "No room scan, no proctor stress, single proven environment", "Travel, fixed times"],
              ["Online (PSI)", "Take from home, flexible times", "Room scan, can be flaky"],
            ],
          },
        }),
      s("checklist", "Pre-exam checklist", "concept",
        "Government ID matches name exactly. Stable internet (test it). Clean desk — only computer, mouse, keyboard, water in clear container. Bathroom before. Phone off + out of room. Backup ID just in case."),
      s("traps", "Logistics traps", "trap",
        "**Name mismatch** = no entry, no refund.\n\n**Phone in the room** = automatic disqualification.\n\n**Second monitor connected** = disqualification.\n\n**Background noise** (kids, pets) = paused exam, time lost."),
    ],
  }),
  lesson({
    day: 90, phase: 7, weekInPhase: 2, phaseProgress: 100,
    topic: "EXAM DAY — execute the plan",
    task: "Take the SAA-C03 exam. Pass. Update your LinkedIn.",
    depth: "Execute",
    source: "Everything in this roadmap",
    examWeight: "100%",
    whyMatters: "90 days of work culminate here. The plan is: stay calm, pace, flag, eliminate, pick the AWS-preferred answer when in doubt. Trust the prep.",
    howToDoIt: "Sleep well the night before. Light breakfast. Arrive / log in 30 minutes early. Read each question twice. Underline the constraint mentally. Eliminate 2 wrong answers. Pick the AWS-preferred of the remaining 2. Flag anything taking > 90 s. Use the full 130 minutes. Review all flagged before submitting.",
    watchOutFor: "Pacing — 2 min per question. Don't second-guess after the second pass; first-instinct is usually right unless you have a specific reason. Don't leave blanks — there's no penalty for wrong.",
    doneWhen: "PASS. Schedule a celebration.",
    examTrap: "Anxiety is normal. Breathe. The exam is exactly what you prepped for.",
    realWorld: "After passing: update LinkedIn, share with your team, push for that promotion. SAA-C03 unlocks senior roles, opens doors to Solutions Architect Pro and specialty certs.",
    sections: [
      s("exec", "Exam day playbook", "concept",
        "1. Sleep 7-8 hr.\n2. Eat light, hydrate moderate.\n3. Log in / arrive 30 min early.\n4. Read every question twice; underline constraints.\n5. First pass: answer 50 easy / flag 15 hard.\n6. Second pass: hit flagged with the time you saved.\n7. Final 10 min: re-check flagged, don't change correct first-instinct without strong reason.\n8. Submit when confident."),
      s("decision", "Decision rule under uncertainty", "concept",
        "When stuck between two answers:\n• Pick the AWS-managed service over self-managed.\n• Pick automation over manual process.\n• Pick least privilege over broad permissions.\n• Pick the option that mentions specific AWS features over generic language.\n• Pick the simpler design when 'least operational overhead' is the constraint."),
      s("after", "After PASS", "real",
        "Update LinkedIn + resume. Add the digital badge. Tell your manager. Update your team's wiki. Start thinking about: Solutions Architect Professional (SAP-C02), Security Specialty, DevOps Pro — they all build on this foundation. You're now a certified AWS Solutions Architect Associate."),
    ],
  }),
];
