import type { AwsDay } from "@/types";
import { s, lesson, review } from "./section-helpers";

// PHASE 5 — OPERATIONS & MONITORING (Days 61–72)
export const PHASE_5: AwsDay[] = [
  lesson({
    day: 61, phase: 5, weekInPhase: 1, phaseProgress: 8,
    topic: "CloudWatch — metrics, alarms, dashboards",
    task: "Create a CloudWatch alarm on EC2 CPU > 80% for 2 evaluation periods. Wire to SNS. Push a custom metric from your app (e.g., OrdersProcessed). Build a dashboard with 4 widgets.",
    depth: "Metrics (standard + custom), alarms (static + anomaly detection), composite alarms, dashboards, namespaces, dimensions",
    source: "AWS CloudWatch docs",
    examWeight: "VERY HIGH — Domain 5 (Operations)",
    whyMatters: "Without CloudWatch you're flying blind. It's the central observability service for AWS — metrics from every service, alarms that trigger SNS / Auto Scaling / Lambda, dashboards for humans. Knowing how to set up alarms and which metrics need the CloudWatch Agent is direct exam money.",
    howToDoIt: "Standard metrics are free (1-minute or 5-minute granularity depending on service). Custom metrics via `put-metric-data` cost per metric. Alarms compare a metric against a threshold over N evaluation periods; trigger actions on state change. Composite alarms combine multiple alarms with AND/OR logic.",
    watchOutFor: "EC2 default metrics DON'T include memory or disk — those require the CloudWatch Agent. Standard resolution metrics are 1-minute; high-res are 1-second (more expensive). Alarm 'evaluation periods' multiplies the period — a 5-min period with 3 eval periods = 15 min before alarm.",
    doneWhen: "Alarm fires SNS on > 80% CPU. Custom metric visible. Dashboard shows CPU, requests, errors, latency.",
    examTrap: "'Memory metric for EC2' → install CloudWatch Agent. 'Auto-scaling on memory' → custom metric → CloudWatch Agent → ASG target tracking.",
    realWorld: "Every production AWS service has a CloudWatch dashboard. On-call runbooks open the dashboard first. Alarms route to PagerDuty via SNS.",
    sections: [
      s("intro", "What CloudWatch covers", "intro",
        "CloudWatch is three things in one: metrics (numbers over time), logs (text events), and events (now EventBridge). Plus alarms (act on metrics), dashboards (visualise), and Synthetics (canary HTTP probes)."),
      s("alarm", "Create an alarm", "config",
        "",
        {
          code: { lang: "bash", source: '# CPU > 80% for 2 evaluation periods of 5 min each\naws cloudwatch put-metric-alarm \\\n  --alarm-name HighCPU-WebServer \\\n  --metric-name CPUUtilization \\\n  --namespace AWS/EC2 \\\n  --dimensions Name=InstanceId,Value=i-0abc \\\n  --statistic Average \\\n  --period 300 \\\n  --evaluation-periods 2 \\\n  --threshold 80 \\\n  --comparison-operator GreaterThanThreshold \\\n  --alarm-actions arn:aws:sns:us-east-1:123:AlertTeam \\\n  --ok-actions arn:aws:sns:us-east-1:123:AlertTeam \\\n  --treat-missing-data breaching' },
        }),
      s("custom", "Custom metrics", "config",
        "",
        {
          code: { lang: "bash", source: '# Push from your app\naws cloudwatch put-metric-data \\\n  --namespace MyApp/Performance \\\n  --metric-name OrdersProcessed \\\n  --value 42 \\\n  --unit Count \\\n  --dimensions Environment=Production,Service=OrderService' },
        }),
      s("traps", "Exam traps", "trap",
        "**EC2 memory/disk needs the CloudWatch Agent.** Default = CPU, network, EBS I/O only.\n\n**Anomaly detection** vs static threshold — anomaly auto-learns the normal band.\n\n**Composite alarms** combine multiple alarms — reduce alert noise.\n\n**Cross-account / cross-region dashboards** for org-wide views."),
      s("real", "Real-world — on-call runbooks", "real",
        "Every prod service has a dashboard. Alarms → PagerDuty → on-call. First step in incident response: open the dashboard."),
    ],
  }),
  lesson({
    day: 62, phase: 5, weekInPhase: 1, phaseProgress: 16,
    topic: "CloudWatch Logs & Logs Insights",
    task: "Ship application logs to CloudWatch Logs via the agent. Run a Logs Insights query to find all 5xx errors in the last hour. Set up a metric filter that turns log patterns into a metric + alarm.",
    depth: "Log groups, streams, retention, metric filters, Logs Insights queries, subscriptions",
    source: "CloudWatch Logs Insights docs",
    examWeight: "HIGH — Domain 5",
    whyMatters: "Logs in CloudWatch are searchable, queryable (Logs Insights), and can be turned into metrics (metric filters) and alarms. Subscriptions stream logs in real time to Lambda, Kinesis, or Firehose for further processing.",
    howToDoIt: "Install CloudWatch Agent on EC2; configure log file paths. ECS Fargate / Lambda: built-in awslogs driver / automatic logging. Use Logs Insights to query in SQL-like syntax. Metric filters turn log patterns into metrics (e.g., count of '5xx' in nginx logs). Subscriptions push to downstream consumers.",
    watchOutFor: "Default retention is FOREVER — set retention on every log group (cost). Logs Insights charges per GB scanned. Pre-filter by time + log stream before counting.",
    doneWhen: "App logs visible in CloudWatch. Insights query returns 5xx count. Metric filter creates a metric → alarm fires on > 10 errors / 5 min.",
    examTrap: "'Real-time log streaming to Splunk / Elasticsearch' = CloudWatch Logs Subscription → Kinesis Firehose → destination.",
    realWorld: "Logs Insights replaced grep for most teams. Common queries (slow Lambdas, 5xx spikes, auth failures) live as saved queries.",
    sections: [
      s("agent", "CloudWatch Agent", "config",
        "",
        {
          code: { lang: "bash", source: 'sudo yum install -y amazon-cloudwatch-agent\n\ncat > /opt/aws/amazon-cloudwatch-agent/etc/config.json <<EOF\n{\n  "metrics": {\n    "metrics_collected": {\n      "mem": {"measurement": ["mem_used_percent"]},\n      "disk": {"measurement": ["disk_used_percent"], "resources": ["/"]}\n    }\n  },\n  "logs": {\n    "logs_collected": {\n      "files": {\n        "collect_list": [{\n          "file_path": "/var/log/myapp/*.log",\n          "log_group_name": "/ec2/myapp",\n          "log_stream_name": "{instance_id}"\n        }]\n      }\n    }\n  }\n}\nEOF\n\nsudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \\\n  -a fetch-config -m ec2 \\\n  -s -c file:/opt/aws/amazon-cloudwatch-agent/etc/config.json' },
        }),
      s("insights", "Logs Insights queries", "config",
        "",
        {
          code: { lang: "sql", source: '# 5xx errors in last hour grouped by 5-min buckets\nfields @timestamp, @message, @logStream\n| filter @message like /5[0-9][0-9]/\n| stats count() as errorCount by bin(5m)\n| sort errorCount desc\n\n# Lambda cold starts in last 24h\nfields @timestamp, @duration, @initDuration\n| filter @type = "REPORT" and ispresent(@initDuration)\n| stats count() as coldStarts, avg(@initDuration) as avgInitMs\n\n# Top 10 slowest Lambda invocations\nfields @timestamp, @requestId, @duration\n| filter @type = "REPORT"\n| sort @duration desc\n| limit 10' },
        }),
      s("traps", "Exam traps", "trap",
        "**Default retention = forever.** Set 7/14/30/90 days per log group.\n\n**Metric filter** converts log pattern → metric → alarm.\n\n**Subscription filter** streams to Lambda / Kinesis / Firehose for downstream (Splunk, OpenSearch)."),
      s("real", "Real-world — Logs Insights as grep replacement", "real",
        "Saved queries: 'slow Lambda invocations', '5xx by endpoint', 'auth failures by user'. Live searchable across log groups and accounts."),
    ],
  }),
  lesson({
    day: 63, phase: 5, weekInPhase: 1, phaseProgress: 24,
    topic: "CloudWatch — Synthetics, RUM, X-Ray, Container Insights",
    task: "Create a CloudWatch Synthetics canary that hits your homepage every 5 min. Enable X-Ray on your Lambda — trace a full request through API GW → Lambda → DynamoDB.",
    depth: "Synthetics canaries, RUM (real user monitoring), X-Ray tracing, Container Insights, ServiceLens",
    source: "AWS CloudWatch Synthetics + X-Ray docs",
    examWeight: "MEDIUM — Domain 5",
    whyMatters: "Synthetics canaries detect outages before users do. X-Ray shows request flow across microservices — finds the slow link. RUM captures real-user perf metrics from browsers. Container Insights gives you per-pod CloudWatch metrics on ECS / EKS.",
    howToDoIt: "Synthetics: a scheduled Lambda script (Node.js Puppeteer or Python Selenium) that hits your site and asserts. RUM: snippet in your JS that ships browser metrics. X-Ray: enable on Lambda (`TracingConfig: Active`); SDK auto-instruments common libs. Container Insights: enable when creating the ECS cluster.",
    watchOutFor: "Synthetics costs per canary-minute + per data point. X-Ray adds ~5% latency but invaluable for debugging distributed systems. RUM cost scales with sessions.",
    doneWhen: "Canary alerts via SNS on failure. X-Ray service map shows the trace. Container Insights dashboard live.",
    examTrap: "'Detect outage before users' = Synthetics. 'Trace request across services' = X-Ray. 'Browser perf metrics' = RUM.",
    realWorld: "SREs check Synthetics first. X-Ray is the go-to during 'why is this slow?' investigations. RUM informs frontend optimisations.",
    sections: [
      s("canaries", "Synthetics canaries", "concept",
        "Scheduled scripts (every 1/5/15 min) that hit your endpoint and assert. Alarm on failure. Bonus: visual diffing (screenshot regressions). Replaces Pingdom/StatusCake for AWS-native shops."),
      s("xray", "X-Ray", "concept",
        "Distributed tracing. Every Lambda / ECS service emits trace segments; X-Ray stitches them into a service map. Find: slow downstream calls, cascading failures, retry storms. Sample rate configurable to control cost."),
      s("traps", "Exam traps", "trap",
        "**Synthetics for proactive uptime check.** Doesn't replace alarms — augments.\n\n**X-Ray needs IAM role permission** + SDK instrumentation (auto for boto3, fetch, etc.).\n\n**ADOT** (OpenTelemetry distro) is the modern way for cross-platform tracing."),
      s("real", "Real-world — debug a slow API", "real",
        "X-Ray service map shows API GW → Lambda → DynamoDB (50ms) → external Stripe API (3 s). External call is the culprit."),
    ],
  }),
  lesson({
    day: 64, phase: 5, weekInPhase: 2, phaseProgress: 32,
    topic: "CloudTrail — audit logs for every API call",
    task: "Confirm CloudTrail is logging in every region. Create a multi-region trail with log file integrity validation, ship to S3 + CloudWatch Logs. Look up the exact API call that created an EC2 instance yesterday.",
    depth: "Management events, data events, insights events, multi-region trail, log file integrity, organization trail",
    source: "AWS CloudTrail docs",
    examWeight: "VERY HIGH — Domain 1 + Domain 5",
    whyMatters: "CloudTrail is the audit log — every API call (console, CLI, SDK, service-to-service) gets recorded. Required for compliance (SOC2, PCI, HIPAA, FedRAMP). Combined with S3 + Athena, you can query 'who did what when' across years of history.",
    howToDoIt: "Default trail captures Management Events for 90 days at no cost. For long-term + data events + organization-wide, create a multi-region trail to S3. Enable Log File Integrity Validation (SHA-256 + RSA signatures). Wire to CloudWatch Logs for real-time alerting. For Organizations, create an Organization Trail in the management account.",
    watchOutFor: "Data Events (S3 object reads, Lambda invokes) cost extra and produce huge volumes — filter by bucket/function. Insights Events detect unusual API patterns (paid). S3 bucket holding CloudTrail must have strict bucket policy + Object Lock.",
    doneWhen: "Multi-region org trail to S3. Athena queries find the EC2 launch. Integrity validation runs without errors.",
    examTrap: "'Who did what when' = CloudTrail. 'Resource configuration change' = Config (Config tracks state; CloudTrail tracks API calls).",
    realWorld: "Every AWS account in every regulated industry has org-wide CloudTrail to a hardened logging account. Athena + CloudTrail logs = incident-response gold.",
    sections: [
      s("event-types", "Event types", "compare",
        "",
        {
          table: {
            headers: ["Type", "What it captures", "Cost"],
            rows: [
              ["Management Events", "API calls that manage resources (CreateBucket, RunInstances)", "Free for 90 days, then per-trail"],
              ["Data Events", "Object-level activity (S3 GetObject, Lambda Invoke)", "Per event (volume!)"],
              ["Insights Events", "Unusual API call patterns", "Per event"],
            ],
          },
        }),
      s("project", "Mini-project — hardened multi-region trail", "project",
        "",
        {
          code: { lang: "bash", source: '# 1. Create S3 bucket for trail logs (with Object Lock optional)\naws s3api create-bucket --bucket my-cloudtrail-logs --region us-east-1\n\n# 2. Create multi-region trail with integrity validation\naws cloudtrail create-trail \\\n  --name OrgTrail \\\n  --s3-bucket-name my-cloudtrail-logs \\\n  --is-multi-region-trail \\\n  --enable-log-file-validation \\\n  --kms-key-id alias/my-app-key \\\n  --is-organization-trail\n\n# 3. Start logging\naws cloudtrail start-logging --name OrgTrail\n\n# 4. Query via Athena (after Athena table created from logs)\n# SELECT eventName, userIdentity.arn, sourceIPAddress, eventTime\n# FROM cloudtrail_logs\n# WHERE eventName = \'RunInstances\' AND eventtime > \'2024-01-15\'\n# LIMIT 100;' },
        }),
      s("traps", "Exam traps", "trap",
        "**CloudTrail vs Config** — CloudTrail = API call log; Config = resource state over time.\n\n**Multi-region trail** captures EVERY region in one trail.\n\n**Log File Integrity Validation** = SHA-256 chained signatures; detects tampering.\n\n**Organization trail** from management account = trail for every member account."),
      s("real", "Real-world — IR gold", "real",
        "Athena over CloudTrail S3 logs = pivot table for any breach investigation. 'Who created this rogue user?' becomes a SQL query."),
    ],
  }),
  lesson({
    day: 65, phase: 5, weekInPhase: 2, phaseProgress: 40,
    topic: "AWS Config — resource state & compliance",
    task: "Enable Config recorder in 2 regions. Add the managed rule `s3-bucket-public-read-prohibited`. Make a bucket public — Config flags it as non-compliant. Add an auto-remediation Lambda.",
    depth: "Configuration recorder, rules (managed + custom Lambda), conformance packs, aggregator, remediation",
    source: "AWS Config docs",
    examWeight: "VERY HIGH — Domain 1 + Domain 5",
    whyMatters: "Config tracks every resource configuration as it changes. Lets you answer: 'What did this SG look like 30 days ago?' 'Who changed it?' 'Is this account compliant with CIS?'. Combined with auto-remediation, drift fixes itself.",
    howToDoIt: "Enable Config recorder (records all resources by default). Pick rules: managed (s3-public-read-prohibited, encrypted-volumes, mfa-enabled-for-iam-console-access...) or custom Lambda. Conformance Packs bundle rules for CIS/PCI/HIPAA. Remediation: SSM Automation document fires on non-compliance.",
    watchOutFor: "Recording cost scales with rate of change. Filter recorder to specific resource types if costs grow. Config is regional — enable in every region.",
    doneWhen: "Config catches a public bucket and remediation flips it private. Compliance score visible. Aggregator combines org-wide compliance.",
    examTrap: "'Detect drift / non-compliance' = Config. 'Aggregate findings' = Security Hub (which uses Config under the hood).",
    realWorld: "Every regulated AWS account runs Config + a CIS conformance pack. Drift detection is the basis of every continuous-compliance program.",
    sections: [
      s("intro", "What Config does", "intro",
        "Records every change to every resource. Evaluates against rules. Produces compliance status. Optionally auto-remediates."),
      s("rules", "Rules — managed vs custom", "concept",
        "**Managed rules** — pre-built by AWS (200+ available). Pick from console.\n\n**Custom rules** — Lambda function evaluates resource and returns COMPLIANT / NON_COMPLIANT. Use for unique policies."),
      s("project", "Mini-project — bucket compliance + remediation", "project",
        "",
        {
          code: { lang: "bash", source: '# Add managed rule\naws configservice put-config-rule --config-rule \\\'{\n  "ConfigRuleName": "s3-bucket-public-read-prohibited",\n  "Source": {\n    "Owner": "AWS",\n    "SourceIdentifier": "S3_BUCKET_PUBLIC_READ_PROHIBITED"\n  }\n}\\\'\n\n# Add remediation: SSM Automation document that makes bucket private\naws configservice put-remediation-configurations --remediation-configurations \\\'[{\n  "ConfigRuleName": "s3-bucket-public-read-prohibited",\n  "TargetType": "SSM_DOCUMENT",\n  "TargetId": "AWS-DisableS3BucketPublicReadWrite",\n  "Automatic": true,\n  "MaximumAutomaticAttempts": 3,\n  "Parameters": {"S3BucketName": {"ResourceValue": {"Value": "RESOURCE_ID"}}}\n}\\\'' },
        }),
      s("traps", "Exam traps", "trap",
        "**Config is regional.** Enable in every region.\n\n**Aggregator** consolidates from multiple accounts / regions.\n\n**Conformance Packs** bundle rules + remediation for a standard (CIS, PCI)."),
      s("real", "Real-world — continuous compliance", "real",
        "Config + Conformance Pack (CIS or PCI) + Security Hub + auto-remediation = continuous compliance. Pre-audit reports come straight out."),
    ],
  }),
  lesson({
    day: 66, phase: 5, weekInPhase: 2, phaseProgress: 48,
    topic: "AWS Backup — central backup management",
    task: "Create a backup plan with daily backups, 35-day retention, cross-region copy. Apply to RDS + EBS + DynamoDB via tags. Test restore.",
    depth: "Backup plans, backup vaults, backup selections, cross-region/cross-account copy, vault lock (WORM)",
    source: "AWS Backup docs",
    examWeight: "HIGH — Domain 2 + Domain 5",
    whyMatters: "Centralised backup across EBS, RDS, DynamoDB, EFS, FSx, Storage Gateway, S3, and more. Replaces per-service backup config. Vault Lock gives WORM compliance (regulated industries).",
    howToDoIt: "Create a Backup Vault (KMS-encrypted destination). Create a Backup Plan: schedule (cron) + lifecycle (when to transition to cold, when to expire) + cross-region copy. Backup Selection picks resources by tag or ARN. Optional: Vault Lock for WORM.",
    watchOutFor: "Backup Vault Lock cannot be removed once enabled — be sure. Cross-region copies pay egress. Cross-account requires sharing the vault.",
    doneWhen: "Daily backups happening. Cross-region copy completing. Test restore works.",
    examTrap: "'Centralised backup across many AWS services' = AWS Backup. 'Just RDS snapshots' = RDS automated backups.",
    realWorld: "AWS Backup eliminated 6 different per-service backup configurations. One policy, one report, one place.",
    sections: [
      s("plan", "Backup plan + cross-region", "config",
        "",
        {
          code: { lang: "json", source: '{\n  "BackupPlan": {\n    "BackupPlanName": "daily-35-day",\n    "Rules": [{\n      "RuleName": "DailyAt3am",\n      "TargetBackupVaultName": "prod-vault",\n      "ScheduleExpression": "cron(0 3 ? * * *)",\n      "StartWindowMinutes": 60,\n      "CompletionWindowMinutes": 180,\n      "Lifecycle": {\n        "MoveToColdStorageAfterDays": 30,\n        "DeleteAfterDays": 365\n      },\n      "CopyActions": [{\n        "DestinationBackupVaultArn": "arn:aws:backup:us-west-2:123:backup-vault:dr-vault",\n        "Lifecycle": {"DeleteAfterDays": 365}\n      }]\n    }]\n  }\n}' },
        }),
      s("traps", "Exam traps", "trap",
        "**Vault Lock is irrevocable** when enforced.\n\n**Cross-region + cross-account** for full DR isolation.\n\n**Backup tags** select resources — easier than ARN lists."),
      s("real", "Real-world — unified backup", "real",
        "One central account holds the Backup Vault. Tag-based selection means new resources are auto-backed-up if tagged correctly."),
    ],
  }),
  lesson({
    day: 67, phase: 5, weekInPhase: 2, phaseProgress: 56,
    topic: "Disaster Recovery — RTO/RPO & 4 strategies",
    task: "Sketch each of the 4 DR strategies for a 3-tier app. Calculate cost vs RTO/RPO trade-offs. Pick the right one for a fictional bank vs a hobby site.",
    depth: "RTO vs RPO, Backup & Restore, Pilot Light, Warm Standby, Multi-Site Active-Active",
    source: "AWS DR Strategies whitepaper",
    examWeight: "VERY HIGH — Domain 2 (Resilient)",
    whyMatters: "DR is straight exam money. Every scenario question keys off RTO (recovery time) and RPO (acceptable data loss). Memorise the 4 strategies and their cost / RTO / RPO numbers.",
    howToDoIt: "Pick a strategy based on RTO/RPO budget. Backup & Restore (hours RTO, hours RPO) — restore from S3 backups. Pilot Light (10s of min RTO) — DB always replicated, app stack restored from images. Warm Standby (~5 min RTO) — scaled-down full stack always running in DR region. Multi-Site (seconds RTO) — full active-active.",
    watchOutFor: "Cost scales inversely with RTO. Multi-Site costs ~2×; Backup & Restore is cheapest. Test the DR plan — most DR plans fail because they were never exercised. Run a real game-day at least annually.",
    doneWhen: "You can name each strategy + recite typical RTO/RPO/cost. You can match a scenario to the right strategy.",
    examTrap: "'Cheapest DR' = Backup & Restore. '< 5 min RTO' = Warm Standby. '< seconds RTO' = Multi-Site. 'RPO measured in hours' = Backup & Restore.",
    realWorld: "Financial services: Multi-Site Active-Active for trading (5-min outage costs millions). Most SaaS: Warm Standby. Hobby sites: Backup & Restore.",
    sections: [
      s("rto-rpo", "RTO vs RPO", "concept",
        "**RTO** (Recovery Time Objective) = how long until you're back online.\n\n**RPO** (Recovery Point Objective) = how much data you can afford to lose (lag between last backup and the outage).\n\nLower both = more expensive."),
      s("four", "The 4 strategies", "compare",
        "",
        {
          table: {
            headers: ["Strategy", "RTO", "RPO", "Cost", "Mechanism"],
            rows: [
              ["Backup & Restore", "Hours", "Hours", "Lowest", "S3 backups, restore from scratch"],
              ["Pilot Light", "10s of min", "Minutes", "Low", "Core DB replicated, rest from AMI"],
              ["Warm Standby", "1–5 min", "Seconds", "Medium", "Scaled-down full stack in DR region"],
              ["Multi-Site Active-Active", "Seconds", "Near 0", "Highest (~2×)", "Full production in both regions"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**Lower RTO/RPO = higher cost.** Pick the cheapest that meets requirements.\n\n**Test the plan.** Untested DR is fiction.\n\n**Aurora Global DB** + Route 53 failover is the canonical Warm Standby pattern."),
      s("real", "Real-world — financial trading", "real",
        "Fidelity-style multi-region active-active for trading. A 5-min outage during market hours costs millions. The ~40% DR cost is rounding error vs the business impact."),
    ],
  }),
  lesson({
    day: 68, phase: 5, weekInPhase: 3, phaseProgress: 64,
    topic: "Systems Manager — fleet management",
    task: "Install the SSM Agent on an EC2. Use Session Manager to shell in without SSH. Run a command across a fleet via Run Command. Patch using Patch Manager. Store config in Parameter Store.",
    depth: "Session Manager (SSH replacement), Run Command, Patch Manager, Parameter Store, Automation, State Manager, Inventory",
    source: "AWS Systems Manager docs",
    examWeight: "VERY HIGH — Domain 5",
    whyMatters: "SSM is the fleet-ops Swiss army knife. Replaces SSH (Session Manager), runs commands across instances (Run Command), patches OS (Patch Manager), stores config (Parameter Store), automates runbooks (Automation), enforces state (State Manager).",
    howToDoIt: "Pre-req: SSM Agent on each instance + Instance Profile with `AmazonSSMManagedInstanceCore`. Session Manager: open browser console session to instance — no SSH, no bastion, full CloudTrail audit. Run Command: send a shell script to many instances at once. Patch Manager: define patch baselines + maintenance windows.",
    watchOutFor: "Session Manager auditable in CloudTrail + S3 — recordings of sessions optional. Beats SSH because no port 22, no key management. Patch Manager has separate baselines per OS.",
    doneWhen: "You can `aws ssm start-session` to any instance. Run Command updates a fleet. Patches applied via maintenance window.",
    examTrap: "'SSH into instance with no public IP / no bastion' = Session Manager. 'Run command on fleet' = Run Command. 'Centrally manage patches' = Patch Manager.",
    realWorld: "Modern AWS shops eliminated SSH entirely — Session Manager only. Audit clean, no key management, no port 22 exposure. Patch Manager runs the boring quarterly patching automatically.",
    sections: [
      s("capabilities", "SSM capabilities", "concept",
        "**Session Manager** — browser/CLI shell to an instance; no SSH.\n**Run Command** — execute shell scripts on many instances.\n**Patch Manager** — apply OS patches per baseline.\n**Parameter Store** — KV config + SecureString secrets.\n**Automation** — runbooks (Documents) that orchestrate AWS APIs.\n**State Manager** — enforce instance state (e.g., antivirus installed, file exists).\n**Inventory** — collect software and OS inventory from fleet."),
      s("session", "Session Manager", "config",
        "",
        {
          code: { lang: "bash", source: '# Open shell — no SSH key, no bastion\naws ssm start-session --target i-0abc\n\n# Port forwarding from local to RDS via the EC2\naws ssm start-session --target i-0abc \\\n  --document-name AWS-StartPortForwardingSessionToRemoteHost \\\n  --parameters \\\'{"host":["mydb.us-east-1.rds.amazonaws.com"],"portNumber":["5432"],"localPortNumber":["5432"]}\\\'' },
        }),
      s("traps", "Exam traps", "trap",
        "**Session Manager replaces SSH.** Audit clean. No port 22.\n\n**Run Command** for fleet-wide shell scripts.\n\n**Patch Manager** + Maintenance Windows for compliance patching."),
      s("real", "Real-world — kill SSH", "real",
        "Modern shops disable SSH entirely. Session Manager + CloudTrail + S3 recordings = full audit trail with zero key management."),
    ],
  }),
  lesson({
    day: 69, phase: 5, weekInPhase: 3, phaseProgress: 72,
    topic: "SSM — Parameter Store, Automation runbooks",
    task: "Store an app config hierarchy in Parameter Store (`/prod/api/db_url`, `/prod/api/log_level`). Build an Automation document that takes a snapshot of every EBS volume tagged `backup=true`.",
    depth: "Parameter Store hierarchies, Standard vs Advanced tier, SecureString, Automation Documents, schedule",
    source: "AWS SSM Parameter Store + Automation docs",
    examWeight: "HIGH — Domain 1 + Domain 5",
    whyMatters: "Parameter Store is the cheap, AWS-native config store. Hierarchical paths make it organised. SecureString = KMS encryption free. Automation runbooks orchestrate multi-step AWS API workflows reproducibly.",
    howToDoIt: "Parameter Store: paths like `/env/app/key`. SecureString uses KMS. Reference in Lambda env vars, CFN, ECS task defs. Automation: YAML/JSON Document with steps (`aws:executeAwsApi`, `aws:runCommand`, etc.). Schedule via EventBridge.",
    watchOutFor: "Standard tier free up to 10K params, 4 KB each. Advanced tier paid, 8 KB, supports policies (e.g., expire param after date). Automation Documents can target multiple resources (rate control).",
    doneWhen: "Hierarchy populated, Lambda reads from it. Automation document snapshots EBS daily.",
    examTrap: "'Cheap app config' = Parameter Store. 'Secret with rotation' = Secrets Manager.",
    realWorld: "Most teams put all non-secret config in Parameter Store. CI/CD references `/prod/...` paths. ECS task definitions reference Parameter Store via `valueFrom`.",
    sections: [
      s("params", "Parameter hierarchies", "config",
        "",
        {
          code: { lang: "bash", source: '# Hierarchy\naws ssm put-parameter --name /prod/api/db_url \\\n  --value "postgres://..." --type SecureString --key-id alias/my-app-key\naws ssm put-parameter --name /prod/api/log_level \\\n  --value "INFO" --type String\n\n# Bulk fetch by path\naws ssm get-parameters-by-path --path /prod/api --recursive --with-decryption' },
        }),
      s("automation", "Automation document", "config",
        "",
        {
          code: { lang: "yaml", source: 'schemaVersion: "0.3"\ndescription: Snapshot all EBS volumes tagged backup=true\nmainSteps:\n  - name: FindVolumes\n    action: aws:executeAwsApi\n    inputs:\n      Service: ec2\n      Api: DescribeVolumes\n      Filters:\n        - Name: tag:backup\n          Values: ["true"]\n    outputs:\n      - Name: VolumeIds\n        Selector: $.Volumes..VolumeId\n        Type: StringList\n\n  - name: SnapshotEach\n    action: aws:executeAwsApi\n    inputs:\n      Service: ec2\n      Api: CreateSnapshot\n      VolumeId: "{{ FindVolumes.VolumeIds }}"\n      Description: "Auto-snapshot by SSM Automation"' },
        }),
      s("traps", "Exam traps", "trap",
        "**Parameter Store SecureString** = KMS for free.\n\n**Standard 4 KB / Advanced 8 KB.** Pick Standard unless you need bigger or policies.\n\n**Automation Documents** are AWS-managed `runbook` orchestration."),
      s("real", "Real-world — config + runbooks", "real",
        "All non-secret config in Parameter Store, referenced by ECS / Lambda. Runbooks for common ops (snapshot, AMI build, reboot fleet)."),
    ],
  }),
  lesson({
    day: 70, phase: 5, weekInPhase: 3, phaseProgress: 80,
    topic: "SSM — Patch Manager, Compliance, State Manager",
    task: "Define a patch baseline for Amazon Linux 2023. Create a maintenance window. Schedule weekly patching. Use State Manager to ensure CloudWatch Agent is installed on every instance.",
    depth: "Patch baselines, maintenance windows, compliance reporting, State Manager Associations",
    source: "AWS Patch Manager docs",
    examWeight: "MEDIUM — Domain 5",
    whyMatters: "Patching is the unsexy security control that prevents 60% of breaches. Patch Manager makes it routine: define baseline, set window, automate. State Manager enforces 'this thing must always be true' (agent installed, file present, service running).",
    howToDoIt: "Pick or create a Patch Baseline per OS (severity levels to auto-approve, approval delay). Create a Maintenance Window (cron schedule). Register Patch Manager as a task in the window. Tag instances to opt them in. State Manager Associations apply a runbook on a schedule to keep state in sync.",
    watchOutFor: "Patch Manager defaults to scan-only — you have to set `Operation: Install`. Maintenance windows are how you control blast radius (e.g., 10% of fleet at a time).",
    doneWhen: "Weekly patching runs in the maintenance window. Compliance dashboard shows percentage patched. State Manager enforces agent presence.",
    examTrap: "'Patch the fleet on a schedule' = Patch Manager. 'Enforce a config across instances' = State Manager.",
    realWorld: "Patch Manager + Maintenance Windows = audit-clean patching. SOC2/PCI auditors specifically ask: 'How do you patch?' This is the answer.",
    sections: [
      s("baselines", "Patch baselines", "concept",
        "A baseline defines which patches to auto-approve. Per OS. Severity levels (Critical / Important / Medium / Low). Approval delay (e.g., 7 days after release). Reject list for known-bad patches."),
      s("windows", "Maintenance windows", "concept",
        "Cron-scheduled window during which Patch Manager runs. Cutoff time stops new tasks. Concurrency control (e.g., 10% of fleet at a time). Tasks include patching, Run Command, Step Functions."),
      s("state", "State Manager", "concept",
        "Associations bind a Document + targets + schedule. Use to: install CloudWatch Agent on every instance, restart a service, ensure a file exists. Self-healing config."),
      s("traps", "Exam traps", "trap",
        "**Operation: Scan vs Install.** Default is Scan (just report). Set Install to actually patch.\n\n**Concurrency** in maintenance windows = blast-radius control.\n\n**State Manager** ≠ Run Command — State Manager is continuous enforcement; Run Command is one-shot."),
      s("real", "Real-world — audit-clean patching", "real",
        "Weekly Maintenance Window patches 25% of fleet, then 50%, then 100% over 4 weeks. Compliance dashboard answers SOC2 audit questions automatically."),
    ],
  }),
  lesson({
    day: 71, phase: 5, weekInPhase: 4, phaseProgress: 90,
    topic: "Cost Explorer, Budgets, Cost Anomaly Detection",
    task: "Open Cost Explorer; group by service and tag. Create a Budget that alerts at 80% of monthly forecast. Enable Cost Anomaly Detection.",
    depth: "Cost Explorer, AWS Budgets (cost, usage, reservation), Cost Anomaly Detection, Cost & Usage Reports (CUR), Cost Categories",
    source: "AWS Cost Management docs",
    examWeight: "VERY HIGH — Domain 4 (Cost-Optimised, 20%)",
    whyMatters: "Cost Explorer visualises spend. Budgets alert before you blow the budget. Anomaly Detection catches surprise spikes (cryptominer on EC2, runaway data egress). Cost Categories slice spend by team / project / environment.",
    howToDoIt: "Cost Explorer is free; enable at account level. Budgets: pick scope (account / service / tag), threshold, alerts. Anomaly Detection: define a monitor by service or by tag; ML learns normal pattern. CUR: dumps every billing line to S3 daily — Athena-queryable for deep analysis.",
    watchOutFor: "Activating cost allocation tags (in Billing console) takes ~24h to backfill. Budgets are per-account by default; for org-wide budgets use the management account.",
    doneWhen: "Cost Explorer shows clean spend by service + tag. Budget alert wired to SNS. Anomaly Detection live.",
    examTrap: "'Forecast monthly spend + alert' = Budgets. 'Detect unusual cost spike automatically' = Cost Anomaly Detection. 'Deepest analysis' = CUR + Athena.",
    realWorld: "Every mature AWS account has Budgets per team + Anomaly Detection org-wide. CUR feeds the FinOps dashboard.",
    sections: [
      s("explorer", "Cost Explorer", "concept",
        "Free, in-console visualisation of spend. Group by: service, region, account, tag, usage type. Filter to dig in. Forecast next month based on history. Right-sizing recommendations (idle / underutilised EC2 → suggest smaller / Spot)."),
      s("budgets", "Budgets", "config",
        "",
        {
          code: { lang: "bash", source: '# Monthly budget at $5 000, alert at 80% forecast\naws budgets create-budget --account-id 123 --budget \\\'{\n  "BudgetName": "monthly-prod",\n  "BudgetLimit": {"Amount": "5000", "Unit": "USD"},\n  "TimeUnit": "MONTHLY",\n  "BudgetType": "COST",\n  "CostFilters": {"TagKeyValue": ["user:Environment$prod"]}\n}\\\' --notifications-with-subscribers \\\'[\n  {\n    "Notification": {\n      "NotificationType": "FORECASTED",\n      "ComparisonOperator": "GREATER_THAN",\n      "Threshold": 80\n    },\n    "Subscribers": [{"SubscriptionType": "SNS","Address": "arn:aws:sns:us-east-1:123:billing-alerts"}]\n  }\n]\\\'' },
        }),
      s("anomaly", "Cost Anomaly Detection", "concept",
        "ML-based monitors that learn normal spend per service or per tag. Alert when daily spend deviates significantly. Catches: misconfigured services, cryptominers, data-egress surprises, abandoned dev resources."),
      s("traps", "Exam traps", "trap",
        "**Activate cost allocation tags** in Billing console (24h backfill).\n\n**CUR** is the source-of-truth raw data — load into Athena/Redshift for FinOps.\n\n**Cost Categories** are pseudo-tags computed from rules — useful when tagging is incomplete."),
      s("real", "Real-world — FinOps", "real",
        "Mature shops have a FinOps team and dashboard built from CUR data. Per-team budgets + anomaly alerts catch waste early."),
    ],
  }),
  lesson({
    day: 72, phase: 5, weekInPhase: 4, phaseProgress: 100,
    topic: "Trusted Advisor & Compute Optimizer",
    task: "Open Trusted Advisor: read every check in the 5 categories. Open Compute Optimizer: review right-sizing recommendations for EC2 + Lambda + EBS.",
    depth: "Trusted Advisor (cost, performance, security, fault tolerance, service limits), Compute Optimizer (right-sizing)",
    source: "AWS Trusted Advisor docs · Compute Optimizer docs",
    examWeight: "HIGH — Domain 4",
    whyMatters: "Trusted Advisor is the curated checklist of AWS-recommended improvements. Compute Optimizer goes deeper: it analyses actual utilisation and recommends specific instance types, EBS volumes, Lambda memory. Together they're free money sitting on the table.",
    howToDoIt: "Trusted Advisor: open and read every check. With Business Support or above, all checks unlock. Fix idle resources, low-util instances, unattached EBS, idle Elastic IPs. Compute Optimizer: enable; wait ~24h for it to gather metrics; apply recommendations (often downsize EC2 = 30-50% savings).",
    watchOutFor: "Free tier of Trusted Advisor shows only 6 core checks; full set requires Business Support+ ($100+/month — may be worth it). Compute Optimizer is free for opt-in.",
    doneWhen: "Trusted Advisor reviewed; quick wins applied. Compute Optimizer recommendations actioned.",
    examTrap: "'Right-size EC2 with actual utilisation data' = Compute Optimizer. 'AWS best-practice checks' = Trusted Advisor. 'Cost analysis' = Cost Explorer.",
    realWorld: "Mature shops run a weekly review of Trusted Advisor + Compute Optimizer + Cost Anomaly findings. Compounding savings over time.",
    sections: [
      s("ta", "Trusted Advisor categories", "concept",
        "5 categories: Cost (idle resources, low util), Performance (high util, service limits), Security (open SGs, MFA, S3 public), Fault Tolerance (Multi-AZ, snapshots), Service Limits (approaching limits)."),
      s("co", "Compute Optimizer", "concept",
        "Analyses CloudWatch metrics over time. Recommends: smaller / different EC2 instance, Graviton swap, EBS volume type/size change, Lambda memory tuning. Often 20-50% cost reduction at no perf risk."),
      s("traps", "Exam traps", "trap",
        "**TA = curated checks.** Limited free; full with Business Support+.\n\n**Compute Optimizer = right-sizing.** Free. Acts on actual utilisation, not heuristics."),
      s("real", "Real-world — weekly hygiene", "real",
        "FinOps team reviews TA + Compute Optimizer + Anomaly weekly. Routine downsizing compounds into significant savings over a year."),
    ],
  }),
];
