import type { AwsDay } from "@/types";
import { s, lesson, review } from "./section-helpers";

// PHASE 1 — FOUNDATION (Days 1–15)
// IAM, VPC, EC2, S3, EBS/EFS, CLI/SDK, CloudFormation
export const PHASE_1: AwsDay[] = [
  lesson({
    day: 1, phase: 1, weekInPhase: 1, phaseProgress: 4,
    topic: "IAM — Identity & Access (Part 1)",
    task: "Enable MFA on root, create an admin IAM user, set a strong password policy, and create three groups: Developers, DevOps, ReadOnly. Attach managed policies to each group.",
    depth: "Users, Groups, Roles, Policies, MFA, password policy, root account hygiene",
    source: "AWS IAM docs · re:Invent 'IAM Best Practices' SEC301",
    examWeight: "HIGH — Domain 1 (Secure Architectures, 30%)",
    whyMatters: "IAM is the gatekeeper of every API call in AWS. Console clicks, CLI commands, SDK calls, service-to-service traffic — all go through IAM. It answers two questions: WHO are you and WHAT can you do. Without it you have a flat root-only account where one leaked credential is game over. With well-designed IAM, each human and each service holds only what it needs, so a compromise has bounded blast radius.",
    howToDoIt: "Secure root first: turn on MFA, create an admin IAM user, save root credentials offline, and never log in as root again. Set a strong account-wide password policy. Create groups (Developers, DevOps, ReadOnly), attach managed policies to GROUPS not users. Add users to groups. For programmatic access, prefer Roles over long-lived access keys whenever possible.",
    watchOutFor: "IAM is GLOBAL, not regional — users, groups, roles, and policies span all regions. Attach policies to groups (or roles), never directly to users. AWS-managed policies are a fine starting point but tend toward over-permissive — graduate to customer-managed policies in production.",
    doneWhen: "You can explain Users vs Groups vs Roles in one sentence each. Root has MFA. Your admin user has MFA. You have three groups, two users in groups, and ZERO inline policies. You can sign in as your admin user and never use root again.",
    examTrap: "Root hygiene shows up constantly. 'New AWS account — what is the FIRST thing to do?' → enable MFA on root, create an admin user, lock root credentials away. Anything that says 'use root for daily ops' or 'attach policies directly to users' is wrong.",
    realWorld: "Netflix runs thousands of microservices, each with its own IAM role scoped to only the AWS APIs it needs. The video-encoding service can write to one S3 prefix and nothing else. If it's compromised, the blast radius stops at that prefix.",
    sections: [
      s("intro", "What is IAM?", "intro",
        "IAM is AWS's identity and access service. Every single API call to AWS — from a console click that creates a bucket, to a Lambda reading from DynamoDB, to a CLI command from your laptop — is authenticated and authorised by IAM. It's free, global, and the foundation of every other security control."),
      s("why", "Why IAM exists", "concept",
        "Without IAM, AWS would be a flat playground where one credential opens everything. IAM lets you slice access by identity (a developer, a CI runner, a Lambda function) and by action (read S3 but not delete; describe EC2 but not run). Least privilege is the rule: every entity gets the minimum permissions to do its job and nothing more. When something gets compromised — and eventually it will — least privilege turns a catastrophe into an incident."),
      s("components", "Core components", "concept",
        "Five things to know:\n\n• **Users** — long-lived human or programmatic identities. Password, optional MFA, optional access keys.\n• **Groups** — collections of users sharing permissions. Assign policies to groups, never to users directly.\n• **Roles** — temporary credentials assumed by services, applications, or federated users. Right answer for almost everything that isn't a human.\n• **Policies** — JSON documents that grant or deny actions on resources. Attached to users, groups, or roles.\n• **Identity Providers** — SAML / OIDC federation so corporate SSO (Okta, Azure AD) controls who logs into AWS."),
      s("policy", "Anatomy of a policy", "config",
        "An IAM policy is JSON with a Version, one or more Statements, and each Statement has Effect (Allow/Deny), Action (which API calls), Resource (which ARNs), and optional Condition (when this rule applies). The example below allows read-only access to one S3 bucket but only when the request is in us-east-1.",
        {
          code: { lang: "json", source: '{\n  "Version": "2012-10-17",\n  "Statement": [{\n    "Sid": "AllowS3ReadOnlyBucket",\n    "Effect": "Allow",\n    "Action": ["s3:GetObject", "s3:ListBucket"],\n    "Resource": [\n      "arn:aws:s3:::my-app-bucket",\n      "arn:aws:s3:::my-app-bucket/*"\n    ],\n    "Condition": {\n      "StringEquals": { "aws:RequestedRegion": "us-east-1" }\n    }\n  }]\n}' },
        }),
      s("project", "Mini-project — secure 3-person dev team", "project",
        "Goal: spin up a secure IAM structure for a 3-person dev team with least-privilege access. Estimate: 45 min. Steps: create three groups (Developers, DevOps, ReadOnly), attach managed policies, create users, add users to groups, generate console passwords with --password-reset-required so they're forced to rotate on first login.",
        {
          code: { lang: "bash", source: '# 1. Create groups\naws iam create-group --group-name Developers\naws iam create-group --group-name DevOps\naws iam create-group --group-name ReadOnly\n\n# 2. Attach managed policies\naws iam attach-group-policy --group-name Developers \\\n  --policy-arn arn:aws:iam::aws:policy/AmazonEC2FullAccess\naws iam attach-group-policy --group-name ReadOnly \\\n  --policy-arn arn:aws:iam::aws:policy/ReadOnlyAccess\n\n# 3. Users → groups\naws iam create-user --user-name alice\naws iam add-user-to-group --user-name alice --group-name Developers\n\n# 4. Console login (forced reset on first login)\naws iam create-login-profile --user-name alice \\\n  --password "Temp@1234!" --password-reset-required' },
        }),
      s("traps", "Exam traps", "trap",
        "**IAM is GLOBAL.** Users, groups, roles, policies span every region.\n\n**Root is for setup only.** Enable MFA on root, create an admin user, lock root credentials away.\n\n**Explicit Deny always wins.** Evaluation order is Deny → Allow → Implicit Deny. Even if 10 policies allow an action, one Deny overrides them all.\n\n**EC2 needs a Role, not keys.** Whenever an EC2 instance accesses S3/DynamoDB/anything — use an Instance Profile (IAM Role attached to the instance), never put access keys on the instance."),
      s("real", "Real-world — Netflix", "real",
        "Netflix uses IAM roles per microservice — the video-encoding service can write to one S3 bucket but cannot touch DynamoDB; the recommendation engine reads DynamoDB but cannot touch the encoding bucket. If one service is popped, the blast radius is exactly that role's permissions and nothing more."),
    ],
  }),
  lesson({
    day: 2, phase: 1, weekInPhase: 1, phaseProgress: 8,
    topic: "IAM — Roles, Trust Policies & Cross-Account",
    task: "Create an EC2 instance role that can read one S3 bucket. Attach an instance profile, launch an EC2, SSH in, and confirm `aws s3 ls` works without any keys on disk. Then build a cross-account read role assumable by a second AWS account.",
    depth: "Roles, trust policies, instance profiles, cross-account assume-role, permission boundaries, SCPs",
    source: "AWS IAM Roles docs · 'Cross-Account Access' AWS blog · re:Invent SEC405",
    examWeight: "VERY HIGH — Domain 1",
    whyMatters: "Roles are the right answer for almost everything that isn't a human user. They issue temporary credentials (15 min – 12 h), they're assumed via STS by trusted principals, and they leave no long-lived secret on disk. Once you understand Trust Policy + Permissions Policy, you can give EC2 access to S3, let Lambda write to DynamoDB, federate corporate SSO, share access between accounts — all without storing a single access key.",
    howToDoIt: "A Role is two policies glued together: a TRUST policy that says WHO can assume me (the EC2 service, another AWS account, an OIDC provider) and a PERMISSIONS policy that says WHAT the assumer can do once assumed. To attach a Role to EC2, wrap it in an Instance Profile and attach that to the instance. EC2 rotates credentials automatically via the metadata service.",
    watchOutFor: "An Instance Profile is NOT the same as the Role — it's a one-Role wrapper that EC2 understands. Trust policies are easy to get wrong: if you forget the `sts:AssumeRole` action, nothing can assume the role.",
    doneWhen: "Your EC2 reads S3 with no keys on disk. Your second AWS account can `aws sts assume-role --role-arn ...` and get temporary credentials. You can explain identity-based policy (attached to user/role) vs resource-based policy (attached to a bucket / KMS key).",
    examTrap: "Whenever you see access keys hardcoded inside an EC2 user-data or .aws/credentials file, that's a wrong answer. Whenever the choice is 'rotate keys' vs 'use a role', use a role.",
    realWorld: "Most enterprises use IAM Identity Center (formerly SSO) federated to Okta/Azure AD. Engineers don't get IAM Users at all — they assume roles via SSO, get 1-hour temporary credentials, and the audit log is clean.",
    sections: [
      s("concept", "Why Roles, not Users, for non-humans", "concept",
        "An IAM User has a password and optionally access keys — long-lived credentials that have to live somewhere. A Role has neither. When something assumes a Role, AWS STS issues short-lived credentials that automatically expire. Nothing to rotate, nothing on disk to leak. Rule: humans get Users (or, better, federation); everything else gets a Role."),
      s("trust", "Trust policy vs permissions policy", "config",
        "Two policies. The **trust policy** is on the Role and says WHO can assume me. The **permissions policy** is on the Role and says WHAT the assumer can do once assumed. The example below trusts the EC2 service to assume the role.",
        {
          code: { lang: "json", source: '{\n  "Version": "2012-10-17",\n  "Statement": [{\n    "Effect": "Allow",\n    "Principal": { "Service": "ec2.amazonaws.com" },\n    "Action": "sts:AssumeRole"\n  }]\n}' },
        }),
      s("project", "Mini-project — EC2 → S3 with zero keys", "project",
        "An EC2 instance that reads an S3 bucket using only an Instance Profile. Credentials live in the EC2 metadata service and rotate automatically.",
        {
          code: { lang: "bash", source: '# 1. Trust policy\ncat > ec2-trust.json <<EOF\n{ "Version": "2012-10-17",\n  "Statement": [{\n    "Effect": "Allow",\n    "Principal": {"Service": "ec2.amazonaws.com"},\n    "Action": "sts:AssumeRole" }] }\nEOF\n\n# 2. Role + S3 read policy\naws iam create-role --role-name EC2-S3-ReadRole \\\n  --assume-role-policy-document file://ec2-trust.json\naws iam attach-role-policy --role-name EC2-S3-ReadRole \\\n  --policy-arn arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess\n\n# 3. Wrap in Instance Profile\naws iam create-instance-profile --instance-profile-name EC2-S3-ReadProfile\naws iam add-role-to-instance-profile \\\n  --instance-profile-name EC2-S3-ReadProfile \\\n  --role-name EC2-S3-ReadRole' },
        }),
      s("cross", "Cross-account access", "concept",
        "To let Account B assume a Role in Account A: set Principal in Account A's trust policy to `{\"AWS\": \"arn:aws:iam::ACCOUNT_B:root\"}`. Then a user in Account B with `sts:AssumeRole` permission on that role can call `aws sts assume-role --role-arn ...` and operate inside Account A for the session duration."),
      s("guardrails", "Permission boundaries vs SCPs", "concept",
        "Two ways to put a hard ceiling on what an identity can do, even if its policies allow more:\n\n• **Permission boundaries** — attached to an IAM identity. Effective permissions = its policies ∩ its boundary. Use to delegate user creation safely.\n• **Service Control Policies (SCPs)** — applied at the AWS Organizations level to entire accounts or OUs. SCPs cannot grant; only restrict. Use to enforce 'no one in this OU can use any region except eu-west-1' or 'no one can disable CloudTrail'."),
      s("traps", "Exam traps", "trap",
        "**Resource-based vs identity-based policy.** Resource-based attach to the resource (S3 bucket policy, KMS key policy, SNS topic policy). Identity-based attach to user/group/role. Cross-account often needs both.\n\n**Instance Profile ≠ Role**, but the console hides this. CLI flows expose it.\n\n**STS regional endpoints** — STS is global by default but has regional endpoints; for HA, use the regional endpoint."),
      s("real", "Real-world — Capital One federation", "real",
        "Capital One federates Okta into AWS Identity Center. Engineers log in to Okta, click 'AWS', pick an account + role, and get a console with 1-hour credentials. Zero long-lived keys exist for engineers. CloudTrail logs the assume-role event tied to a real human identity."),
    ],
  }),
  lesson({
    day: 3, phase: 1, weekInPhase: 1, phaseProgress: 12,
    topic: "VPC — Virtual Private Cloud (Part 1)",
    task: "From scratch with the CLI: build a VPC with 2 public + 2 private + 2 DB subnets across 2 AZs, an Internet Gateway, NAT Gateways, route tables wired correctly, and an EC2 in a private subnet that can reach the internet outbound but has no public IP.",
    depth: "CIDR, subnets, AZs, IGW, NAT GW vs NAT instance, route tables, public vs private subnet definition",
    source: "AWS VPC docs · 'VPC Best Practices' whitepaper · re:Invent NET305",
    examWeight: "VERY HIGH — Domain 1 + Domain 2",
    whyMatters: "A VPC is your private data centre inside AWS. You pick the IP ranges, the subnets, the routing, and the firewalls. Without VPC discipline, all your EC2s sit on a flat public network where the database is one misconfigured Security Group from being on the open internet. With a real VPC, you get defence in depth: web tier in public subnets, app tier in private subnets with no inbound from the internet, DB tier in subnets with no internet route at all.",
    howToDoIt: "Pick a /16 for the VPC (e.g., 10.0.0.0/16). Carve subnets per AZ — public (route to IGW) and private (route to NAT). Attach an Internet Gateway. Provision a NAT Gateway in each AZ for HA. Private route tables point 0.0.0.0/0 at the NAT Gateway — that's how private instances reach the internet outbound without being reachable inbound.",
    watchOutFor: "A 'public subnet' is just a subnet whose route table has a route to an IGW. There's no checkbox. NAT Gateway sits in a PUBLIC subnet (it needs the IGW to reach out) but services PRIVATE subnets (their route table points to it). For HA, run one NAT per AZ — a single NAT means all private subnets in other AZs lose internet if its AZ dies.",
    doneWhen: "You can draw the standard 3-tier VPC on a whiteboard from memory. Your private EC2 can `curl https://example.com` but you cannot SSH to it from your laptop. The DB subnet has no route to the internet at all.",
    examTrap: "If the answer mentions a NAT Instance, check whether it's still the right call — the exam usually wants NAT Gateway (managed, HA within an AZ, scales). NAT Instance is a self-managed EC2 you have to remember to disable Source/Destination Check on.",
    realWorld: "Airbnb runs a multi-AZ VPC with web ALBs in public subnets, app servers in private subnets (no public IPs), RDS in isolated DB subnets with no internet route. A NACL blocks known-bad IP ranges. Security Groups enforce per-tier traffic. A compromised web server cannot reach the database directly.",
    sections: [
      s("intro", "What a VPC is", "intro",
        "A VPC is your isolated virtual network in AWS. You define the IP space (a CIDR like 10.0.0.0/16), divide it into subnets (each in a single AZ), and control routing and firewalling. Every EC2, Lambda VPC, RDS, ECS task lives inside a VPC. Default VPC exists in every region but build your own for production."),
      s("subnets", "Subnets, AZs, public vs private", "concept",
        "A subnet is a slice of the VPC's CIDR (e.g., 10.0.1.0/24) tied to ONE Availability Zone. To survive an AZ outage, put a subnet of each tier in 2+ AZs. Public vs private isn't a checkbox — it's about routing: a subnet whose route table sends 0.0.0.0/0 to the Internet Gateway is public; one that sends it to a NAT Gateway is private; one with no 0.0.0.0/0 route is isolated."),
      s("igw", "Internet Gateway & NAT Gateway", "concept",
        "**IGW** is a horizontally-scaled, redundant component attached to the VPC that allows traffic in and out. One IGW per VPC, free.\n\n**NAT Gateway** lives in a public subnet, holds an Elastic IP, and lets instances in private subnets reach the internet outbound without being reachable inbound. Charged per hour + per GB. For HA: one NAT per AZ."),
      s("project", "Mini-project — 3-tier VPC from scratch", "project",
        "Build a production-grade VPC: 2 AZs, public + private + DB subnets, IGW, NAT, correct route tables. Estimate: 60 min.",
        {
          code: { lang: "bash", source: '# 1. VPC\nVPC_ID=$(aws ec2 create-vpc --cidr-block 10.0.0.0/16 \\\n  --query Vpc.VpcId --output text)\naws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames\n\n# 2. IGW\nIGW_ID=$(aws ec2 create-internet-gateway \\\n  --query InternetGateway.InternetGatewayId --output text)\naws ec2 attach-internet-gateway --vpc-id $VPC_ID --internet-gateway-id $IGW_ID\n\n# 3. Subnets across 2 AZs\nPUB1=$(aws ec2 create-subnet --vpc-id $VPC_ID --cidr-block 10.0.1.0/24 \\\n  --availability-zone us-east-1a --query Subnet.SubnetId --output text)\nPRIV1=$(aws ec2 create-subnet --vpc-id $VPC_ID --cidr-block 10.0.3.0/24 \\\n  --availability-zone us-east-1a --query Subnet.SubnetId --output text)\n\n# 4. NAT Gateway in PUB1\nEIP=$(aws ec2 allocate-address --domain vpc --query AllocationId --output text)\nNAT=$(aws ec2 create-nat-gateway --subnet-id $PUB1 --allocation-id $EIP \\\n  --query NatGateway.NatGatewayId --output text)\n\n# 5. Public route table → IGW\nPUB_RT=$(aws ec2 create-route-table --vpc-id $VPC_ID \\\n  --query RouteTable.RouteTableId --output text)\naws ec2 create-route --route-table-id $PUB_RT \\\n  --destination-cidr-block 0.0.0.0/0 --gateway-id $IGW_ID\naws ec2 associate-route-table --subnet-id $PUB1 --route-table-id $PUB_RT\n\n# 6. Private route table → NAT\nPRIV_RT=$(aws ec2 create-route-table --vpc-id $VPC_ID \\\n  --query RouteTable.RouteTableId --output text)\naws ec2 create-route --route-table-id $PRIV_RT \\\n  --destination-cidr-block 0.0.0.0/0 --nat-gateway-id $NAT\naws ec2 associate-route-table --subnet-id $PRIV1 --route-table-id $PRIV_RT' },
        }),
      s("traps", "Exam traps", "trap",
        "**NAT Gateway is in the PUBLIC subnet** but services PRIVATE subnets.\n\n**NAT Instance vs NAT Gateway** — Gateway is managed (HA in-AZ, scales). Instance is self-managed and must have Source/Dest Check DISABLED. Exam almost always wants Gateway.\n\n**One NAT per AZ for HA.** A single NAT in 1a means all private subnets lose internet if 1a dies."),
      s("real", "Real-world — Airbnb VPC layering", "real",
        "Airbnb's VPC: ALB in public subnets, app servers in private (no public IPs), RDS in isolated DB subnets (no 0.0.0.0/0 route). A subnet-level NACL blocks known-bad IP ranges. Security Groups enforce per-tier traffic. Defence in depth, layer by layer."),
    ],
  }),
  lesson({
    day: 4, phase: 1, weekInPhase: 1, phaseProgress: 16,
    topic: "VPC — Security Groups, NACLs, Endpoints, Peering & TGW",
    task: "On yesterday's VPC: lock down web tier with a Security Group (80/443 from 0.0.0.0/0), app tier (8080 from web SG only), DB tier (5432 from app SG only). Add a NACL that blocks one specific malicious /24. Provision a Gateway VPC Endpoint to S3.",
    depth: "Security Groups vs NACLs, VPC Endpoints (Gateway vs Interface), Peering, PrivateLink, Transit Gateway",
    source: "AWS VPC Endpoints docs · 'Networking at Scale' AWS whitepaper",
    examWeight: "VERY HIGH — Domain 1",
    whyMatters: "Security Groups and NACLs are your two firewalls. Endpoints let you reach AWS services privately (no NAT, no public internet). Peering connects two VPCs but isn't transitive. Transit Gateway is the hub for hub-and-spoke at scale. Pick the right tool and you save money, latency, and exposure all at once.",
    howToDoIt: "Default-deny inbound on Security Groups; only allow what you need, and prefer SG-references over CIDR (web-SG → app-SG, not 10.0.0.0/16 → app-SG). NACLs are stateless — every Allow needs a matching reverse rule including ephemeral ports (1024–65535). VPC Gateway Endpoints (S3, DynamoDB) are free; Interface Endpoints (everything else, via PrivateLink) cost per hour + per GB.",
    watchOutFor: "Security Groups are STATEFUL — return traffic is automatically allowed. NACLs are STATELESS — return traffic needs an explicit Allow. VPC Peering is NOT TRANSITIVE — A↔B and B↔C does not give you A↔C. For hub-and-spoke, Transit Gateway is the answer.",
    doneWhen: "Web accepts only 80/443 from anywhere; app accepts 8080 only from web SG; DB accepts 5432 only from app SG. A NACL on the public subnet denies a specific bad /24. `aws s3 ls` from your private instance now goes via the Gateway Endpoint.",
    examTrap: "If two VPCs are peered through a third, traffic does NOT transit. The exam tests this with diagrams. Security Groups can't deny — only allow. To explicitly block an IP, you need a NACL.",
    realWorld: "Lyft uses Transit Gateway as its network hub. 30+ VPCs (per service per region) attach to a single TGW. On-prem connects via Direct Connect → TGW. New VPC = one attachment + one TGW route. They moved from a peering mesh that exploded into N² connections.",
    sections: [
      s("sg-vs-nacl", "Security Groups vs NACLs", "compare",
        "**Security Group** — instance-level (technically ENI-level) firewall. Stateful. Allow rules ONLY. Default: deny all inbound, allow all outbound.\n\n**NACL** — subnet-level firewall. Stateless. Allow AND Deny. Rules numbered, evaluated in order, first match wins. Use to block specific IP ranges.",
        {
          table: {
            headers: ["Feature", "Security Group", "Network ACL"],
            rows: [
              ["Level", "ENI / instance", "Subnet"],
              ["State", "Stateful", "Stateless"],
              ["Rules", "Allow only", "Allow + Deny"],
              ["Evaluation", "All rules considered", "Numbered, first match wins"],
              ["Default", "Deny all inbound", "Allow all in & out"],
              ["Use case", "Day-to-day access control", "Block specific IPs / CIDRs"],
            ],
          },
        }),
      s("endpoints", "VPC Endpoints — Gateway vs Interface", "concept",
        "Endpoints let resources in your VPC reach AWS services privately, without traversing the internet or a NAT.\n\n• **Gateway Endpoints** — S3 and DynamoDB only. Free. Add a route in your route table.\n• **Interface Endpoints (PrivateLink)** — everything else (KMS, SQS, ECR, Secrets Manager). $0.01/hr per AZ + $0.01/GB. Creates an ENI in your subnet."),
      s("peering", "Peering vs PrivateLink vs TGW", "compare",
        "**VPC Peering** — 1:1 connection between 2 VPCs. Cheap. Non-transitive. Fine for a handful of VPCs.\n\n**PrivateLink** — exposes a service in your VPC to other VPCs / accounts via a private endpoint. Used for SaaS providers and cross-account services.\n\n**Transit Gateway** — hub for hub-and-spoke. One attachment per VPC; route table on the TGW decides who can talk to whom. Scales to thousands of VPCs. Right answer once you have ~5+ VPCs."),
      s("project", "Mini-project — lock down 3-tier VPC + S3 endpoint", "project",
        "",
        {
          code: { lang: "bash", source: '# Web SG — 80/443 from internet\nWEB_SG=$(aws ec2 create-security-group --vpc-id $VPC_ID \\\n  --group-name web-sg --description "web tier" \\\n  --query GroupId --output text)\naws ec2 authorize-security-group-ingress --group-id $WEB_SG \\\n  --protocol tcp --port 443 --cidr 0.0.0.0/0\n\n# App SG — only from Web SG (SG reference, not CIDR)\nAPP_SG=$(aws ec2 create-security-group --vpc-id $VPC_ID \\\n  --group-name app-sg --description "app tier" \\\n  --query GroupId --output text)\naws ec2 authorize-security-group-ingress --group-id $APP_SG \\\n  --protocol tcp --port 8080 --source-group $WEB_SG\n\n# DB SG — only from App SG\nDB_SG=$(aws ec2 create-security-group --vpc-id $VPC_ID \\\n  --group-name db-sg --description "db tier" \\\n  --query GroupId --output text)\naws ec2 authorize-security-group-ingress --group-id $DB_SG \\\n  --protocol tcp --port 5432 --source-group $APP_SG\n\n# Gateway Endpoint to S3 — free, private path\naws ec2 create-vpc-endpoint --vpc-id $VPC_ID \\\n  --service-name com.amazonaws.us-east-1.s3 \\\n  --route-table-ids $PRIV_RT' },
        }),
      s("traps", "Exam traps", "trap",
        "**SG = stateful, NACL = stateless.** If you allow inbound 443 on a NACL, you also need outbound 1024–65535 (ephemeral) for the response.\n\n**SG can't deny.** To block a specific malicious IP, you need a NACL deny rule.\n\n**Peering is not transitive.** Use Transit Gateway.\n\n**Gateway Endpoint = S3/DynamoDB only.** Everything else is Interface (PrivateLink) and costs money."),
      s("real", "Real-world — Lyft Transit Gateway", "real",
        "Lyft connects 30+ VPCs per region to a single TGW. On-prem data centres attach via Direct Connect. New service = new VPC = one TGW attachment, one route table entry. They came from a peering mesh that hit O(N²) connections."),
    ],
  }),
  lesson({
    day: 5, phase: 1, weekInPhase: 1, phaseProgress: 20,
    topic: "EC2 — instance families, pricing, AMIs, user data",
    task: "Launch a t3.micro Amazon Linux 2023 EC2 in your public subnet using a User Data bootstrap that installs httpd and serves a 'hello' page. SSH in. Stop the instance, change instance type to t3.small, restart.",
    depth: "Instance families (t/m/c/r/p/i/g), 5 pricing models, AMIs, user data, IMDSv2",
    source: "AWS EC2 docs · EC2 instance types page · 'EC2 Spot Best Practices' video",
    examWeight: "VERY HIGH — Domain 2 + Domain 4",
    whyMatters: "EC2 is the workhorse. Almost everything else is built on EC2 under the hood. Knowing the family map (t = burstable, m = general, c = compute, r = memory, p/g = GPU, i = NVMe) and the 5 pricing models (On-Demand, Reserved, Savings Plans, Spot, Dedicated) is half of cost optimisation on the exam.",
    howToDoIt: "Pick an AMI (Amazon Linux 2023 is a safe default). Pick instance type (t3.micro for tests, m6i for prod web/app, r6i for memory, c6i for CPU, Graviton g-suffix for ~20% cheaper at equal perf). Configure VPC + subnet + Security Group + Key Pair. Pass a User Data script. Attach an Instance Profile.",
    watchOutFor: "User Data runs ONCE on first boot, as root. To re-run, recreate or `cloud-init clean` + restart. Instance Store (NVMe) is EPHEMERAL — lost on stop/terminate. EBS persists. Always require IMDSv2 (token-based).",
    doneWhen: "Your EC2 serves an HTML page. You can name 5 instance families and one use case for each. You can explain Reserved vs Savings Plans (Savings Plans are more flexible — commit to $/hr, not a specific instance family).",
    examTrap: "Spot can be terminated with a 2-minute warning. Use only for fault-tolerant workloads (batch, ML training, CI). Never for stateful databases. T-family uses CPU credits — sustained 100% CPU exhausts them and throttles you. Use M-family for steady workloads.",
    realWorld: "Shopify on Black Friday uses predictive scaling on ASGs to pre-warm hours before peak. Reserved Instances cover baseline. Spot covers burst at ~90% discount. ALB drains connections gracefully on Spot termination — users never notice.",
    sections: [
      s("families", "Instance families cheat sheet", "concept",
        "• **t3 / t4g** — burstable CPU. Dev/test, low-traffic web.\n• **m6i / m7i** — general purpose. Production web/app servers.\n• **c6i / c7i** — compute optimised. Video encoding, HPC.\n• **r6i / r7i** — memory optimised. In-memory DBs, SAP, Redis.\n• **p3 / p4d / p5** — GPU. ML training, CUDA.\n• **i3 / i4i** — NVMe storage optimised. High-IOPS DBs, Cassandra.\n• **g-suffix (e.g., m7g, c7g)** — Graviton (ARM). ~20% cheaper at equal/better perf."),
      s("pricing", "5 pricing models", "compare",
        "",
        {
          table: {
            headers: ["Model", "Discount", "Commitment", "Best for"],
            rows: [
              ["On-Demand", "0%", "None", "Unpredictable / short-term"],
              ["Reserved (1 yr)", "~40%", "1 year", "Steady-state predictable"],
              ["Reserved (3 yr)", "~60%", "3 years", "Long-running stable baseline"],
              ["Savings Plans", "~66%", "1 or 3 yr", "Flexible — any instance family"],
              ["Spot", "~90%", "None", "Fault-tolerant batch / ML / CI"],
              ["Dedicated Host", "varies", "Optional", "Licensing compliance (BYOL)"],
            ],
          },
        }),
      s("user-data", "Launch with User Data", "config",
        "User Data is a shell script that runs once on first boot as root. Use it to install packages, pull config, and start your service.",
        {
          code: { lang: "bash", source: '#!/bin/bash\nyum update -y\nyum install -y httpd\nsystemctl start httpd\nsystemctl enable httpd\necho "Hello from $(hostname)" > /var/www/html/index.html' },
        }),
      s("launch", "Launch via CLI with Instance Profile", "config",
        "",
        {
          code: { lang: "bash", source: 'aws ec2 run-instances \\\n  --image-id ami-0c02fb55956c7d316 \\\n  --instance-type t3.micro \\\n  --key-name my-keypair \\\n  --subnet-id $PUB1 \\\n  --security-group-ids $WEB_SG \\\n  --iam-instance-profile Name=EC2-S3-ReadProfile \\\n  --user-data file://bootstrap.sh \\\n  --tag-specifications \\\n    "ResourceType=instance,Tags=[{Key=Name,Value=WebServer}]"' },
        }),
      s("traps", "Exam traps", "trap",
        "**Spot = 2-minute warning** before termination. Fault-tolerant only.\n\n**T-family CPU credits** — sustained 100% CPU exhausts credits and gets throttled to baseline. Use t3.unlimited (extra cost) or step up to M.\n\n**Instance Store is EPHEMERAL.** Stop = data gone. Reboot = preserved.\n\n**IMDSv2 only.** v1 has been the source of high-profile breaches."),
      s("real", "Real-world — Shopify Black Friday", "real",
        "Shopify uses predictive scaling, Reserved baseline, Spot burst at 90% off. ALB connection draining means a Spot termination notice doesn't drop a single user request."),
    ],
  }),
  lesson({
    day: 6, phase: 1, weekInPhase: 1, phaseProgress: 24,
    topic: "EC2 — Auto Scaling Groups & Launch Templates",
    task: "Build a Launch Template, then an ASG with min=2 / desired=2 / max=6 spread across 2 AZs, attached to an ALB target group. Add target tracking: scale out when avg CPU > 70%. Stress-test with `stress --cpu 4` and watch the ASG add capacity.",
    depth: "Launch Templates, ASG, scaling policies (target tracking, step, scheduled, predictive), lifecycle hooks",
    source: "AWS Auto Scaling docs · 'EC2 Auto Scaling Deep Dive' video",
    examWeight: "VERY HIGH — Domain 2 (Resilient, 26%)",
    whyMatters: "An ASG gives you elasticity AND high availability — replace failed instances automatically AND scale with load. Foundation of resilient compute. The exam adores it: 'How do you handle a 10x traffic spike?' or 'How do you survive an AZ outage?' almost always answer ASG across 2+ AZs.",
    howToDoIt: "Create a Launch Template (modern replacement for Launch Configurations). Reference it from an ASG. Set min/desired/max. Spread across multiple AZs. Attach to a target group. Add target tracking scaling policy. Set health-check-type=ELB so ALB health checks drive instance replacement.",
    watchOutFor: "Cooldown periods prevent flapping. Health-check grace period gives a new instance time to boot before being marked unhealthy. If User Data takes 5 min, set grace period to 300s. Use Launch Templates, not Launch Configurations (deprecated).",
    doneWhen: "Stress test: instances spawn within ~3 minutes of crossing 70% CPU. Stop the load: instances terminate after cooldown. ALB target group shows healthy instances throughout.",
    examTrap: "ASG replaces unhealthy instances automatically. If a question says 'instance got stuck' and the option is 'manually relaunch', that's wrong — let ASG do it.",
    realWorld: "Netflix's Chaos Monkey kills random EC2 instances during business hours. ASGs replace them within seconds, ALB shifts traffic away. If your architecture can't survive Chaos Monkey, you don't have HA — you have HA on paper.",
    sections: [
      s("concept", "Why ASG", "concept",
        "An Auto Scaling Group does three things: maintains desired capacity (replace failed instances), scales horizontally based on policies (CPU, request count, queue depth), and spreads instances across AZs for resilience."),
      s("template", "Launch Template", "config",
        "",
        {
          code: { lang: "bash", source: 'aws ec2 create-launch-template \\\n  --launch-template-name MyAppTemplate \\\n  --launch-template-data \\\'{"ImageId":"ami-0c02fb55956c7d316","InstanceType":"t3.micro","KeyName":"my-keypair","SecurityGroupIds":["sg-0abc"],"IamInstanceProfile":{"Name":"EC2-S3-ReadProfile"}}\\\'' },
        }),
      s("asg", "Create the ASG", "config",
        "",
        {
          code: { lang: "bash", source: 'aws autoscaling create-auto-scaling-group \\\n  --auto-scaling-group-name MyAppASG \\\n  --launch-template LaunchTemplateName=MyAppTemplate \\\n  --min-size 2 --max-size 6 --desired-capacity 2 \\\n  --vpc-zone-identifier "$PRIV1,$PRIV2" \\\n  --target-group-arns $TG_ARN \\\n  --health-check-type ELB \\\n  --health-check-grace-period 300' },
        }),
      s("policies", "Scaling policies", "concept",
        "• **Target tracking** — pick a metric and target value. Simplest, most common.\n• **Step scaling** — fine-grained 'if metric in band X, change capacity by Y'.\n• **Scheduled scaling** — calendar-based (every weekday 9am: scale to 10).\n• **Predictive scaling** — ML-based; pre-warms capacity before historical patterns predict demand."),
      s("project", "Mini-project — auto-scaled web app", "project",
        "",
        {
          code: { lang: "bash", source: 'aws autoscaling put-scaling-policy \\\n  --auto-scaling-group-name MyAppASG \\\n  --policy-name CPUTargetTracking \\\n  --policy-type TargetTrackingScaling \\\n  --target-tracking-configuration \\\'{"PredefinedMetricSpecification":{"PredefinedMetricType":"ASGAverageCPUUtilization"},"TargetValue":70.0,"ScaleInCooldown":300,"ScaleOutCooldown":60}\\\'\n\n# Generate load on an instance\nsudo yum install -y stress\nstress --cpu 4 --timeout 300' },
        }),
      s("traps", "Exam traps", "trap",
        "**Health-check grace period** — give new instances time to boot before ELB marks unhealthy.\n\n**Lifecycle hooks** let you run custom code before an instance is added/removed (drain connections, run a final backup) — exam loves this.\n\n**Mixed-instance policy** lets one ASG combine On-Demand + Spot for cost-optimised resilience."),
      s("real", "Real-world — Chaos Monkey", "real",
        "Netflix kills random EC2 instances in production during business hours. ASGs replace them within seconds. HA isn't a design — it's something you have to prove by killing things and watching the system recover."),
    ],
  }),
  lesson({
    day: 7, phase: 1, weekInPhase: 1, phaseProgress: 28,
    topic: "S3 — buckets, objects, storage classes",
    task: "Create a bucket. Upload a file. Try every storage class transition (Standard → IA → Glacier). Enable versioning. Delete a file, then restore the previous version. Calculate per-month cost for 1TB across each class.",
    depth: "Buckets, objects, keys, all 7 storage classes, lifecycle rules, versioning",
    source: "AWS S3 docs · S3 storage classes pricing page",
    examWeight: "VERY HIGH — Domain 4 (Cost-Optimised, 20%) + Domain 1",
    whyMatters: "S3 is the most-used AWS service — almost every architecture uses it for something. Understanding the 7 storage classes and their access/cost tradeoffs is direct exam money: 'Which storage class for archives accessed once a year?' = Glacier Deep Archive. 'Which for frequently accessed data with unknown patterns?' = Intelligent-Tiering.",
    howToDoIt: "S3 is flat key-value: a bucket holds objects, each object has a key (the 'path' is just a / in the key, no real folders). Pick a storage class on upload (or use Intelligent-Tiering). Set lifecycle rules to auto-transition. Enable versioning to recover from accidental delete/overwrite.",
    watchOutFor: "S3 has STRONG read-after-write consistency since Dec 2020. Once enabled, versioning can only be SUSPENDED, not disabled. Glacier retrieval has minimums: Standard 3–5 hr, Bulk 5–12 hr, Expedited 1–5 min (extra cost).",
    doneWhen: "You can recite all 7 storage classes and one use case each. You've seen lifecycle move an object to Glacier in your console. Versioning saved you from a delete in a test.",
    examTrap: "S3 is NOT a file system — there are no real folders, just key prefixes. S3 doesn't support file locking (use S3 Object Lock for WORM compliance, or EFS for shared filesystem semantics).",
    realWorld: "Dropbox stores petabytes in S3. Multipart Upload splits files into chunks uploaded in parallel (5MB chunks, must use for files > 5GB). Intelligent-Tiering moves rarely-accessed user files to cheaper tiers automatically.",
    sections: [
      s("intro", "What S3 is", "intro",
        "S3 is AWS's object storage. You store files (objects) in containers (buckets). Each object has a key (the 'path'), a body, and metadata. S3 is global namespace — bucket names are unique across ALL AWS accounts in the world. Objects are immutable once written; to 'modify', you overwrite."),
      s("classes", "All 7 storage classes", "compare",
        "Pick the cheapest class your access pattern allows.",
        {
          table: {
            headers: ["Class", "Use case", "Min duration", "Retrieval", "Relative cost"],
            rows: [
              ["Standard", "Frequently accessed", "None", "Instant", "Highest"],
              ["Intelligent-Tiering", "Unknown / shifting", "None", "Instant", "Standard + monitoring fee"],
              ["Standard-IA", "Infrequent but rapid", "30 d", "Instant", "Lower + retrieval fee"],
              ["One Zone-IA", "Infrequent, recreatable", "30 d", "Instant", "20% less than Standard-IA"],
              ["Glacier Instant", "Archives, quarterly access", "90 d", "Milliseconds", "Very low"],
              ["Glacier Flexible", "Long-term archive", "90 d", "1–12 hr", "Very low"],
              ["Glacier Deep Archive", "7–10 yr compliance", "180 d", "12–48 hr", "Lowest"],
            ],
          },
        }),
      s("lifecycle", "Lifecycle rules", "config",
        "Automate the move from hot to cold.",
        {
          code: { lang: "bash", source: 'aws s3api put-bucket-lifecycle-configuration \\\n  --bucket my-data-bucket \\\n  --lifecycle-configuration \\\'{"Rules":[{"Id":"AutoTier","Status":"Enabled","Transitions":[{"Days":30,"StorageClass":"STANDARD_IA"},{"Days":90,"StorageClass":"GLACIER"},{"Days":365,"StorageClass":"DEEP_ARCHIVE"}],"Expiration":{"Days":2555}}]}\\\'' },
        }),
      s("versioning", "Versioning & MFA Delete", "config",
        "Versioning preserves every version of every object — overwrites and deletes become new versions, not destruction. You can recover from human error and from ransomware.",
        {
          code: { lang: "bash", source: '# Enable versioning\naws s3api put-bucket-versioning \\\n  --bucket my-bucket \\\n  --versioning-configuration Status=Enabled\n\n# List versions\naws s3api list-object-versions --bucket my-bucket --prefix myfile.txt\n\n# Restore a specific version\naws s3api get-object --bucket my-bucket --key myfile.txt \\\n  --version-id ABC123xyz restored.txt' },
        }),
      s("traps", "Exam traps", "trap",
        "**Strong consistency since Dec 2020.** Old materials say 'eventual' — out of date.\n\n**Cross-Region Replication (CRR)** requires versioning on BOTH source and destination, is asynchronous, and does NOT replicate existing objects.\n\n**Multipart Upload** required for objects > 5 GB; recommended for > 100 MB. Transfer Acceleration uses CloudFront edge locations to speed uploads."),
      s("real", "Real-world — Dropbox", "real",
        "Dropbox stores petabytes in S3. Multipart Upload runs in parallel for big files. Intelligent-Tiering tiers rarely-accessed user files. Event Notifications trigger Lambda chains: thumbnail generation, virus scanning, search indexing."),
    ],
  }),
  lesson({
    day: 8, phase: 1, weekInPhase: 1, phaseProgress: 32,
    topic: "S3 — encryption, access control, static website hosting",
    task: "Make a bucket secure: block public access, force SSE-KMS via bucket policy (deny if encryption header missing), enable access logging. Then deploy a static site to a SECOND bucket via S3 + CloudFront with Origin Access Control.",
    depth: "Bucket policies, ACLs, Block Public Access, SSE-S3 vs SSE-KMS vs SSE-C, presigned URLs, static hosting, OAC",
    source: "AWS S3 Security Best Practices · 'Static Sites with CloudFront' tutorial",
    examWeight: "VERY HIGH — Domain 1",
    whyMatters: "Most S3 horror stories (Verizon, Accenture, FedEx leaks) came from misconfigured permissions. Knowing how Block Public Access, bucket policies, ACLs, and CloudFront OAC interact is foundational. KMS encryption gives per-key audit trails (CloudTrail logs every Decrypt) — critical for compliance.",
    howToDoIt: "Default deny. Always turn on Block Public Access at the account AND bucket level unless you explicitly need a public bucket. Enable default encryption (SSE-S3 free, SSE-KMS for audit trails). Use bucket policies for granular access. For private content served to web users, use presigned URLs (time-limited).",
    watchOutFor: "ACLs are legacy — prefer bucket policies. The 4 Block Public Access settings have nuances. Bucket policies and IAM policies both apply; the union of allows minus any explicit deny.",
    doneWhen: "Try to upload an unencrypted object — it fails. Try to make the bucket public — it's blocked. Your CloudFront-fronted bucket serves a static site over HTTPS, but you cannot reach the bucket directly via its S3 URL.",
    examTrap: "If a question lists 'public bucket policy' as the answer for serving web content, it's wrong. The right answer is S3 + CloudFront + OAC (Origin Access Control), bucket private.",
    realWorld: "Pinterest serves billions of pin images via CloudFront + S3 + OAC. Buckets are private; CloudFront is the only thing that can read. Engineers can't bypass the CDN — cache invalidation IS the deploy mechanism.",
    sections: [
      s("encryption", "Encryption at rest — 3 options", "compare",
        "• **SSE-S3** — AWS-managed keys. Free. Single key per bucket. Default in 2023+.\n• **SSE-KMS** — KMS-managed keys (AWS-managed or customer-managed). Per-call CloudTrail audit. Slight cost.\n• **SSE-C** — customer-provided keys. You send the key per request. AWS doesn't store it. Niche use case."),
      s("policy", "Bucket policy: deny unencrypted uploads", "config",
        "A bucket policy with Deny on PutObject when the encryption header is missing or wrong. Deny wins over any Allow.",
        {
          code: { lang: "json", source: '{\n  "Version": "2012-10-17",\n  "Statement": [{\n    "Sid": "DenyUnencryptedUploads",\n    "Effect": "Deny",\n    "Principal": "*",\n    "Action": "s3:PutObject",\n    "Resource": "arn:aws:s3:::my-secure-bucket/*",\n    "Condition": {\n      "StringNotEquals": {\n        "s3:x-amz-server-side-encryption": "aws:kms"\n      }\n    }\n  }]\n}' },
        }),
      s("project", "Mini-project — static site behind CloudFront", "project",
        "Deploy a static site to S3, front it with CloudFront for HTTPS + global CDN, lock the bucket private with OAC.",
        {
          code: { lang: "bash", source: '# 1. Create bucket + sync site\naws s3 mb s3://my-static-site-12345\naws s3 sync ./website/ s3://my-static-site-12345/\n\n# 2. Block all public access (CloudFront reaches via OAC)\naws s3api put-public-access-block \\\n  --bucket my-static-site-12345 \\\n  --public-access-block-configuration \\\n  "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"\n\n# 3. Create CloudFront distribution with OAC pointing at the bucket\n#    (UI flow recommended). The OAC IAM policy is auto-attached\n#    so only this distribution can read.' },
        }),
      s("presigned", "Presigned URLs", "concept",
        "A presigned URL is a time-limited URL signed with your AWS credentials that lets a client upload or download an object directly to/from S3 without going through your backend. Default expiry 15 min; max 7 days for SigV4."),
      s("traps", "Exam traps", "trap",
        "**Block Public Access** has 4 settings — know what each does.\n\n**OAC > OAI.** Origin Access Identity is legacy; Origin Access Control is the modern replacement (supports KMS-encrypted buckets, all S3 operations).\n\n**S3 Object Lock** — WORM (Write Once Read Many) for compliance (SEC 17a-4). Two modes: Governance (admins can override) and Compliance (no one can override, even root)."),
      s("real", "Real-world — Pinterest", "real",
        "Pinterest serves billions of images via CloudFront + private S3 + OAC. Cache invalidation IS the deploy mechanism."),
    ],
  }),
  lesson({
    day: 9, phase: 1, weekInPhase: 2, phaseProgress: 36,
    topic: "EBS — Elastic Block Store",
    task: "Attach a 100 GB gp3 volume to an EC2. Format ext4. Mount. Take a snapshot. Detach the volume. Create a new volume from the snapshot in another AZ. Attach to a new EC2 and confirm the data transferred.",
    depth: "EBS volume types (gp3, gp2, io2, st1, sc1), snapshots, encryption, Multi-Attach, AZ scope",
    source: "AWS EBS docs · EBS volume comparison page",
    examWeight: "HIGH — Domain 2 + Domain 3",
    whyMatters: "EBS is network-attached block storage for EC2 — persists independently of the instance. Picking the right volume type (gp3 default, io2 for mission-critical DBs, st1 for big throughput, sc1 for cold) is straight cost and performance optimisation.",
    howToDoIt: "Create a volume in the SAME AZ as your EC2. Attach it. Inside the OS, format and mount. To move data across AZs: snapshot → restore in target AZ. Snapshots are stored in S3 (managed by AWS). Encryption is per-volume; default-encrypt every volume in production.",
    watchOutFor: "EBS volumes are tied to ONE AZ. To move them, snapshot and restore. gp3 is the default in 2023+ (cheaper than gp2 at the same baseline). Multi-Attach (io1/io2 only, same AZ, cluster-aware FS required) lets one volume attach to up to 16 instances.",
    doneWhen: "You can restore a snapshot in another AZ. You know latency / throughput numbers for gp3, io2, st1. You've enabled default encryption at the account level.",
    examTrap: "Move data across AZs = snapshot + restore. Move data across regions = copy snapshot to target region. EBS is single-AZ; EFS is multi-AZ.",
    realWorld: "Most production databases on EC2 (self-managed Postgres, Mongo, Cassandra) sit on io2 Block Express for guaranteed IOPS. Snapshots are scheduled via Data Lifecycle Manager, encrypted with KMS, replicated to a DR region.",
    sections: [
      s("intro", "What EBS is", "intro",
        "EBS is network-attached block storage that behaves like a local hard drive. Tied to one Availability Zone. Persists independently of the EC2 lifecycle — terminate the instance, the volume can stay (or be deleted, depending on DeleteOnTermination)."),
      s("types", "Volume types", "compare",
        "",
        {
          table: {
            headers: ["Type", "IOPS", "Throughput", "Use case"],
            rows: [
              ["gp3 (general SSD)", "Up to 16 000", "1 000 MB/s", "Default — boot, most workloads"],
              ["gp2 (older SSD)", "Up to 16 000", "250 MB/s", "Older default — prefer gp3"],
              ["io2 Block Express", "Up to 256 000", "4 000 MB/s", "Mission-critical DBs, Oracle, SAP"],
              ["st1 (throughput HDD)", "—", "500 MB/s", "Big-data / log streaming"],
              ["sc1 (cold HDD)", "—", "250 MB/s", "Infrequently accessed, cheapest"],
            ],
          },
        }),
      s("snapshots", "Snapshots", "config",
        "Snapshots are incremental block-level backups stored in S3 (managed by AWS). The first snapshot is full; subsequent ones store only changed blocks.",
        {
          code: { lang: "bash", source: '# Snapshot\nSNAP=$(aws ec2 create-snapshot --volume-id vol-0abc \\\n  --description nightly --query SnapshotId --output text)\n\n# Wait for snapshot to complete\naws ec2 wait snapshot-completed --snapshot-ids $SNAP\n\n# Restore in another AZ\naws ec2 create-volume --snapshot-id $SNAP \\\n  --availability-zone us-east-1b --volume-type gp3 --size 100\n\n# Copy snapshot to another region (DR)\naws ec2 copy-snapshot --source-region us-east-1 \\\n  --source-snapshot-id $SNAP --destination-region us-west-2 --encrypted' },
        }),
      s("traps", "Exam traps", "trap",
        "**EBS = single AZ.** Move = snapshot + restore.\n\n**Multi-Attach** (io1/io2 only, same AZ, cluster-aware FS).\n\n**Default encryption** — enable at account level so all new volumes are encrypted.\n\n**RAID 0** for performance; RAID 1 unnecessary because EBS is already replicated within the AZ.\n\n**Volume type change is online** — you can change gp3 ↔ io2 without downtime."),
      s("real", "Real-world — self-managed DB on io2", "real",
        "When teams need extreme IOPS or features RDS doesn't support, they run Postgres/Mongo on EC2 with io2 Block Express. Data Lifecycle Manager schedules nightly KMS-encrypted snapshots and copies them to a DR region."),
    ],
  }),
  lesson({
    day: 10, phase: 1, weekInPhase: 2, phaseProgress: 40,
    topic: "EFS, FSx & Storage Gateway",
    task: "Provision an EFS file system. Create mount targets in 2 AZs. Mount it on two EC2s in different AZs simultaneously. From instance A write a file; read it from instance B.",
    depth: "EFS (NFS), FSx for Windows / Lustre / NetApp ONTAP / OpenZFS, Storage Gateway",
    source: "AWS EFS docs · 'Choosing AWS Storage Services' whitepaper",
    examWeight: "HIGH — Domain 3",
    whyMatters: "EFS is shared file system for Linux fleets. FSx covers Windows / HPC / NetApp / ZFS. Storage Gateway is the on-prem-to-AWS bridge. The exam keys off use cases: 'Shared content for a fleet of EC2s' = EFS. 'Lift-and-shift Windows file share' = FSx for Windows. 'High-throughput parallel filesystem' = FSx for Lustre.",
    howToDoIt: "EFS: create the file system, mount targets in each AZ (one per AZ, with a Security Group allowing NFS port 2049). Mount with `mount -t efs fs-id:/ /mnt/shared`. Use Provisioned Throughput for predictable performance, Bursting for default.",
    watchOutFor: "EFS is REGIONAL (multi-AZ); EBS is single-AZ. Don't confuse Multi-Attach EBS (same AZ, up to 16 instances, cluster FS) with EFS (multi-AZ, unlimited clients, NFS).",
    doneWhen: "Two EC2s in different AZs share the same file system. You can recite when to use EFS vs FSx vs Storage Gateway.",
    examTrap: "'Shared file storage across multiple EC2s in different AZs' → EFS, never EBS. 'High-IOPS DB storage for one EC2' → EBS io2. 'Temporary, ultra-fast scratch' → Instance Store.",
    realWorld: "Many enterprises use FSx for Windows to lift-and-shift file servers without rewriting the Windows app stack. Storage Gateway bridges remaining on-prem workloads — SMB clients see a local share, the data tiers to S3 + Glacier transparently.",
    sections: [
      s("efs", "EFS", "concept",
        "Elastic File System — managed NFS v4 that scales automatically. Mount targets per AZ. Pay per GB stored, no provisioning. Ideal for shared content across a Linux fleet."),
      s("fsx", "FSx family", "compare",
        "",
        {
          table: {
            headers: ["FSx variant", "Protocol", "Use case"],
            rows: [
              ["FSx for Windows", "SMB", "Lift-and-shift Windows shares (AD, DFS)"],
              ["FSx for Lustre", "POSIX", "HPC, ML training, parallel scratch"],
              ["FSx for NetApp ONTAP", "NFS, SMB, iSCSI", "Multi-protocol, lift-and-shift NetApp"],
              ["FSx for OpenZFS", "NFS", "ZFS features (snapshots, clones)"],
            ],
          },
        }),
      s("gateway", "Storage Gateway", "concept",
        "On-prem-to-AWS bridge.\n• **File Gateway** — on-prem mounts S3 as SMB/NFS, hot files cached locally.\n• **Volume Gateway** — on-prem mounts as iSCSI; data tiered to S3.\n• **Tape Gateway** — virtual tape library backed by S3 + Glacier."),
      s("project", "Mini-project — shared EFS across AZs", "project",
        "",
        {
          code: { lang: "bash", source: '# 1. Create EFS file system\nEFS=$(aws efs create-file-system --performance-mode generalPurpose \\\n  --throughput-mode bursting --encrypted \\\n  --query FileSystemId --output text)\n\n# 2. Mount targets in each AZ\naws efs create-mount-target --file-system-id $EFS \\\n  --subnet-id $PRIV1 --security-groups $EFS_SG\naws efs create-mount-target --file-system-id $EFS \\\n  --subnet-id $PRIV2 --security-groups $EFS_SG\n\n# 3. Mount on each EC2\nsudo yum install -y amazon-efs-utils\nsudo mkdir /mnt/shared\nsudo mount -t efs $EFS:/ /mnt/shared' },
        }),
      s("traps", "Exam traps", "trap",
        "**EFS = multi-AZ, multi-client.** EBS = single-AZ.\n\n**EFS storage classes** — Standard (multi-AZ, default), One Zone (single-AZ, ~47% cheaper). IA tiers via lifecycle.\n\n**FSx for Lustre** has S3 integration — read straight from S3 as if it were the filesystem; ideal for ML jobs against a data lake."),
      s("real", "Real-world — FSx Windows lift-and-shift", "real",
        "Enterprises lift-and-shift Windows file servers to FSx for Windows: same SMB, same Active Directory, no app rewrite."),
    ],
  }),
  lesson({
    day: 11, phase: 1, weekInPhase: 2, phaseProgress: 44,
    topic: "AWS CLI & CloudShell — fluency",
    task: "Install AWS CLI v2 locally. Configure with named profiles for two accounts. Use JMESPath `--query` to filter outputs. Open CloudShell — note that creds are auto-loaded.",
    depth: "AWS CLI v2 install / config, named profiles, JMESPath queries, CloudShell, output formats",
    source: "AWS CLI v2 docs · jmespath.org · CloudShell user guide",
    examWeight: "MEDIUM — used across all domains",
    whyMatters: "Console clicks don't scale. The CLI is how you script, audit, and reproduce AWS state. JMESPath turns 'huge JSON dump' into 'just the 5 fields I want'. Named profiles let you switch between dev/staging/prod without re-running `aws configure`.",
    howToDoIt: "Install CLI v2 (NOT v1 — different commands and slower). `aws configure --profile production` for each account. Use `--query` with JMESPath expressions to filter, `--output table` for human-readable, `--output json` for machine-parseable. CloudShell is the in-browser terminal with credentials auto-loaded.",
    watchOutFor: "Two CLI versions exist; always use v2. Profiles live in `~/.aws/config` and credentials in `~/.aws/credentials`. For SSO, use `aws sso login --profile prod`. CloudShell has 1 GB persistent home dir per region and is free.",
    doneWhen: "You can list all running EC2 instance IDs with one command. You can flip between two profiles with `--profile`.",
    examTrap: "Credentials precedence: env vars > ~/.aws/credentials > Instance Profile (on EC2). A leaked env var on a build server has burned more companies than misconfigured S3.",
    realWorld: "SREs live in the CLI. Production change reviews include the exact CLI command + the expected output. CloudShell is the break-glass option: locked out of your laptop, log into the console with MFA, open CloudShell, run the rollback.",
    sections: [
      s("install", "Install + configure", "config",
        "",
        {
          code: { lang: "bash", source: '# Install on Linux\ncurl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip\nunzip awscliv2.zip && sudo ./aws/install\n\n# Configure\naws configure\n# AWS Access Key ID:     AKIA...\n# AWS Secret Access Key: ...\n# Default region:        us-east-1\n# Default output format: json\n\n# Named profiles for multi-account\naws configure --profile production\naws s3 ls --profile production' },
        }),
      s("jmespath", "JMESPath — filter the firehose", "config",
        "Every CLI command returns JSON. JMESPath via `--query` turns it into exactly what you want.",
        {
          code: { lang: "bash", source: '# All running instance IDs as a table\naws ec2 describe-instances \\\n  --filters "Name=instance-state-name,Values=running" \\\n  --query "Reservations[*].Instances[*].[InstanceId,InstanceType,State.Name]" \\\n  --output table\n\n# Just public IPs, one per line\naws ec2 describe-instances \\\n  --query "Reservations[].Instances[].PublicIpAddress" \\\n  --output text' },
        }),
      s("cloudshell", "CloudShell", "concept",
        "Browser-based terminal in the AWS console with the CLI pre-installed and credentials auto-loaded from your console session. 1 GB persistent home per region. Free. Use it for: quick scripts, break-glass rollback, copying files between buckets without leaving the browser."),
      s("traps", "Exam traps", "trap",
        "**Credentials precedence** — env vars override ~/.aws/credentials, which overrides Instance Profile.\n\n**SSO** — modern teams use `aws sso login --profile X` instead of access keys.\n\n**Output format** — text and table for humans, json for `jq`/scripts."),
      s("real", "Real-world — change reviews", "real",
        "Mature teams require change reviews to include the exact CLI command and expected output. CloudShell is break-glass: laptop dead, walk to a colleague, log in with MFA, run the rollback."),
    ],
  }),
  lesson({
    day: 12, phase: 1, weekInPhase: 2, phaseProgress: 48,
    topic: "Boto3 — Python SDK for AWS",
    task: "Write a Python script with Boto3 that lists all EC2 instances across all regions, prints state/type/public IP, and writes a CSV. Use pagination so it works in accounts with > 1000 instances.",
    depth: "Boto3 client vs resource API, pagination, retries, region iteration",
    source: "Boto3 docs · 'Boto3 Pagination' AWS guide",
    examWeight: "LOW (knowing it exists is enough for the exam)",
    whyMatters: "Boto3 is how Python apps talk to AWS. Lambda functions, data scripts, Glue jobs, automation tools — all Boto3. Pagination is the trap that bites everyone: the default page size hides results in big accounts.",
    howToDoIt: "Install boto3. Use `boto3.client('ec2')` for low-level (1:1 with the API) or `boto3.resource('s3')` for higher-level (Pythonic). Always use Paginators for list/describe operations. Iterate regions via `ec2.describe_regions()`.",
    watchOutFor: "`describe_instances()` returns at most 1000 results unless you paginate. `boto3.resource()` doesn't exist for every service. Retries are configurable — for production set adaptive mode + a max attempts.",
    doneWhen: "Your script handles 1000+ instances correctly. You can switch between profiles via Session.",
    examTrap: "When asked 'how do I list 5000 EC2 instances', the right answer involves PAGINATION, not increasing the page size.",
    realWorld: "Most internal AWS tools at most companies are 200-line Boto3 scripts: nightly snapshot pruners, IAM access reports, cost allocators by tag.",
    sections: [
      s("client", "Client API", "config",
        "",
        {
          code: { lang: "python", source: 'import boto3\n\nec2 = boto3.client("ec2", region_name="us-east-1")\n\nresponse = ec2.describe_instances(\n    Filters=[{"Name": "instance-state-name", "Values": ["running"]}]\n)\nfor reservation in response["Reservations"]:\n    for instance in reservation["Instances"]:\n        print(f"{instance[\'InstanceId\']} - {instance[\'InstanceType\']}")' },
        }),
      s("paginator", "Paginators — handle big accounts", "config",
        "",
        {
          code: { lang: "python", source: 'paginator = ec2.get_paginator("describe_instances")\nfor page in paginator.paginate(\n    Filters=[{"Name": "instance-state-name", "Values": ["running"]}]\n):\n    for reservation in page["Reservations"]:\n        for instance in reservation["Instances"]:\n            print(instance["InstanceId"])' },
        }),
      s("project", "Mini-project — multi-region inventory CSV", "project",
        "",
        {
          code: { lang: "python", source: 'import boto3, csv\n\nsession = boto3.Session(profile_name="production")\nec2_global = session.client("ec2", region_name="us-east-1")\nregions = [r["RegionName"] for r in ec2_global.describe_regions()["Regions"]]\n\nwith open("inventory.csv", "w", newline="") as f:\n    writer = csv.writer(f)\n    writer.writerow(["Region", "InstanceId", "Type", "State", "PublicIp"])\n    for region in regions:\n        ec2 = session.client("ec2", region_name=region)\n        paginator = ec2.get_paginator("describe_instances")\n        for page in paginator.paginate():\n            for r in page["Reservations"]:\n                for i in r["Instances"]:\n                    writer.writerow([\n                        region, i["InstanceId"], i["InstanceType"],\n                        i["State"]["Name"], i.get("PublicIpAddress", "")\n                    ])' },
        }),
      s("traps", "Production traps", "trap",
        "**Always paginate.** describe_* returns at most 1000 by default.\n\n**Adaptive retries.** `Config(retries={'mode': 'adaptive', 'max_attempts': 5})` for production.\n\n**Don't pickle Boto3 clients across processes.** Threads OK, multiprocessing not OK."),
      s("real", "Real-world — internal tools", "real",
        "Most companies' AWS automation is unsexy 200-line Boto3 scripts: snapshot pruners, access reports, cost allocators."),
    ],
  }),
  lesson({
    day: 13, phase: 1, weekInPhase: 2, phaseProgress: 52,
    topic: "CloudFormation — IaC fundamentals",
    task: "Write a CloudFormation template that creates a VPC + 2 public subnets + IGW + Security Group + EC2 in YAML. Deploy with `aws cloudformation create-stack`. Use Parameters for environment, Mappings for AMI per region, and Outputs to print the EC2 public IP.",
    depth: "Templates (YAML/JSON), Stacks, Parameters, Mappings, Conditions, Resources, Outputs, Pseudo Parameters",
    source: "AWS CloudFormation User Guide",
    examWeight: "HIGH — Domain 1 + Domain 2",
    whyMatters: "Click-ops doesn't scale or reproduce. CloudFormation makes infra a versioned artefact in git: every change is a code review, every environment is identical, every deploy is a stack update with automatic rollback on failure.",
    howToDoIt: "Write a YAML template (Resources is required, everything else optional). `aws cloudformation create-stack` to deploy. Parameters for things that change per environment. Mappings for static lookups. Conditions for resources that exist in some envs only. Outputs to expose values.",
    watchOutFor: "Stack DELETE removes ALL resources, including RDS — use `DeletionPolicy: Retain` on data resources. Stack drift detects manual changes from console; run weekly. ChangeSets preview what an update will do.",
    doneWhen: "You can deploy your template, see the EC2 public IP in Outputs, update the stack to a different instance type, and roll back automatically if it fails.",
    examTrap: "If you delete a stack and your RDS goes with it, you didn't have `DeletionPolicy: Retain` (or termination protection).",
    realWorld: "Most large enterprises layer their stacks: networking stack (VPC), security stack (IAM, KMS), platform stack (clusters), app stack (ECS service). Cross-stack references via Outputs/Imports.",
    sections: [
      s("template", "Template anatomy", "config",
        "Six sections: Parameters, Mappings, Conditions, Resources (REQUIRED), Outputs, Metadata. Use YAML for readability.",
        {
          code: { lang: "yaml", source: 'AWSTemplateFormatVersion: "2010-09-09"\nDescription: "3-tier Web App"\n\nParameters:\n  EnvironmentType:\n    Type: String\n    AllowedValues: [dev, staging, prod]\n    Default: dev\n  InstanceType:\n    Type: String\n    Default: t3.micro\n\nMappings:\n  AmiMap:\n    us-east-1: { AMI: ami-0c02fb55956c7d316 }\n    us-west-2: { AMI: ami-0e1bed4f06a3b463d }\n\nConditions:\n  IsProd: !Equals [!Ref EnvironmentType, prod]\n\nResources:\n  WebSG:\n    Type: AWS::EC2::SecurityGroup\n    Properties:\n      GroupDescription: Web tier\n      VpcId: !Ref MyVPC\n      SecurityGroupIngress:\n        - IpProtocol: tcp\n          FromPort: 443\n          ToPort: 443\n          CidrIp: 0.0.0.0/0\n\n  WebServer:\n    Type: AWS::EC2::Instance\n    Properties:\n      ImageId: !FindInMap [AmiMap, !Ref AWS::Region, AMI]\n      InstanceType: !Ref InstanceType\n\nOutputs:\n  WebServerPublicIP:\n    Value: !GetAtt WebServer.PublicIp' },
        }),
      s("deploy", "Deploy / update / delete", "config",
        "",
        {
          code: { lang: "bash", source: '# Validate first\naws cloudformation validate-template --template-body file://template.yaml\n\n# Create\naws cloudformation create-stack \\\n  --stack-name MyWebApp --template-body file://template.yaml \\\n  --parameters ParameterKey=EnvironmentType,ParameterValue=prod \\\n  --capabilities CAPABILITY_NAMED_IAM \\\n  --on-failure ROLLBACK\n\n# Update\naws cloudformation update-stack --stack-name MyWebApp \\\n  --template-body file://updated.yaml \\\n  --parameters ParameterKey=InstanceType,ParameterValue=t3.small\n\n# Delete (CAUTION — removes ALL resources)\naws cloudformation delete-stack --stack-name MyWebApp' },
        }),
      s("traps", "Exam traps", "trap",
        "**Stack delete = resource delete** unless `DeletionPolicy: Retain` is set. Always set Retain on data (RDS, S3, DynamoDB).\n\n**Termination Protection** prevents accidental delete.\n\n**ChangeSets** preview an update before commit.\n\n**Drift detection** catches manual console changes."),
      s("real", "Real-world — StackSets", "real",
        "StackSets deploy a single template across multiple accounts AND regions in one operation. Used for AWS Organizations baselines."),
    ],
  }),
  lesson({
    day: 14, phase: 1, weekInPhase: 2, phaseProgress: 56,
    topic: "CloudFormation — nested stacks, StackSets, alternatives (CDK, Terraform)",
    task: "Refactor yesterday's monolithic template into nested stacks: networking-stack.yaml + app-stack.yaml + db-stack.yaml. Cross-reference via Outputs/Imports. Then explore CDK with a 30-line TypeScript equivalent.",
    depth: "Nested stacks, StackSets, cross-stack references, drift, CDK vs CloudFormation vs Terraform",
    source: "AWS CloudFormation Nested Stacks docs · CDK workshop",
    examWeight: "MEDIUM — Domain 1",
    whyMatters: "Real systems have 30+ resources. Split by concern (network, app, data). StackSets fan out across accounts. CDK gives you real programming-language ergonomics on top of CloudFormation.",
    howToDoIt: "Split by lifecycle: things that rarely change (VPC) into a parent; things that change often (app version) into children. Reference via `!ImportValue` or pass parameters into nested stacks. CDK in TypeScript/Python synthesizes to CloudFormation — same blast radius, way better DX.",
    watchOutFor: "Cross-stack imports are immutable: once exported and imported, you can't change the export's name without breaking the importer. Use parameters when you need flexibility.",
    doneWhen: "You can split a monolith into nested stacks. You've used StackSets to deploy to 2 accounts. You've written a CDK app and `cdk synth`'d the CloudFormation.",
    examTrap: "StackSets are the answer for 'apply this template across all 50 accounts in our Organization'. Not Lambda, not scripts — StackSets.",
    realWorld: "Most modern AWS shops use either CDK (AWS-native, better DX) or Terraform (multi-cloud, vast module ecosystem).",
    sections: [
      s("nested", "Nested stacks", "concept",
        "A nested stack is a Resource of type `AWS::CloudFormation::Stack` whose `TemplateURL` points to another template in S3. The parent owns the children's lifecycle."),
      s("crossref", "Cross-stack references", "config",
        "",
        {
          code: { lang: "yaml", source: '# Stack A exports\nOutputs:\n  VPCID:\n    Value: !Ref MyVPC\n    Export:\n      Name: NetworkStack-VPCID\n\n# Stack B imports\nResources:\n  AppSG:\n    Type: AWS::EC2::SecurityGroup\n    Properties:\n      VpcId: !ImportValue NetworkStack-VPCID' },
        }),
      s("stacksets", "StackSets", "concept",
        "Deploy ONE template to multiple accounts AND regions in one operation. Driven from a delegated admin account in AWS Organizations. The standard answer for org-wide baselines."),
      s("alt", "CloudFormation vs CDK vs Terraform", "compare",
        "",
        {
          table: {
            headers: ["Tool", "Language", "Multi-cloud", "When to use"],
            rows: [
              ["CloudFormation", "YAML/JSON", "AWS only", "Existing CFN shops, SAM apps"],
              ["CDK", "TS / Python / Java / Go", "AWS only (synth → CFN)", "AWS-only shops wanting real-language DX"],
              ["Terraform", "HCL", "Yes", "Multi-cloud or large module ecosystem needed"],
              ["Pulumi", "TS / Python / Go", "Yes", "Pulumi shops"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**StackSets** = multi-account multi-region.\n\n**SAM is a CFN superset** for serverless — `Transform: AWS::Serverless-2016-10-31`."),
      s("real", "Real-world — CDK adoption", "real",
        "Most modern AWS-only shops have moved to CDK. Real types, real loops, real conditional logic instead of CFN's quirky intrinsics."),
    ],
  }),
  review(15, 1, 2, 60,
    "Phase 1 review — Foundation",
    "Re-deploy a complete 3-tier VPC + EC2 + S3 + IAM with CloudFormation in under 30 minutes. Read 5 SAA-C03 sample questions on Domain 1. Note any gaps and revisit those days."),
];
