import type { AwsDay } from "@/types";
import { s, lesson, capstone } from "./section-helpers";

// PHASE 6 — ARCHITECTURE PATTERNS (Days 73–82)
export const PHASE_6: AwsDay[] = [
  lesson({
    day: 73, phase: 6, weekInPhase: 1, phaseProgress: 10,
    topic: "High Availability — multi-AZ design principles",
    task: "Audit yesterday's 3-tier app: is every layer multi-AZ? ALB across 2 AZs, ASG with min=2 in 2 AZs, RDS Multi-AZ, ElastiCache replicas in another AZ. Fix anything that isn't.",
    depth: "SPOFs, multi-AZ for every layer, statelessness, health checks, graceful degradation",
    source: "AWS Well-Architected Reliability Pillar",
    examWeight: "VERY HIGH — Domain 2",
    whyMatters: "HA means surviving the failure of any single component without users noticing. The rule: NO Single Point of Failure. Every layer — compute, DB, cache, networking — must be redundant. The exam keys hard on this — half of Domain 2 is HA scenarios.",
    howToDoIt: "Compute: ASG across 2+ AZs behind ALB (also 2+ AZs). DB: RDS / Aurora Multi-AZ. Cache: ElastiCache replicas in different AZs with auto-failover. Storage: S3 (already 3-AZ), EFS (multi-AZ), EBS (snapshot for cross-AZ). Make services STATELESS — session in ElastiCache or DynamoDB, not on disk.",
    watchOutFor: "Multi-AZ ≠ multi-region. An AWS region outage still kills you (rare but happens). Stateless apps + ALB health checks + ASG = self-healing within a region.",
    doneWhen: "You can kill any single instance / AZ / replica and the system stays up. Whiteboard test: 'AZ us-east-1a is gone right now' — what breaks? Nothing.",
    examTrap: "Anything single-AZ in a 'high availability' question is wrong. EBS single-AZ → EFS or snapshots for HA. Single RDS instance → Multi-AZ.",
    realWorld: "Netflix's Chaos Monkey verifies HA daily by killing random instances. AWS itself runs game days that kill entire AZs in test environments. Real HA is something you prove, not design.",
    sections: [
      s("rules", "HA rules", "concept",
        "1. Eliminate Single Points of Failure (SPOFs).\n2. Every layer redundant — compute, DB, cache, network, storage.\n3. Services stateless — session in shared store, never local disk.\n4. Health checks at every layer drive automatic replacement.\n5. ASGs / Aurora / ElastiCache auto-replace failed components."),
      s("topology", "Standard 3-tier multi-AZ", "concept",
        "Region (e.g., us-east-1):\n• Route 53 → CloudFront → WAF on ALB\n• ALB across 2 AZs\n• ASG min=2 spread across 2 AZs\n• Aurora Multi-AZ writer + reader\n• ElastiCache primary + replica in different AZ\n• EFS multi-AZ for shared content\n• S3 (already 3-AZ replicated)"),
      s("stateless", "Statelessness", "concept",
        "Sessions in ElastiCache / DynamoDB. Uploaded files to S3, not local disk. Logs to CloudWatch / Firehose, not /var/log files (or to both). Restart-safe — any instance can serve any request."),
      s("traps", "Exam traps", "trap",
        "**Multi-AZ ≠ multi-region.** Region outage = need DR.\n\n**EBS is single-AZ.** Use EFS for shared cross-AZ filesystem.\n\n**RDS Multi-AZ failover is invisible** — apps just reconnect to the same endpoint."),
      s("real", "Real-world — Chaos Engineering", "real",
        "Netflix kills random instances daily. AWS internal game days kill AZs. Real HA is proven by killing things in production-like environments."),
    ],
  }),
  lesson({
    day: 74, phase: 6, weekInPhase: 1, phaseProgress: 20,
    topic: "Multi-region patterns",
    task: "Sketch all 4 DR strategies for the 3-tier app: which AWS services, what RTO/RPO, monthly cost. Pick a 'right' one for: hobby site, e-commerce, bank trading desk.",
    depth: "Multi-region read replicas, Aurora Global DB, S3 CRR, DynamoDB Global Tables, Route 53 failover",
    source: "AWS Multi-Region Architectures whitepaper",
    examWeight: "VERY HIGH — Domain 2",
    whyMatters: "Multi-region survives a region outage. Aurora Global DB does cross-region sub-second replication. DynamoDB Global Tables are active-active. S3 CRR replicates buckets. Route 53 failover policy flips DNS on health-check failure. Knowing how to wire these is half of senior architect work.",
    howToDoIt: "Pick strategy based on RTO/RPO budget (revisit Day 67). Common pieces: Aurora Global DB OR DynamoDB Global Tables for data. S3 CRR for buckets. Route 53 failover or latency policies for DNS. Replicate IAM / KMS via Multi-Region keys. Replicate Lambda code, ECS task defs via CFN StackSets.",
    watchOutFor: "Cross-region copies cost egress + storage at destination. KMS keys are regional — use Multi-Region Keys or re-encrypt in target. Stateful resources are hardest (sessions, cache) — keep them region-local and live with the failover state-loss.",
    doneWhen: "You can describe a complete multi-region active-passive design for a 3-tier app including all data replication.",
    examTrap: "'Cross-region MySQL active-active' = Aurora Global DB (NOT regular read replica — those are async one-way).",
    realWorld: "Most production apps eventually go multi-region. Aurora Global DB + Route 53 failover is the canonical Warm Standby pattern.",
    sections: [
      s("data", "Multi-region data replication", "compare",
        "",
        {
          table: {
            headers: ["Service", "Mechanism", "Lag"],
            rows: [
              ["Aurora Global DB", "Storage-level cross-region", "< 1 s"],
              ["DynamoDB Global Tables", "Multi-region active-active", "< 1 s"],
              ["S3 Cross-Region Replication", "Async per-object", "Minutes"],
              ["RDS cross-region read replica", "Async logical", "Seconds–minutes"],
              ["ElastiCache Global Datastore", "Cross-region Redis replication", "< 1 s"],
            ],
          },
        }),
      s("dns", "Route 53 + health checks", "concept",
        "Route 53 failover policy with health checks on primary. Secondary record points to DR region. TTL short (~60 s) so DNS flips fast. Combine with `EvaluateTargetHealth` on Alias records for automatic flip."),
      s("traps", "Exam traps", "trap",
        "**Aurora Global DB ≠ Aurora cross-region read replica** (different products).\n\n**Multi-Region KMS Keys** so the same encrypted snapshot works in both regions.\n\n**DynamoDB Global Tables** = active-active, last-writer-wins."),
      s("real", "Real-world — Aurora Global", "real",
        "The canonical Warm Standby: Aurora Global DB primary + secondary, Route 53 failover with health checks, ECS scaled-down in DR region. Promote secondary in < 1 min."),
    ],
  }),
  lesson({
    day: 75, phase: 6, weekInPhase: 1, phaseProgress: 30,
    topic: "Global Accelerator — anycast IPs + intelligent routing",
    task: "Provision a Global Accelerator pointing at two ALBs in two regions. Get the static anycast IPs. Compare client latency vs Route 53 latency routing.",
    depth: "Global Accelerator, anycast IPs, AWS backbone routing, endpoints groups, traffic dial, NLB integration",
    source: "AWS Global Accelerator docs",
    examWeight: "MEDIUM — Domain 3",
    whyMatters: "Global Accelerator gives you 2 anycast static IPs that route via the AWS global backbone (not public internet) to the nearest healthy endpoint. Sub-second failover. Used for: latency-sensitive apps (gaming, trading), apps that need static IPs (firewalls upstream).",
    howToDoIt: "Create Accelerator → 2 anycast IPs assigned. Add Endpoint Groups (one per region) → add endpoints (ALB / NLB / EC2 / EIP). Set traffic dial (weighted routing) and health checks. Clients hit anycast IP → routed via AWS backbone.",
    watchOutFor: "Global Accelerator ≠ CloudFront. CloudFront caches content; GA routes traffic. They're complementary, not replacements. GA costs $0.025/hr + per-GB.",
    doneWhen: "Clients see < 50 ms latency via AWS backbone vs > 100 ms via public internet. Failover within seconds when primary region health check fails.",
    examTrap: "'Static IP + multi-region failover' = Global Accelerator. 'Cache content globally' = CloudFront. 'DNS-based routing' = Route 53.",
    realWorld: "Real-time multiplayer games (Riot, Epic) and trading platforms run on Global Accelerator. Static IPs upstream firewalls can whitelist. AWS backbone avoids ISP variability.",
    sections: [
      s("intro", "What GA does", "intro",
        "GA gives you 2 anycast static IPs that route via AWS's private global backbone (not public internet) to the nearest healthy endpoint. Anycast = same IP advertised from many edge locations; routers send you to the closest one."),
      s("compare", "GA vs CloudFront vs Route 53", "compare",
        "",
        {
          table: {
            headers: ["Service", "Use case", "Layer"],
            rows: [
              ["Route 53", "DNS routing", "DNS"],
              ["CloudFront", "Cache static + dynamic content at edge", "L7 HTTP"],
              ["Global Accelerator", "TCP/UDP traffic via AWS backbone", "L4"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**Static IPs** (2 anycast) — clients can whitelist them.\n\n**TCP/UDP traffic via AWS backbone** — bypasses ISP variability.\n\n**Sub-second failover** between regions via health checks."),
      s("real", "Real-world — gaming + trading", "real",
        "Multiplayer games use GA for low-latency UDP. Trading platforms use it for static IP firewall whitelisting + AWS backbone routing."),
    ],
  }),
  lesson({
    day: 76, phase: 6, weekInPhase: 2, phaseProgress: 40,
    topic: "Cost optimisation — right-sizing & Savings Plans",
    task: "Run Cost Explorer Rightsizing Recommendations. Compute Optimizer too. Convert one On-Demand EC2 to a 1-yr Compute Savings Plan. Calculate yearly savings.",
    depth: "Right-sizing, Savings Plans (Compute / EC2 Instance / SageMaker), Reserved Instances, Spot, Graviton",
    source: "AWS Cost Optimization Pillar",
    examWeight: "VERY HIGH — Domain 4",
    whyMatters: "Cost optimisation is 20% of the exam and 100% of FinOps. Right-sizing alone often saves 30%. Savings Plans + Spot stack on top for another 50-70%. The exam tests: 'Which commitment vehicle?' and 'Which workload deserves Spot?'.",
    howToDoIt: "Right-size first (free wins from Compute Optimizer). Cover baseline with Compute Savings Plans (most flexible — any instance family, any region). For fault-tolerant batch / ML / CI: Spot, 90% off. Switch to Graviton (g-suffix) for 20% cheaper at equal/better perf.",
    watchOutFor: "Savings Plans commit you for 1 or 3 years. Overcommit and you pay for unused capacity. Spot can be terminated with 2-min warning — only fault-tolerant workloads. Reserved Instances are older and less flexible than Savings Plans for new commitments.",
    doneWhen: "You can articulate the savings stack: right-size → Savings Plan baseline → Spot for burst → Graviton swap.",
    examTrap: "'Maximum flexibility while saving' = Compute Savings Plans (any instance family). 'Specific instance type' = Reserved Instances. 'Fault-tolerant batch' = Spot.",
    realWorld: "FinOps teams stack: SP for baseline (70% of capacity), Spot for batch (90% off), On-Demand for unpredictable surge. Total bill reduction commonly 50-65%.",
    sections: [
      s("rightsizing", "Right-sizing first", "concept",
        "Compute Optimizer reads CloudWatch metrics, recommends specific changes: smaller instance, different family, Graviton swap. Usually 20-50% savings at zero perf risk. Free."),
      s("commitments", "Savings Plans vs Reserved vs Spot", "compare",
        "",
        {
          table: {
            headers: ["Model", "Discount", "Flexibility", "Commitment"],
            rows: [
              ["Compute Savings Plans", "~66%", "Any instance family / region / OS", "1 or 3 yr, $/hr"],
              ["EC2 Instance Savings Plans", "~72%", "Family-locked, region-locked", "1 or 3 yr, $/hr"],
              ["Standard Reserved Instances", "~75%", "Family-locked", "1 or 3 yr, capacity"],
              ["Spot", "~90%", "None — can terminate", "None"],
              ["Graviton swap", "~20% extra", "Just change family", "None"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "**Compute SP is more flexible** than RI — covers any instance family.\n\n**Spot for fault-tolerant only** — batch, ML, CI, stateless web behind ALB.\n\n**Spot Fleet / Mixed Instances Policy** = combo of On-Demand + Spot for safety."),
      s("real", "Real-world — FinOps stack", "real",
        "70% on Savings Plans (steady), 20% Spot (burst + batch), 10% On-Demand (unpredictable). Plus Graviton swap. Typical bill reduction 50-65%."),
    ],
  }),
  lesson({
    day: 77, phase: 6, weekInPhase: 2, phaseProgress: 50,
    topic: "Cost — S3, networking, idle resources",
    task: "Audit your account: unattached EBS volumes (delete), idle EIPs (release), old snapshots (lifecycle), forgotten NAT Gateways (consolidate). Calculate the monthly leakage.",
    depth: "S3 storage class optimisation, Intelligent-Tiering, idle resource hunting, NAT GW consolidation, data transfer costs",
    source: "AWS Cost Optimization Pillar · 'Cost Cleanup' AWS blog",
    examWeight: "HIGH — Domain 4",
    whyMatters: "Idle resources are silent budget killers. Unattached EBS volumes, EIPs not attached to running instances, NAT Gateways in every AZ when one would do, S3 lifecycle never set — these add up to thousands per month at any scale.",
    howToDoIt: "S3 Intelligent-Tiering as default. Lifecycle rules to expire old versions, transition to IA/Glacier. CloudWatch unattached EBS volumes, idle EIPs, orphaned snapshots. Consolidate NAT GWs where ok (one per region instead of per AZ — accept the HA hit if dev). Data transfer costs: same-AZ traffic free, cross-AZ paid, cross-region expensive — design accordingly.",
    watchOutFor: "S3 lifecycle transitions cost money per object (small). Intelligent-Tiering has monitoring fee per object (negligible above ~128 KB). NAT Gateway charges per GB through — sometimes cheaper to provision a VPC Endpoint.",
    doneWhen: "Account hygiene script runs nightly. Unattached resources reported. S3 lifecycle on every bucket.",
    examTrap: "'Optimise S3 with unknown access patterns' = Intelligent-Tiering. 'Long-term archive' = Glacier / Deep Archive lifecycle. 'Cross-AZ traffic costs' = re-architect to keep talking same-AZ.",
    realWorld: "Quarterly account hygiene reviews catch tens of thousands in waste. The savings compound — auto-deleted snapshots, lifecycle-tiered S3, consolidated NAT GWs.",
    sections: [
      s("idle", "Hunt idle resources", "config",
        "",
        {
          code: { lang: "bash", source: '# Unattached EBS volumes\naws ec2 describe-volumes --filters Name=status,Values=available \\\n  --query "Volumes[*].[VolumeId,Size,VolumeType,CreateTime]" --output table\n\n# Unattached Elastic IPs\naws ec2 describe-addresses \\\n  --query "Addresses[?!InstanceId && !NetworkInterfaceId].[PublicIp,AllocationId]" --output table\n\n# Old snapshots\naws ec2 describe-snapshots --owner-ids self \\\n  --query "Snapshots[?StartTime<\\`2024-01-01\\`].[SnapshotId,StartTime,VolumeSize]" --output table' },
        }),
      s("s3-tiering", "S3 lifecycle + Intelligent-Tiering", "config",
        "Set Intelligent-Tiering as the default. Add lifecycle to expire old versions and old non-current versions. Glacier / Deep Archive for compliance archives."),
      s("data-transfer", "Data transfer optimisation", "concept",
        "Same-AZ: free. Cross-AZ: paid. Cross-region: expensive. CloudFront → origin: free egress. VPC Endpoints: avoid NAT data charges to AWS services. Design topology to keep chatty services co-located."),
      s("traps", "Exam traps", "trap",
        "**Egress is the silent killer.** Cross-region replication is $$. CloudFront → S3 = free.\n\n**NAT Gateway per GB** — consider Gateway Endpoint for S3/DynamoDB to bypass.\n\n**Intelligent-Tiering** for unknown patterns; lifecycle for known ones."),
      s("real", "Real-world — quarterly hygiene", "real",
        "Quarterly cleanups catch tens of thousands. Auto-delete snapshots > 90 days, expire old S3 versions, consolidate NATs."),
    ],
  }),
  lesson({
    day: 78, phase: 6, weekInPhase: 2, phaseProgress: 60,
    topic: "Cost — billing alarms, Anomaly Detection, Cost Categories",
    task: "Set up a tiered billing alarm (80%, 100%, 120% of monthly target). Enable Cost Anomaly Detection per service. Define Cost Categories to split spend by team / environment.",
    depth: "AWS Budgets advanced, Cost Anomaly Detection, Cost Categories, allocation tags, consolidated billing",
    source: "AWS Cost Management docs",
    examWeight: "MEDIUM — Domain 4",
    whyMatters: "Reactive cost management (look at the bill at month-end) is too late. Anomaly Detection catches surprises within hours. Cost Categories let FinOps slice without tagging discipline. Tiered budgets warn at multiple thresholds.",
    howToDoIt: "Budgets at 50% / 80% / 100% / 120% — each escalating to a different channel. Anomaly Detection per top service. Cost Categories using rules (e.g., 'if account is in OU prod, category = production').",
    watchOutFor: "Cost Categories computed retroactively when you change rules. Anomaly Detection takes ~10 days to learn baseline.",
    doneWhen: "Tiered budgets emit to email/SNS/PagerDuty as thresholds cross. Cost Categories segment spend correctly.",
    examTrap: "'Allocate spend without tagging' = Cost Categories. 'Detect cost spike' = Anomaly Detection. 'Tiered budget escalation' = multiple Budgets with different notifications.",
    realWorld: "Mature FinOps has 4-tier alerting, weekly Anomaly Detection review, Cost Categories aligned to org chart.",
    sections: [
      s("tiered", "Tiered budget alerts", "concept",
        "Multiple Budgets at different thresholds. 50% → Slack channel. 80% → email engineers. 100% → page on-call. 120% → email VP."),
      s("cost-cat", "Cost Categories", "concept",
        "Computed pseudo-tags. Rules: 'if linked account is in (123, 456, 789), category = Engineering'. 'if tag:CostCenter starts with CC-1, category = Platform'. Categories then appear as a dimension in Cost Explorer and Budgets."),
      s("traps", "Exam traps", "trap",
        "**Cost Categories** = analyst's friend when tagging is inconsistent.\n\n**Anomaly Detection** is ML — gives it 10 days to learn before relying on alerts.\n\n**Consolidated Billing** in AWS Organizations combines billing across accounts + applies volume discounts globally."),
      s("real", "Real-world — 4-tier alerts", "real",
        "50% → Slack ops. 80% → engineering. 100% → on-call. 120% → leadership. Forces conversation early."),
    ],
  }),
  lesson({
    day: 79, phase: 6, weekInPhase: 2, phaseProgress: 70,
    topic: "Performance — caching, autoscaling, choosing the right service",
    task: "Audit a slow flow: where would caching help? Add ElastiCache Redis for a hot read query. Add CloudFront in front of an API. Compare p99 latency.",
    depth: "Caching layers (CloudFront, ElastiCache, DAX), autoscaling triggers, picking the right compute / database service",
    source: "AWS Performance Efficiency Pillar",
    examWeight: "VERY HIGH — Domain 3",
    whyMatters: "Performance optimisation is also cost optimisation — fewer cycles = lower bill. Cache layers reduce DB load. Autoscaling matches capacity to demand. Picking the right service (DynamoDB vs Aurora, Lambda vs ECS) is half of architecture.",
    howToDoIt: "Cache at three levels: CDN (CloudFront), application cache (ElastiCache), DB cache (DAX for DynamoDB, RDS Performance Insights). Autoscale on the right metric (CPU? request count? queue depth? custom?). Pick services based on access pattern: simple KV → DynamoDB; relational with joins → Aurora; analytics → Redshift.",
    watchOutFor: "Cache invalidation is the hard problem. Set sane TTLs and accept some staleness. Autoscaling lag (3-5 min to spin a new instance) — pre-scale for known patterns. Don't pick a service for buzzword reasons.",
    doneWhen: "p99 latency dropped by adding cache. Autoscaling spins up before user impact. Service map (X-Ray) shows clean call graph.",
    examTrap: "'Microsecond reads for DynamoDB' = DAX. 'Cache for SQL' = ElastiCache Redis. 'Edge caching' = CloudFront.",
    realWorld: "Multi-layer caching (CDN + app + DB) is the standard. Latency budgets per layer (e.g., 50ms total = 5ms CDN miss + 10ms app + 5ms cache + 30ms backend).",
    sections: [
      s("layers", "Cache layers", "concept",
        "**CloudFront** — edge cache for static + dynamic content.\n**ElastiCache Redis** — app-tier cache (sessions, query results, leaderboards).\n**DAX** — microsecond cache in front of DynamoDB.\n**RDS Performance Insights** — query-level analysis, not a cache but helps tune."),
      s("choose", "Choosing the right service", "concept",
        "Decision flowchart: simple KV at scale → DynamoDB. Joins / SQL → Aurora. Analytics → Redshift. Time-series → Timestream. Full-text search → OpenSearch. Graph → Neptune. Document → DocumentDB. ML-ready warehouse → Redshift + SageMaker."),
      s("traps", "Exam traps", "trap",
        "**Pick service for access pattern, not buzzword.**\n\n**Autoscale on the bottleneck metric** — for queue worker, scale on queue depth, not CPU.\n\n**Cache invalidation** — TTL + versioned keys is the trick."),
      s("real", "Real-world — latency budget", "real",
        "Plan p99 latency per layer. 50ms total: 5ms edge + 10ms app + 5ms cache + 30ms DB. If any layer exceeds, optimise it."),
    ],
  }),
  lesson({
    day: 80, phase: 6, weekInPhase: 3, phaseProgress: 80,
    topic: "Well-Architected Framework — 6 pillars",
    task: "Run an AWS Well-Architected Review on your capstone app. For each of 6 pillars, list 3 risks and 3 mitigations.",
    depth: "Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, Sustainability",
    source: "AWS Well-Architected Framework whitepaper · WA Tool in console",
    examWeight: "VERY HIGH — exam framing",
    whyMatters: "WAF is the lens AWS uses to evaluate architectures. The exam frames most questions through these pillars — when the answer says 'most operationally excellent', that's a WAF cue. Memorise the 6 pillars and what each cares about.",
    howToDoIt: "Open the Well-Architected Tool in the console. Create a Workload. Answer the questionnaire across all 6 pillars. Tool returns risks + recommendations. Use the same lens during architecture reviews.",
    watchOutFor: "WAF questions are often subjective — 'best practice' lenses. When in doubt: pick the AWS-managed service over self-managed, automation over manual, encryption-at-rest, least-privilege.",
    doneWhen: "You can name all 6 pillars + the question each one asks.",
    examTrap: "'Most operationally efficient' = Operational Excellence pillar. 'Most reliable / available' = Reliability pillar. The lens in the question word tells you which pillar's lens to apply.",
    realWorld: "Major architecture decisions at any AWS shop get reviewed via WA Tool. AWS Solutions Architects use the same lens with customers.",
    sections: [
      s("pillars", "The 6 pillars", "concept",
        "",
        {
          table: {
            headers: ["Pillar", "Core question", "Key services"],
            rows: [
              ["Operational Excellence", "Can you run and monitor systems to deliver value?", "CloudWatch, CloudTrail, SSM, X-Ray"],
              ["Security", "How do you protect information and systems?", "IAM, KMS, WAF, GuardDuty, Shield"],
              ["Reliability", "Can you recover from failures and scale?", "Multi-AZ, ASG, Route 53, AWS Backup"],
              ["Performance Efficiency", "How efficiently are you using compute / storage?", "Right-sizing, CloudFront, Lambda, DAX"],
              ["Cost Optimization", "How do you avoid unnecessary costs?", "Cost Explorer, Savings Plans, Spot, S3 IA"],
              ["Sustainability", "How do you minimise environmental impact?", "Graviton, right-sizing, serverless"],
            ],
          },
        }),
      s("lens", "Using the lens", "concept",
        "When an exam question says 'most cost-effective', filter answers through Cost Optimization. 'Most operationally efficient' = OE pillar. 'Highest reliability' = Reliability. The lens in the question tells you which pillar to think with."),
      s("traps", "Exam traps", "trap",
        "**'Best practice' in AWS-speak** = managed services over self-managed, automation over manual, encryption-at-rest, least-privilege, multi-AZ.\n\n**Sustainability** (newest pillar) — Graviton, serverless, right-sizing."),
      s("real", "Real-world — WA reviews", "real",
        "AWS Solutions Architects run formal WA reviews. Internal teams use the same lens for architecture reviews. It's the canonical 'is this a good design?' framework."),
    ],
  }),
  lesson({
    day: 81, phase: 6, weekInPhase: 3, phaseProgress: 90,
    topic: "Well-Architected lenses — Serverless, SaaS, IoT, ML",
    task: "Pick the Serverless Lens. Re-review your serverless capstone through it. Identify gaps the base framework didn't catch.",
    depth: "Serverless Lens, SaaS Lens, IoT Lens, ML Lens, Data Analytics Lens",
    source: "AWS WA Lenses",
    examWeight: "LOW — context only",
    whyMatters: "Lenses are domain-specific extensions of WAF. Serverless Lens has best practices specific to Lambda (cold start mitigation, idempotency, observability). SaaS Lens covers multi-tenancy isolation. IoT Lens covers edge compute. ML Lens covers training/serving.",
    howToDoIt: "Apply a lens in the WA Tool. Answer additional lens-specific questions. Get lens-specific risks + recommendations on top of the base framework.",
    watchOutFor: "Lenses are paid context (WAF base is free). Worth it during major project kickoffs.",
    doneWhen: "You know which lens fits which workload type.",
    examTrap: "Lenses themselves rarely show up directly on the exam — but the principles do (e.g., 'idempotent Lambda' is a Serverless Lens best practice).",
    realWorld: "Lenses standardise reviews for specific architectures. Saas Lens especially common at companies building multi-tenant platforms.",
    sections: [
      s("lenses", "The lenses", "compare",
        "",
        {
          table: {
            headers: ["Lens", "Focus"],
            rows: [
              ["Serverless Lens", "Lambda, API Gateway, Step Functions, DynamoDB"],
              ["SaaS Lens", "Multi-tenant isolation, tenant onboarding, metering"],
              ["IoT Lens", "Edge compute, Greengrass, telemetry pipelines"],
              ["ML Lens", "Training, serving, MLOps, model lifecycle"],
              ["Data Analytics Lens", "Data lakes, ETL, warehousing, BI"],
            ],
          },
        }),
      s("traps", "Exam traps", "trap",
        "Lenses themselves rarely tested directly — but their principles seep into questions: idempotent Lambda, tenant isolation, edge inference."),
      s("real", "Real-world — SaaS Lens", "real",
        "Multi-tenant SaaS platforms run SaaS Lens reviews. Tenant isolation, onboarding, metering, noisy neighbour — covered systematically."),
    ],
  }),
  capstone(82, 6, 3, 100,
    "Phase 6 capstone — Multi-Region DR",
    "Implement the Multi-Region DR capstone: us-east-1 primary, us-west-2 warm standby, Aurora Global DB, Route 53 failover, Lambda promotion runbook. Run a real game-day: simulate region failure, fail over, fail back. Document RTO/RPO achieved."),
];
